'use client';

import {ReactNode,useEffect,useMemo,useState} from 'react';
import {usePathname,useRouter} from 'next/navigation';
import {Bell,Boxes,ClipboardCheck,Home,MapPinned,Menu,PackageSearch,ReceiptText,Route,Settings,ShieldCheck,ShoppingCart,Users,WalletCards} from 'lucide-react';
import BitalisLogo from '@/components/BitalisLogo';

type User={id:string;role:string;firstName?:string;lastName?:string;email?:string};
const menus:Record<string,{href:string;label:string;icon:any}[]>={
COBRADOR:[{href:'/dashboard',label:'Inicio',icon:Home},{href:'/route',label:'Ruta',icon:Route},{href:'/collections',label:'Cobrar',icon:WalletCards},{href:'/clients',label:'Clientes',icon:Users},{href:'/notifications',label:'Más',icon:Menu}],
VENDEDOR:[{href:'/dashboard',label:'Inicio',icon:Home},{href:'/sales/new',label:'Venta',icon:ShoppingCart},{href:'/clients',label:'Clientes',icon:Users},{href:'/products',label:'Productos',icon:PackageSearch},{href:'/notifications',label:'Más',icon:Menu}],
SUPERVISOR:[{href:'/dashboard',label:'Inicio',icon:Home},{href:'/authorizations',label:'Autorizar',icon:ShieldCheck},{href:'/route',label:'Ruta',icon:MapPinned},{href:'/notifications',label:'Alertas',icon:Bell},{href:'/control-center',label:'Más',icon:Menu}],
ADMIN:[{href:'/dashboard',label:'Inicio',icon:Home},{href:'/control-center',label:'Control',icon:Boxes},{href:'/cash',label:'Caja',icon:ReceiptText},{href:'/inventory',label:'Inventario',icon:ClipboardCheck},{href:'/settings',label:'Más',icon:Settings}],
};
export default function AppShell({children,title}:{children:ReactNode;title?:string}){const router=useRouter(),pathname=usePathname();const[user,setUser]=useState<User|null>(null);useEffect(()=>{try{const raw=localStorage.getItem('bitalis_auth_user');if(raw)setUser(JSON.parse(raw));}catch{}},[]);const role=(user?.role||'ADMIN').toUpperCase();const nav=useMemo(()=>menus[role]||menus.ADMIN,[role]);return <div className="min-h-screen bg-[#F3F4F6] text-[#2B2B2B] pb-24"><header className="sticky top-0 z-40 border-b border-slate-200/80 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3"><div className="flex items-center gap-3"><BitalisLogo size="md" variant="light"/><div className="hidden sm:block"><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#C79A3B]">{role}</p><h1 className="text-sm font-black text-[#12224A]">{title||'BITALIS'}</h1></div></div><button onClick={()=>router.push('/notifications')} className="relative flex h-11 w-11 items-center justify-center rounded-2xl border border-slate-200 bg-white text-[#12224A]" aria-label="Notificaciones"><Bell className="h-5 w-5"/></button></div></header><main>{children}</main><nav className="fixed inset-x-0 bottom-0 z-50 border-t border-slate-200 bg-white/98 px-2 pb-[max(.5rem,env(safe-area-inset-bottom))] pt-2 shadow-[0_-12px_30px_rgba(18,34,74,.08)]"><div className="mx-auto grid max-w-xl grid-cols-5 gap-1">{nav.map(({href,label,icon:Icon})=>{const active=href==='/dashboard'?pathname===href:pathname.startsWith(href);return <button key={href} onClick={()=>router.push(href)} className={`flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl text-[10px] font-black transition focus:outline-none focus:ring-2 focus:ring-[#FF6A00] ${active?'bg-[#12224A] text-white':'text-slate-500 hover:bg-slate-100'}`}><Icon className="h-5 w-5"/><span>{label}</span></button>})}</div></nav></div>}
