'use client';

import {ReactNode} from 'react';
import {CheckCircle2,Loader2,MapPin,Wifi,WifiOff,X,AlertTriangle} from 'lucide-react';

export const cx=(...v:(string|false|null|undefined)[])=>v.filter(Boolean).join(' ');
export function Button({children,variant='primary',loading=false,className='',...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'action'|'outline'|'danger'|'ghost';loading?:boolean}){const map={primary:'bg-[#12224A] text-white',action:'bg-[#FF6A00] text-white',outline:'border border-slate-200 bg-white text-[#12224A]',danger:'bg-red-600 text-white',ghost:'bg-transparent text-[#12224A]'};return <button {...props} disabled={props.disabled||loading} className={cx('inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl px-4 text-sm font-black transition focus-visible:ring-2 focus-visible:ring-[#FF6A00] disabled:cursor-not-allowed disabled:opacity-50',map[variant],className)}>{loading&&<Loader2 className="h-4 w-4 animate-spin"/>}{children}</button>}
export function Input({label,error,className='',...props}:React.InputHTMLAttributes<HTMLInputElement>&{label?:string;error?:string}){return <label className="block"><span className="mb-2 block text-xs font-black text-slate-600">{label}</span><input {...props} className={cx('min-h-12 w-full rounded-2xl border border-slate-200 bg-white px-4 text-sm text-[#2B2B2B] outline-none focus:border-[#FF6A00] focus:ring-2 focus:ring-orange-100',className)}/>{error&&<span className="mt-1 block text-xs font-bold text-red-600">{error}</span>}</label>}
export function Select({label,children,className='',...props}:React.SelectHTMLAttributes<HTMLSelectElement>&{label?:string}){return <label className="block"><span className="mb-2 block text-xs font-black text-slate-600">{label}</span><select {...props} className={cx('min-h-12 w-full rounded-2xl border border-slate-200 bg-white px-4 text-sm outline-none focus:border-[#FF6A00] focus:ring-2 focus:ring-orange-100',className)}>{children}</select></label>}
export function Card({children,className=''}:{children:ReactNode;className?:string}){return <section className={cx('rounded-3xl border border-slate-200 bg-white p-4 shadow-sm',className)}>{children}</section>}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'success'|'danger'|'warning'|'info'}){const m={neutral:'bg-slate-100 text-slate-600',success:'bg-emerald-50 text-emerald-700',danger:'bg-red-50 text-red-700',warning:'bg-amber-50 text-amber-700',info:'bg-blue-50 text-blue-700'};return <span className={cx('inline-flex rounded-full px-2.5 py-1 text-[10px] font-black',m[tone])}>{children}</span>}
export function Alert({children,tone='warning'}:{children:ReactNode;tone?:'warning'|'danger'|'success'|'info'}){const m={warning:'border-amber-200 bg-amber-50 text-amber-800',danger:'border-red-200 bg-red-50 text-red-700',success:'border-emerald-200 bg-emerald-50 text-emerald-700',info:'border-blue-200 bg-blue-50 text-blue-700'};return <div role="status" className={cx('rounded-2xl border p-4 text-sm font-bold',m[tone])}>{children}</div>}
export function Modal({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:ReactNode}){if(!open)return null;return <div className="fixed inset-0 z-[120] flex items-end justify-center bg-[#12224A]/60 p-0 backdrop-blur-sm sm:items-center sm:p-4" role="dialog" aria-modal="true" aria-label={title}><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-t-[28px] bg-white p-5 shadow-2xl sm:rounded-[28px]"><div className="flex items-center justify-between"><h2 className="text-lg font-black text-[#12224A]">{title}</h2><button onClick={onClose} className="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-100" aria-label="Cerrar"><X className="h-4 w-4"/></button></div><div className="mt-4">{children}</div></div></div>}
export function ConfirmDialog({open,title,message,onCancel,onConfirm,busy=false}:{open:boolean;title:string;message:string;onCancel:()=>void;onConfirm:()=>void;busy?:boolean}){return <Modal open={open} onClose={onCancel} title={title}><p className="text-sm leading-6 text-slate-600">{message}</p><div className="mt-5 grid grid-cols-2 gap-2"><Button variant="outline" onClick={onCancel}>Cancelar</Button><Button variant="action" onClick={onConfirm} loading={busy}>Confirmar</Button></div></Modal>}
export function Skeleton({className='h-12'}:{className?:string}){return <div className={cx('animate-pulse rounded-2xl bg-slate-200',className)} aria-hidden="true"/>}
export function EmptyState({title='Sin registros',text='No hay información para mostrar.'}:{title?:string;text?:string}){return <div className="rounded-3xl border border-dashed border-slate-300 bg-white p-8 text-center"><p className="font-black text-[#12224A]">{title}</p><p className="mt-2 text-sm text-slate-500">{text}</p></div>}
export function MoneyDisplay({value,className=''}:{value:number|string|null|undefined;className?:string}){const n=Number(value||0);return <span className={cx('font-black tabular-nums',className)}>{new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n)}</span>}
export function RiskBadge({risk}:{risk?:string|null}){const r=String(risk||'LOW').toUpperCase();return <Badge tone={r==='CRITICAL'||r==='HIGH'?'danger':r==='MEDIUM'?'warning':'success'}>{r}</Badge>}
export function StatusBadge({status}:{status?:string|null}){const s=String(status||'PENDING').toUpperCase();const tone=s.includes('ERROR')||s.includes('REJECT')||s.includes('OVERDUE')?'danger':s.includes('PENDING')||s.includes('QUEUE')?'warning':s.includes('ACTIVE')||s.includes('APPROVED')||s.includes('COMPLETED')||s.includes('VERIFIED')?'success':'neutral';return <Badge tone={tone as any}>{s}</Badge>}
export function GPSIndicator({active,accuracy}:{active:boolean;accuracy?:number}){return <span className={cx('inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[10px] font-black',active?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700')}><MapPin className="h-3 w-3"/>{active?`GPS${accuracy?` ${Math.round(accuracy)}m`:''}`:'SIN GPS'}</span>}
export function SyncIndicator({online,queued=0,syncing=false}:{online:boolean;queued?:number;syncing?:boolean}){return <span className={cx('inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[10px] font-black',online?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700')}>{online?<Wifi className="h-3 w-3"/>:<WifiOff className="h-3 w-3"/>}{syncing?'SINCRONIZANDO':online?queued?`${queued} PENDIENTE(S)`:'CONECTADO':'SIN CONEXIÓN'}</span>}
export function KPI({label,value,icon:Icon}:{label:string;value:ReactNode;icon?:any}){return <Card>{Icon&&<Icon className="h-5 w-5 text-[#C79A3B]"/>}<p className="mt-3 text-[10px] font-black uppercase tracking-[.11em] text-slate-400">{label}</p><div className="mt-1 text-xl font-black text-[#12224A]">{value}</div></Card>}
export function CustomerCard({name,folio,balance,risk,onClick}:{name:string;folio?:string;balance?:number;risk?:string;onClick?:()=>void}){return <button onClick={onClick} className="w-full rounded-3xl border border-slate-200 bg-white p-4 text-left shadow-sm"><div className="flex items-start justify-between gap-3"><div><RiskBadge risk={risk}/><p className="mt-2 font-black text-[#12224A]">{name}</p><p className="text-xs text-slate-500">{folio}</p></div>{balance!=null&&<MoneyDisplay value={balance} className="text-[#12224A]"/>}</div></button>}
export function RouteCard(props:{name:string;balance:number;suggested?:number;distance?:string;risk?:string;onCollect?:()=>void}){return <Card><div className="flex items-start justify-between"><div><RiskBadge risk={props.risk}/><h3 className="mt-2 font-black text-[#12224A]">{props.name}</h3><p className="mt-1 text-xs text-slate-500">{props.distance||'Distancia no disponible'}</p></div><MoneyDisplay value={props.balance}/></div>{props.suggested!=null&&<p className="mt-3 text-xs text-slate-500">Sugerido <MoneyDisplay value={props.suggested}/></p>}{props.onCollect&&<Button variant="action" onClick={props.onCollect} className="mt-4 w-full">COBRAR</Button>}</Card>}
export function PaymentButton({amount,onClick}:{amount:number;onClick:()=>void}){return <Button variant="outline" onClick={onClick}>${amount.toLocaleString('es-MX')}</Button>}
export function Timeline({items}:{items:{id?:string;title:string;detail?:string;date?:string}[]}){return <div className="space-y-3">{items.map((x,i)=><div key={x.id||i} className="flex gap-3"><div className="mt-1 h-3 w-3 shrink-0 rounded-full bg-[#C79A3B]"/><div><p className="text-sm font-black text-[#12224A]">{x.title}</p>{x.detail&&<p className="text-xs text-slate-500">{x.detail}</p>}{x.date&&<p className="mt-1 text-[10px] text-slate-400">{x.date}</p>}</div></div>)}</div>}
export function ApprovalCard({type,title,detail,onApprove,onReject}:{type:string;title:string;detail?:string;onApprove:()=>void;onReject:()=>void}){return <Card><Badge tone="warning">{type}</Badge><h3 className="mt-3 font-black text-[#12224A]">{title}</h3>{detail&&<p className="mt-1 text-sm text-slate-500">{detail}</p>}<div className="mt-4 grid grid-cols-2 gap-2"><Button variant="danger" onClick={onReject}>RECHAZAR</Button><Button onClick={onApprove}>APROBAR</Button></div></Card>}
export function CashSummary({expected,counted,difference}:{expected:number;counted?:number;difference?:number}){return <Card><p className="text-xs font-black text-slate-500">Caja</p><div className="mt-3 grid grid-cols-3 gap-2"><div><small>Esperado</small><br/><MoneyDisplay value={expected}/></div><div><small>Contado</small><br/><MoneyDisplay value={counted||0}/></div><div><small>Diferencia</small><br/><MoneyDisplay value={difference||0}/></div></div></Card>}
export function InventoryCard({name,sku,physical,reserved,available}:{name:string;sku:string;physical:number;reserved:number;available:number}){return <Card><h3 className="font-black text-[#12224A]">{name}</h3><p className="text-xs text-slate-400">{sku}</p><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><div>Físico<br/><b>{physical}</b></div><div>Reservado<br/><b>{reserved}</b></div><div>Disponible<br/><b>{available}</b></div></div></Card>}
export const MobileCard=Card;
export function DataTable({children}:{children:ReactNode}){return <div className="w-full overflow-x-auto rounded-3xl border border-slate-200 bg-white">{children}</div>}
export function Toast({message,tone='success'}:{message:string;tone?:'success'|'warning'|'danger'}){return <div className={cx('fixed inset-x-4 bottom-24 z-[130] mx-auto max-w-md rounded-2xl p-4 text-sm font-black shadow-2xl',tone==='success'?'bg-emerald-600 text-white':tone==='warning'?'bg-amber-500 text-slate-950':'bg-red-600 text-white')}>{tone==='success'?<CheckCircle2 className="mr-2 inline h-4 w-4"/>:<AlertTriangle className="mr-2 inline h-4 w-4"/>}{message}</div>}
export const Drawer=Modal;
