'use client';

import {useCallback,useEffect,useState} from 'react';
import {AlertTriangle,CheckCircle2,CloudOff,CloudUpload,Loader2,RefreshCw,Trash2,X} from 'lucide-react';
import AppShell from '@/components/phase15/AppShell';
import {listQueued,removeQueued,OfflineOperation} from '@/lib/phase15/offlineQueue';
import {syncQueuedOperations} from '@/lib/phase15/syncQueue';
import {haptic} from '@/lib/ux/haptics';

const label=(kind:string)=>({PAYMENT:'Cobro',VISIT:'Visita',CLIENT_INTAKE:'Alta de cliente',RESCHEDULE:'Reprogramación',EXPENSE:'Gasto',DOWN_PAYMENT:'Enganche'} as Record<string,string>)[kind]||kind||'Operación';

export default function SyncPage(){
 const[rows,setRows]=useState<OfflineOperation[]>([]),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[online,setOnline]=useState(true),[message,setMessage]=useState(''),[discarding,setDiscarding]=useState<OfflineOperation|null>(null),[working,setWorking]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{setRows(await listQueued());}finally{setLoading(false);}},[]);
 useEffect(()=>{setOnline(navigator.onLine);void load();const on=()=>{setOnline(true);void load();},off=()=>setOnline(false),changed=()=>void load();window.addEventListener('online',on);window.addEventListener('offline',off);window.addEventListener('bitalis:queue-changed',changed);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off);window.removeEventListener('bitalis:queue-changed',changed);};},[load]);
 const sync=async()=>{if(!online||syncing)return;haptic('tap');setSyncing(true);setMessage('');try{const r=await syncQueuedOperations();setMessage(r.failed?`${r.synced} sincronizada(s), ${r.failed} con error.`:`${r.synced} operación(es) sincronizada(s).`);haptic(r.failed?'error':'success');}catch(e:any){setMessage(e?.message||'No pudimos sincronizar.');haptic('error');}finally{setSyncing(false);await load();}};
 const askDiscard=(r:OfflineOperation)=>{haptic('tap');setDiscarding(r);};
 const discard=async()=>{if(!discarding||working)return;setWorking(true);try{await removeQueued(discarding.id);setDiscarding(null);setMessage('Operación eliminada del dispositivo.');haptic('success');await load();}catch(e:any){setMessage(e?.message||'No pudimos eliminar la operación.');haptic('error');}finally{setWorking(false);}};
 const pending=rows.filter(r=>r.state!=='SYNCED');
 return <AppShell title="Sincronización"><main className="mx-auto max-w-4xl px-3 py-3 sm:px-4 sm:py-5">
  <section className="rounded-[24px] bg-[var(--bitalis-primary)] p-4 text-white sm:rounded-[28px] sm:p-5"><p className="text-[10px] font-black uppercase tracking-[.14em] text-[var(--bitalis-mint)]">Modo offline</p><h1 className="mt-2 text-xl font-black sm:text-2xl">Centro de sincronización</h1><p className="mt-2 text-xs leading-5 text-emerald-50/80 sm:text-sm">Las operaciones pendientes permanecen en este dispositivo hasta que el servidor confirme su recepción.</p></section>
  <div className={`mt-3 rounded-2xl border p-3 sm:mt-4 sm:p-4 ${online?'border-emerald-200 bg-emerald-50 text-emerald-800':'border-red-200 bg-red-50 text-red-800'}`}><div className="flex items-center gap-3">{online?<CheckCircle2 className="h-5 w-5 shrink-0"/>:<CloudOff className="h-5 w-5 shrink-0"/>}<div className="min-w-0 flex-1"><p className="text-sm font-black">{online?'Conectado':'Sin conexión'}</p><p className="text-xs">{online?pending.length?`${pending.length} operación(es) pendiente(s).`:'Todo está sincronizado.':'Las operaciones seguirán guardadas en este dispositivo.'}</p></div></div><button disabled={!online||syncing||!pending.length} onClick={()=>void sync()} className="mt-3 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-[var(--bitalis-action)] px-4 text-xs font-black text-white disabled:opacity-40">{syncing?<Loader2 className="h-4 w-4 animate-spin"/>:<CloudUpload className="h-4 w-4"/>}{syncing?'SINCRONIZANDO…':'SINCRONIZAR AHORA'}</button></div>
  {message&&<div className="mt-3 rounded-2xl border border-[var(--bitalis-border)] bg-white p-3 text-sm font-bold text-[var(--bitalis-primary)]">{message}</div>}
  {loading?<div className="flex justify-center p-12"><Loader2 className="h-6 w-6 animate-spin text-[var(--bitalis-primary)]"/></div>:<section className="mt-3 space-y-3">{pending.map(r=><article key={r.id} className="rounded-3xl border border-[var(--bitalis-border)] bg-white p-4 shadow-sm"><div className="flex items-start gap-3"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl ${r.state==='FAILED'?'bg-red-50 text-red-600':'bg-amber-50 text-amber-600'}`}>{r.state==='FAILED'?<AlertTriangle className="h-5 w-5"/>:<RefreshCw className="h-5 w-5"/>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-black text-[var(--bitalis-primary)]">{label(r.kind)}</h2><span className="rounded-full bg-slate-100 px-2 py-1 text-[9px] font-black text-slate-600">{r.state}</span></div><p className="mt-1 break-all text-[10px] text-slate-400">{r.idempotencyKey}</p><p className="mt-2 text-xs text-slate-500">Guardada {new Date(r.createdAt).toLocaleString('es-MX')} · intentos {r.attempts}</p>{r.lastError&&<p className="mt-2 text-xs font-bold text-red-600">{r.lastError}</p>}</div><button onClick={()=>askDiscard(r)} className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl border border-red-100 bg-red-50 text-red-600" aria-label="Eliminar operación pendiente"><Trash2 className="h-4 w-4"/></button></div></article>)}{!pending.length&&<div className="rounded-3xl border border-emerald-200 bg-emerald-50 p-8 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-emerald-600"/><p className="mt-3 font-black text-emerald-800">Todo sincronizado</p><p className="mt-1 text-sm text-emerald-700">No hay operaciones pendientes en este dispositivo.</p></div>}</section>}
  {discarding&&<div data-no-swipe className="fixed inset-0 z-[150] flex items-end bg-slate-950/55 sm:items-center sm:justify-center sm:p-4" onClick={()=>!working&&setDiscarding(null)}><section onClick={e=>e.stopPropagation()} className="bitalis-bottom-sheet w-full p-4 pb-[max(1rem,env(safe-area-inset-bottom))] sm:max-w-sm sm:rounded-[28px] sm:p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-red-600">Eliminar pendiente</p><h2 className="mt-1 text-lg font-black text-[var(--bitalis-primary)]">¿Descartar esta operación?</h2></div><button disabled={working} onClick={()=>setDiscarding(null)} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-600 disabled:opacity-50" aria-label="Cerrar"><X className="h-4 w-4"/></button></div><p className="mt-3 text-sm leading-6 text-slate-600">Se eliminará únicamente de este dispositivo y <b>no se enviará al servidor</b>. Úsalo solo si confirmaste que la operación no debe sincronizarse.</p><div className="mt-4 grid grid-cols-2 gap-2"><button disabled={working} onClick={()=>setDiscarding(null)} className="min-h-12 rounded-2xl border border-[var(--bitalis-border)] bg-white text-xs font-black text-[var(--bitalis-primary)] disabled:opacity-50">CANCELAR</button><button disabled={working} onClick={()=>void discard()} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-red-600 px-3 text-xs font-black text-white disabled:opacity-50">{working?<Loader2 className="h-4 w-4 animate-spin"/>:<Trash2 className="h-4 w-4"/>}ELIMINAR</button></div></section></div>}
 </main></AppShell>;
}
