import {NextRequest,NextResponse} from 'next/server';
import {PrismaService} from '@/src/database/prisma.service';
import {InventoryService} from '@/src/inventory/inventory.service';
import {extractUserContext} from '@/src/sales/sales-auth.helper';
import {PermissionService} from '@/src/server/auth/permission.service';

function httpStatus(message:string){return message.includes('UNAUTHORIZED')?401:message.startsWith('FORBIDDEN:')?403:400;}
export async function GET(req:NextRequest){try{const user=await extractUserContext(req);await PermissionService.requirePermission(user.userId,'inventory.view');const prisma=PrismaService.getInstance();const logs=await prisma.auditLog.findMany({where:{action:'INVENTORY_PHYSICAL_COUNT'},orderBy:{createdAt:'desc'},take:100});return NextResponse.json({success:true,counts:logs.map(log=>{let detail:any={};try{detail=JSON.parse(log.newValues||'{}')}catch{}return{id:log.id,userId:log.userId,createdAt:log.createdAt,...detail}})},{headers:{'Cache-Control':'no-store'}});}catch(error:any){const message=String(error?.message||'No pudimos consultar los conteos.');return NextResponse.json({success:false,error:message},{status:httpStatus(message)});}}
export async function POST(req:NextRequest){try{const user=await extractUserContext(req);await PermissionService.requirePermission(user.userId,'inventory.manage');const body=await req.json();const warehouseId=String(body?.warehouseId||''),productId=String(body?.productId||''),reason=String(body?.reason||'').trim(),countedQuantity=Number(body?.countedQuantity);if(!warehouseId||!productId)throw new Error('Selecciona producto y almacén.');if(!Number.isInteger(countedQuantity)||countedQuantity<0)throw new Error('El conteo físico debe ser un entero igual o mayor a cero.');const stock=await InventoryService.getStock(warehouseId,productId);const systemQuantity=Number(stock.quantityOnHand||0),variance=countedQuantity-systemQuantity;if(variance!==0&&!reason)throw new Error('Explica el motivo de la diferencia.');if(countedQuantity<Number(stock.quantityReserved||0))throw new Error('El conteo no puede ser menor que las unidades reservadas; revisa las reservas antes de ajustar.');const idempotencyKey=String(body?.idempotencyKey||'')||undefined;if(variance!==0)await InventoryService.adjustStock({warehouseId,productId,quantityDelta:variance,reason:`Conteo físico: ${reason}`,userId:user.userId,idempotencyKey});const prisma=PrismaService.getInstance();const detail={warehouseId,productId,systemQuantity,countedQuantity,variance,reason:reason||'Sin diferencia',idempotencyKey};const log=await prisma.auditLog.create({data:{userId:user.userId,action:'INVENTORY_PHYSICAL_COUNT',entity:'InventoryStock',entityId:`${warehouseId}:${productId}`,newValues:JSON.stringify(detail),idempotencyKey}});return NextResponse.json({success:true,count:{id:log.id,createdAt:log.createdAt,...detail}});}catch(error:any){const message=String(error?.message||'No pudimos registrar el conteo.');return NextResponse.json({success:false,error:message},{status:httpStatus(message)});}}
