'use client';
import {useEffect,useMemo,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import {Banknote,ChevronRight,Loader2,MapPin,Phone,Search,ShieldCheck,X} from 'lucide-react';
import AppShell from '@/components/phase15/AppShell';
import {apiClient,newIdempotencyKey} from '@/lib/phase15/apiClient';
import {queueOperation} from '@/lib/phase15/offlineQueue';
import {haptic} from '@/lib/ux/haptics';

type Row={id:string;saleId?:string|null;saleNumber?:string|null;hasSale?:boolean;hasActiveCredit?:boolean;saldoActual:number;suggestedInstallment:number;client:{id:string;clientNumber:string;firstName:string;lastName:string;secondLastName?:string|null;phone?:string;latitude?:number|null;longitude?:number|null;riskLevel?:string}};
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'});
export default function CollectionsPage(){
 const router=useRouter(),searchParams=useSearchParams();
 const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[selected,setSelected]=useState<Row|null>(null),[amount,setAmount]=useState(''),[method,setMethod]=useState<'CASH'|'BANK_TRANSFER'>('CASH'),[saving,setSaving]=useState(false),[confirmOpen,setConfirmOpen]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[position,setPosition]=useState<any>(null);
 const load=async()=>{setLoading(true);setError('');try{const j:any=await apiClient('/api/collections/portfolio?scope=all');const next:Row[]=j?.data||[];setRows(next);const found=next.find(x=>x.id===searchParams.get('credit'));if(found?.hasActiveCredit!==false)setSelected(found||null)}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{void load();navigator.geolocation?.getCurrentPosition(p=>setPosition({lat:p.coords.latitude,lng:p.coords.longitude}),()=>{},{enableHighAccuracy:true,timeout:8000})},[]);
 useEffect(()=>{if(selected){setAmount(String(Math.min(Number(selected.suggestedInstallment||0)||Number(selected.saldoActual),Number(selected.saldoActual))));setConfirmOpen(false)}},[selected?.id]);
 const filtered=useMemo(()=>rows.filter(x=>`${x.client.firstName} ${x.client.lastName} ${x.client.secondLastName||''} ${x.client.clientNumber} ${x.client.phone||''} ${x.saleNumber||''}`.toLowerCase().includes(query.trim().toLowerCase())),[rows,query]);
 const value=Number(amount),valid=!!selected&&Number.isFinite(value)&&value>0&&value<=Number(selected.saldoActual);
 const submit=async()=>{if(!selected||!valid)return;setSaving(true);setError('');const key=newIdempotencyKey('collection'),body={creditId:selected.id,amount:value,paymentMethod:method,clientCapturedAt:new Date().toISOString(),gpsLatitude:position?.lat,gpsLongitude:position?.lng,notes:'Cobro BITALIS',idempotencyKey:key};try{if(!navigator.onLine){await queueOperation({endpoint:'/api/payments',method:'POST',body,idempotencyKey:key,kind:'PAYMENT'});setMessage(`Cobro ${money.format(value)} guardado para sincronizar.`)}else{await apiClient('/api/payments',{method:'POST',body:JSON.stringify(body),idempotencyKey:key});setMessage(`Cobro ${money.format(value)} registrado.`);await load()}setSelected(null);setConfirmOpen(false);haptic('success')}catch(e:any){setError(e.message);haptic('error')}finally{setSaving(false)}};
 return <AppShell title="Cobranza"><main className="mx-auto max-w-6xl px-3 py-3 pb-28 sm:px-4 sm:py-5"><section className="rounded-[24px] bg-[var(--bitalis-primary)] p-4 text-white sm:p-5"><p className="text-[10px] font-black uppercase tracking-[.14em] text-[var(--bitalis-mint)]">Cobranza rápida</p><h1 className="mt-1 text-2xl font-black">Cobrar</h1><p className="mt-2 text-sm text-emerald-50/80">Busca cualquier cliente. Si su venta no tiene crédito, podrás abrirla y completar su calendario.</p></section>
 {error&&<div role="alert" className="mt-3 rounded-2xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}{message&&<div className="mt-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-bold text-emerald-700">{message}</div>}
 {selected?<PaymentForm row={selected} amount={amount} setAmount={setAmount} method={method} setMethod={setMethod} valid={valid} onBack={()=>setSelected(null)} onReview={()=>setConfirmOpen(true)}/>:<><div className="relative mt-3"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nombre, teléfono, cliente o folio de venta" className="min-h-14 w-full rounded-2xl border bg-white pl-11 pr-4 text-sm"/></div>{loading?<div className="flex justify-center p-12"><Loader2 className="h-6 w-6 animate-spin"/></div>:<div className="mt-3 space-y-2">{filtered.map(x=><ClientRow key={x.id} row={x} onOpen={()=>x.hasActiveCredit===false?router.push(x.saleId?`/sales/${x.saleId}`:`/clients/${x.client.id}`):setSelected(x)} onClient={()=>router.push(`/clients/${x.client.id}`)}/>)}{!filtered.length&&<div className="rounded-3xl border bg-white p-8 text-center text-sm text-slate-500">No encontramos clientes con ese nombre, teléfono o folio.</div>}</div>}</>}
 {confirmOpen&&selected&&<div className="fixed inset-0 z-[80] flex items-end bg-black/35" onClick={()=>!saving&&setConfirmOpen(false)}><section onClick={e=>e.stopPropagation()} className="bitalis-bottom-sheet bitalis-safe-bottom w-full p-4 sm:mx-auto sm:max-w-lg"><div className="flex justify-between"><div><p className="text-xs font-black text-emerald-700">CONFIRMACIÓN FINAL</p><h2 className="text-2xl font-black">{money.format(value)}</h2><p>{selected.client.firstName} {selected.client.lastName}</p></div><button onClick={()=>setConfirmOpen(false)} className="h-12 w-12 rounded-2xl bg-slate-100"><X className="mx-auto h-5 w-5"/></button></div><button disabled={saving} onClick={()=>void submit()} className="mt-4 flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-[var(--bitalis-action)] font-black text-white"><ShieldCheck className="h-5 w-5"/>{saving?'REGISTRANDO…':'CONFIRMAR COBRO'}</button></section></div>}
 </main></AppShell>}
function ClientRow({row,onOpen,onClient}:{row:Row;onOpen:()=>void;onClient:()=>void}){const inactive=row.hasActiveCredit===false;return <article className="rounded-3xl border bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex gap-2"><span className="rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-black text-emerald-700">{inactive?'SIN CRÉDITO':row.client.riskLevel||'LOW'}</span><span className="text-[10px] text-slate-400">{row.client.clientNumber}</span></div><h2 className="mt-2 truncate text-lg font-black">{row.client.firstName} {row.client.lastName}</h2><p className="mt-1 text-xs text-slate-500">{inactive?(row.hasSale?`Venta ${row.saleNumber} · falta crear crédito`:'Sin venta a crédito activa'):`Saldo ${money.format(Number(row.saldoActual))} · sugerido ${money.format(Number(row.suggestedInstallment||0))}`}</p></div><button onClick={()=>{haptic('tap');onOpen()}} className={`flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl text-white ${inactive?'bg-slate-500':'bg-[var(--bitalis-action)]'}`}><ChevronRight className="h-5 w-5"/></button></div><div className="mt-3 grid grid-cols-3 gap-2"><a href={`tel:${row.client.phone||''}`} className="flex min-h-12 items-center justify-center gap-1 rounded-xl bg-slate-50 text-[10px] font-black"><Phone className="h-4 w-4"/>Llamar</a><button onClick={onClient} className="flex min-h-12 items-center justify-center gap-1 rounded-xl bg-slate-50 text-[10px] font-black"><Banknote className="h-4 w-4"/>Cliente</button><button disabled={row.client.latitude==null} onClick={()=>window.open(`https://www.google.com/maps/search/?api=1&query=${row.client.latitude},${row.client.longitude}`,'_blank')} className="flex min-h-12 items-center justify-center gap-1 rounded-xl bg-slate-50 text-[10px] font-black disabled:opacity-40"><MapPin className="h-4 w-4"/>Mapa</button></div></article>}
function PaymentForm({row,amount,setAmount,method,setMethod,valid,onBack,onReview}:{row:Row;amount:string;setAmount:(v:string)=>void;method:'CASH'|'BANK_TRANSFER';setMethod:(v:'CASH'|'BANK_TRANSFER')=>void;valid:boolean;onBack:()=>void;onReview:()=>void}){return <section className="mt-3 rounded-[24px] border bg-white p-4"><button onClick={onBack} className="min-h-12 text-xs font-black text-slate-500">← Cambiar cliente</button><h2 className="text-xl font-black">{row.client.firstName} {row.client.lastName}</h2><p className="text-xs text-slate-500">{row.client.clientNumber} · {row.saleNumber||'crédito activo'}</p><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-2xl bg-slate-50 p-3"><p className="text-[10px] text-slate-400">SALDO ACTUAL</p><p className="text-xl font-black">{money.format(Number(row.saldoActual))}</p></div><div className="rounded-2xl bg-emerald-50 p-3"><p className="text-[10px] text-emerald-700">SUGERIDO</p><p className="text-xl font-black text-emerald-700">{money.format(Number(row.suggestedInstallment||0))}</p></div></div><label className="mt-3 block text-xs font-black">Monto<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} className="mt-2 min-h-14 w-full rounded-2xl border bg-slate-50 px-4 text-2xl font-black"/></label><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>setMethod('CASH')} className={`min-h-12 rounded-2xl border text-xs font-black ${method==='CASH'?'bg-[var(--bitalis-primary)] text-white':''}`}>Efectivo</button><button onClick={()=>setMethod('BANK_TRANSFER')} className={`min-h-12 rounded-2xl border text-xs font-black ${method==='BANK_TRANSFER'?'bg-[var(--bitalis-primary)] text-white':''}`}>Transferencia</button></div><button disabled={!valid} onClick={onReview} className="mt-4 flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-[var(--bitalis-action)] font-black text-white disabled:opacity-40"><ShieldCheck className="h-5 w-5"/>REVISAR Y CONFIRMAR</button></section>}
