'use client';

import {FormEvent,useEffect,useMemo,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {Camera,CheckCircle2,ChevronRight,Crosshair,FileCheck2,Home,Loader2,MapPin,Phone,Search,ShieldCheck,UserRound} from 'lucide-react';
import AppShell,{useShellPermissions} from '@/components/phase15/AppShell';
import {apiClient,newIdempotencyKey} from '@/lib/phase15/apiClient';
import {haptic} from '@/lib/ux/haptics';

type Client={id:string;clientNumber:string;firstName:string;lastName:string;secondLastName?:string|null;phone?:string|null;status:string;riskLevel:string;customerType?:string|null;createdAt:string};
type Role='VENDEDORA'|'SUPERVISORA'|'ADMIN'|'COBRADOR'|'';
type Photos={facade:File|null;clientPhoto:File|null;contract:File|null};
const emptyPhotos:Photos={facade:null,clientPhoto:null,contract:null};

function readRole():Role{try{const raw=localStorage.getItem('bitalis_auth_user');const user=raw?JSON.parse(raw):null;return String(user?.role||'').toUpperCase() as Role;}catch{return '';}}
async function compressImage(file:File){if(!file.type.startsWith('image/'))return file;const bitmap=await createImageBitmap(file);const max=1280,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');if(!ctx)return file;ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',.72));bitmap.close();return blob?new File([blob],file.name.replace(/\.[^.]+$/,'.jpg'),{type:'image/jpeg'}):file;}
function preview(file:File|null){return file?URL.createObjectURL(file):'';}

export default function ClientsScreen({intakeOnly=false}:{intakeOnly?:boolean}){
 const router=useRouter(),permissions=useShellPermissions(),nameRef=useRef<HTMLInputElement|null>(null);
 const[role]=useState<Role>(()=>readRole()),[clients,setClients]=useState<Client[]>([]),[loading,setLoading]=useState(!intakeOnly),[saving,setSaving]=useState(false),[gpsLoading,setGpsLoading]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[query,setQuery]=useState('');
 const[name,setName]=useState(''),[phone,setPhone]=useState(''),[photos,setPhotos]=useState<Photos>(emptyPhotos),[position,setPosition]=useState<{lat:number;lng:number;accuracy?:number}|null>(null);
 const canCreate=permissions?.has('clients.create')===true,canView=permissions?.has('clients.view')===true,canFastIntake=canCreate&&['VENDEDORA','SUPERVISORA','ADMIN'].includes(role);

 useEffect(()=>{if(intakeOnly||new URLSearchParams(window.location.search).get('mode')==='intake')setTimeout(()=>nameRef.current?.focus(),80);},[intakeOnly]);
 const load=async()=>{if(!canView||intakeOnly){setLoading(false);return;}setLoading(true);setError('');try{const json:any=await apiClient('/api/clients?page=1&limit=100');setClients(json?.data||[]);}catch(e:any){setError(e.message);}finally{setLoading(false);}};
 useEffect(()=>{if(canView&&!intakeOnly)void load();else setLoading(false);},[canView,intakeOnly]);
 const filtered=useMemo(()=>clients.filter(c=>`${c.clientNumber} ${c.firstName} ${c.lastName} ${c.phone||''}`.toLowerCase().includes(query.toLowerCase())),[clients,query]);
 const pending=useMemo(()=>filtered.filter(c=>c.customerType==='PENDING_SUPERVISOR'||c.lastName==='PENDIENTE'),[filtered]);
 const completed=[!!position,!!photos.facade,!!photos.clientPhoto,!!photos.contract].filter(Boolean).length;
 const pick=async(key:keyof Photos,file?:File|null)=>{if(!file)return;haptic('tap');try{const compact=await compressImage(file);setPhotos(current=>({...current,[key]:compact}));haptic('success');}catch{setPhotos(current=>({...current,[key]:file}));}};
 const captureGps=()=>{haptic('tap');if(!navigator.geolocation){setError('Este dispositivo no permite capturar ubicación.');return;}setGpsLoading(true);setError('');navigator.geolocation.getCurrentPosition(result=>{setPosition({lat:result.coords.latitude,lng:result.coords.longitude,accuracy:result.coords.accuracy});setGpsLoading(false);haptic('success');},()=>{setError('No pudimos capturar la ubicación. Activa el permiso GPS e intenta nuevamente.');setGpsLoading(false);haptic('error');},{enableHighAccuracy:true,maximumAge:0,timeout:10000});};
 const submit=async(event:FormEvent)=>{event.preventDefault();haptic('tap');if(!canFastIntake){setError('No tienes permiso para registrar clientes.');return;}if(!name.trim()){setError('Ingresa el nombre del cliente.');nameRef.current?.focus();return;}if(!position){setError('Captura la ubicación del cliente antes de guardar.');return;}if(!photos.facade||!photos.clientPhoto||!photos.contract){setError('Debes tomar las tres fotografías: fachada, cliente y contrato.');return;}setSaving(true);setError('');setSuccess('');try{const form=new FormData();form.set('name',name.trim());form.set('phone',phone.trim());form.set('facade',photos.facade);form.set('clientPhoto',photos.clientPhoto);form.set('contract',photos.contract);form.set('idempotencyKey',newIdempotencyKey('field-client'));form.set('latitude',String(position.lat));form.set('longitude',String(position.lng));if(position.accuracy!=null)form.set('locationAccuracy',String(position.accuracy));const token=localStorage.getItem('bitalis_access_token');const response=await fetch('/api/clients/intake',{method:'POST',headers:token?{Authorization:`Bearer ${token}`}:{},body:form});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json?.error||'No pudimos enviar el registro.');setName('');setPhone('');setPhotos(emptyPhotos);setPosition(null);setSuccess(role==='SUPERVISORA'||role==='ADMIN'?`Cliente guardado · ${json?.client?.clientNumber||''}. Puedes completar el expediente cuando sea seguro.`:`Registro enviado a supervisión · ${json?.client?.clientNumber||''}`);haptic('success');setTimeout(()=>nameRef.current?.focus(),80);if(canView&&!intakeOnly)await load();}catch(e:any){setError(e.message);haptic('error');}finally{setSaving(false);}};
 const pageTitle=intakeOnly?'Alta rápida':role==='VENDEDORA'&&canFastIntake?'Alta rápida':role==='SUPERVISORA'?'Clientes y expedientes':'Clientes';
 const pageDescription=intakeOnly||role==='VENDEDORA'?'Captura y continúa. Solo lo indispensable en calle.':role==='SUPERVISORA'?'Puedes dar de alta en campo y completar el expediente después.':'Consulta expedientes y evidencias.';

 return <AppShell title={intakeOnly?'Alta rápida':'Clientes'}><main className="mx-auto max-w-6xl px-3 py-4 sm:px-4">
  <section className="rounded-[24px] bg-[#12224A] p-4 text-white"><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#C79A3B]">CRM en campo</p><h1 className="mt-1 text-xl font-black">{pageTitle}</h1><p className="mt-1 text-xs text-slate-300">{pageDescription}</p></section>
  {error&&<div role="alert" className="mt-3 rounded-2xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}
  {success&&<div className="mt-3 flex gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-bold text-emerald-700"><CheckCircle2 className="h-5 w-5 shrink-0"/>{success}</div>}
  {canFastIntake&&<form onSubmit={submit} className="mt-3 rounded-[24px] border border-slate-200 bg-white p-3 sm:p-4">
   <div className="mb-3 flex items-start justify-between gap-3"><div><p className="text-sm font-black text-[#12224A]">Alta rápida en campo</p><p className="mt-0.5 text-[11px] text-slate-500">Nombre + GPS + 3 fotos. Teléfono opcional.</p></div><span className="shrink-0 rounded-full bg-orange-50 px-2.5 py-1 text-[9px] font-black text-[#FF6A00]">{completed}/4 LISTO</span></div>
   <div className="mb-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#FF6A00] transition-all" style={{width:`${completed*25}%`}}/></div>
   <label className="block"><span className="text-xs font-black text-slate-500">Nombre del cliente *</span><input ref={nameRef} autoComplete="off" value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre completo" className="mt-2 min-h-14 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 text-base outline-none focus:border-[#FF6A00] focus:ring-4 focus:ring-orange-500/10"/></label>
   <label className="mt-3 block"><span className="text-xs font-black text-slate-500">Teléfono <span className="font-medium text-slate-400">(opcional)</span></span><input inputMode="tel" autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Número telefónico" className="mt-2 min-h-14 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 text-base outline-none focus:border-[#FF6A00] focus:ring-4 focus:ring-orange-500/10"/></label>
   <button type="button" onClick={captureGps} disabled={gpsLoading} className={`mt-3 flex min-h-14 w-full touch-manipulation items-center justify-center gap-2 rounded-2xl border px-3 text-center text-sm font-black transition active:scale-[.98] ${position?'border-emerald-200 bg-emerald-50 text-emerald-700':'border-blue-200 bg-blue-50 text-blue-700'}`}>{gpsLoading?<Loader2 className="h-5 w-5 animate-spin"/>:position?<MapPin className="h-5 w-5"/>:<Crosshair className="h-5 w-5"/>}{gpsLoading?'CAPTURANDO GPS…':position?`UBICACIÓN CAPTURADA${position.accuracy?` · ±${Math.round(position.accuracy)} m`:''}`:'CAPTURAR UBICACIÓN'}</button>
   <div className="mt-3 grid grid-cols-3 gap-2"><PhotoCapture title="Fachada" icon={<Home/>} file={photos.facade} onPick={file=>pick('facade',file)}/><PhotoCapture title="Cliente" icon={<UserRound/>} file={photos.clientPhoto} onPick={file=>pick('clientPhoto',file)}/><PhotoCapture title="Contrato" icon={<FileCheck2/>} file={photos.contract} onPick={file=>pick('contract',file)}/></div>
   <button disabled={saving||gpsLoading||completed<4} className="mt-4 flex min-h-16 w-full touch-manipulation items-center justify-center gap-2 rounded-2xl bg-[#FF6A00] text-base font-black text-white shadow-lg shadow-orange-500/20 transition active:scale-[.98] disabled:opacity-40">{saving?<Loader2 className="h-6 w-6 animate-spin"/>:<ShieldCheck className="h-5 w-5"/>}{saving?'ENVIANDO…':'GUARDAR Y CONTINUAR'}</button>
  </form>}
  {!intakeOnly&&canView&&<section className="mt-4"><div className="relative"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente" className="min-h-12 w-full rounded-2xl border border-slate-200 bg-white pl-11 pr-4 text-sm outline-none focus:ring-2 focus:ring-[#FF6A00]"/></div>{role==='SUPERVISORA'&&pending.length>0&&<div className="mt-3 rounded-2xl border border-amber-200 bg-amber-50 p-3 text-sm font-black text-amber-800">{pending.length} expediente{pending.length===1?'':'s'} pendiente{pending.length===1?'':'s'}</div>}{loading?<div className="flex justify-center p-10"><Loader2 className="h-6 w-6 animate-spin text-[#12224A]"/></div>:<div className="mt-3 space-y-2">{(role==='SUPERVISORA'?[...pending,...filtered.filter(c=>!pending.includes(c))]:filtered).map(client=><ClientCard key={client.id} client={client} role={role} router={router}/>)}</div>}</section>}
 </main></AppShell>;
}

function ClientCard({client,role,router}:{client:Client;role:Role;router:ReturnType<typeof useRouter>}){const pending=client.customerType==='PENDING_SUPERVISOR'||client.lastName==='PENDIENTE';const open=()=>{haptic('tap');router.push(role==='SUPERVISORA'||role==='ADMIN'?`/clients/${client.id}/complete`:`/clients/${client.id}`);};return <article className={`rounded-2xl border bg-white p-3 ${pending?'border-amber-200':'border-slate-200'}`}><div className="flex items-center gap-3"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${pending?'bg-amber-50 text-amber-700':'bg-slate-100 text-[#12224A]'}`}><UserRound className="h-5 w-5"/></div><div className="min-w-0 flex-1"><h2 className="truncate text-sm font-black text-[#12224A]">{client.firstName} {client.lastName==='PENDIENTE'?'':client.lastName}</h2><p className="mt-1 truncate text-[11px] text-slate-500">{client.clientNumber}{client.phone?` · ${client.phone}`:''}</p></div><button onClick={open} className={`flex min-h-11 items-center justify-center gap-1 rounded-xl ${role==='SUPERVISORA'||role==='ADMIN'?'bg-[#12224A] px-3 text-xs font-black text-white':'w-11 bg-slate-100 text-[#12224A]'}`}>{role==='SUPERVISORA'||role==='ADMIN'?'Editar':null}<ChevronRight className="h-4 w-4"/></button></div>{role==='COBRADOR'&&<div className="mt-2 flex gap-2"><button onClick={open} className="flex min-h-11 flex-1 items-center justify-center gap-2 rounded-xl bg-[#FF6A00] text-xs font-black text-white"><Camera className="h-4 w-4"/>Ver fotos</button>{client.phone&&<a href={`tel:${client.phone}`} className="flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 text-xs font-black text-[#12224A]"><Phone className="h-4 w-4"/>Llamar</a>}</div>}</article>}

function PhotoCapture({title,icon,file,onPick}:{title:string;icon:React.ReactNode;file:File|null;onPick:(file:File|null)=>void}){const src=useMemo(()=>preview(file),[file]);useEffect(()=>()=>{if(src)URL.revokeObjectURL(src);},[src]);return <label className={`block cursor-pointer rounded-2xl border p-2 text-center transition active:scale-[.98] ${file?'border-emerald-200 bg-emerald-50':'border-dashed border-slate-300 bg-slate-50'}`}>{src?<img src={src} alt={title} className="h-24 w-full rounded-xl object-cover sm:h-28"/>:<div className="flex h-24 flex-col items-center justify-center text-slate-400 sm:h-28"><div className="mb-1 h-5 w-5">{icon}</div><Camera className="h-5 w-5"/></div>}<p className={`mt-2 truncate text-[10px] font-black sm:text-[11px] ${file?'text-emerald-700':'text-[#12224A]'}`}>{file?'✓ LISTA':title}</p><input type="file" accept="image/*" capture="environment" className="hidden" onChange={e=>onPick(e.target.files?.[0]||null)}/></label>}
