'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {Camera,CheckCircle2,ChevronRight,Crosshair,FileCheck2,Home,Loader2,MapPin,Phone,Search,ShieldCheck,UserRound} from 'lucide-react';
import AppShell from '@/components/phase15/AppShell';
import {apiClient,newIdempotencyKey} from '@/lib/phase15/apiClient';

type Client={id:string;clientNumber:string;firstName:string;lastName:string;secondLastName?:string|null;phone?:string|null;status:string;riskLevel:string;customerType?:string|null;createdAt:string};
type Role='VENDEDORA'|'SUPERVISORA'|'ADMIN'|'COBRADOR'|'';
type Photos={facade:File|null;clientPhoto:File|null;contract:File|null};
const emptyPhotos:Photos={facade:null,clientPhoto:null,contract:null};

async function compressImage(file:File){if(!file.type.startsWith('image/'))return file;const bitmap=await createImageBitmap(file);const max=1280,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');if(!ctx)return file;ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,'image/jpeg',.72));bitmap.close();return blob?new File([blob],file.name.replace(/\.[^.]+$/,'.jpg'),{type:'image/jpeg'}):file;}
function preview(file:File|null){return file?URL.createObjectURL(file):'';}

export default function ClientsPage(){
 const router=useRouter();const[role,setRole]=useState<Role>(''),[clients,setClients]=useState<Client[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[gpsLoading,setGpsLoading]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[query,setQuery]=useState('');const[name,setName]=useState(''),[phone,setPhone]=useState(''),[photos,setPhotos]=useState<Photos>(emptyPhotos),[position,setPosition]=useState<{lat:number;lng:number;accuracy?:number}|null>(null);
 useEffect(()=>{try{const raw=localStorage.getItem('bitalis_auth_user');const u=raw?JSON.parse(raw):null;setRole(String(u?.role||'').toUpperCase() as Role);}catch{}},[]);
 const load=async()=>{setLoading(true);setError('');try{const j:any=await apiClient('/api/clients?page=1&limit=100');setClients(j?.data||[]);}catch(e:any){setError(e.message);}finally{setLoading(false);}};useEffect(()=>{if(role)load();},[role]);
 const filtered=useMemo(()=>clients.filter(c=>`${c.clientNumber} ${c.firstName} ${c.lastName} ${c.phone||''}`.toLowerCase().includes(query.toLowerCase())),[clients,query]);const pending=useMemo(()=>filtered.filter(c=>c.customerType==='PENDING_SUPERVISOR'||c.lastName==='PENDIENTE'),[filtered]);
 const pick=async(key:keyof Photos,file?:File|null)=>{if(!file)return;try{const compact=await compressImage(file);setPhotos(p=>({...p,[key]:compact}));}catch{setPhotos(p=>({...p,[key]:file}));}};
 const captureGps=()=>{if(!navigator.geolocation){setError('Este dispositivo no permite capturar ubicación.');return;}setGpsLoading(true);setError('');navigator.geolocation.getCurrentPosition(p=>{setPosition({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy});setGpsLoading(false);},()=>{setError('No pudimos capturar la ubicación. Activa el permiso GPS e intenta nuevamente.');setGpsLoading(false);},{enableHighAccuracy:true,maximumAge:0,timeout:10000});};
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!name.trim()){setError('Ingresa el nombre del cliente.');return;}if(!position){setError('Captura la ubicación del cliente antes de guardar.');return;}if(!photos.facade||!photos.clientPhoto||!photos.contract){setError('Debes tomar las tres fotografías: fachada, cliente y contrato.');return;}setSaving(true);setError('');setSuccess('');try{const fd=new FormData();fd.set('name',name.trim());fd.set('phone',phone.trim());fd.set('facade',photos.facade);fd.set('clientPhoto',photos.clientPhoto);fd.set('contract',photos.contract);fd.set('idempotencyKey',newIdempotencyKey('seller-client'));fd.set('latitude',String(position.lat));fd.set('longitude',String(position.lng));if(position.accuracy!=null)fd.set('locationAccuracy',String(position.accuracy));const token=localStorage.getItem('bitalis_access_token');const res=await fetch('/api/clients/intake',{method:'POST',headers:token?{Authorization:`Bearer ${token}`}:{},body:fd});const j=await res.json().catch(()=>({}));if(!res.ok)throw new Error(j?.error||'No pudimos enviar el registro.');setName('');setPhone('');setPhotos(emptyPhotos);setPosition(null);setSuccess(`Registro enviado a supervisión · ${j?.client?.clientNumber||''}`);await load();}catch(e:any){setError(e.message);}finally{setSaving(false);}};
 return <AppShell title="Clientes"><main className="mx-auto max-w-6xl px-4 py-4"><section className="rounded-[24px] bg-[#12224A] p-4 text-white"><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#C79A3B]">CRM en ruta</p><h1 className="mt-1 text-xl font-black">{role==='VENDEDORA'?'Alta rápida':role==='SUPERVISORA'?'Expedientes por completar':'Clientes'}</h1><p className="mt-1 text-xs text-slate-300">{role==='VENDEDORA'?'Captura y continúa. Solo lo indispensable en calle.':role==='SUPERVISORA'?'Revisa evidencias y completa o corrige el expediente.':'Consulta expedientes y evidencias.'}</p></section>{error&&<div role="alert" className="mt-3 rounded-2xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}{success&&<div className="mt-3 flex gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-bold text-emerald-700"><CheckCircle2 className="h-5 w-5"/>{success}</div>}
 {role==='VENDEDORA'&&<form onSubmit={submit} className="mt-3 rounded-[24px] border border-slate-200 bg-white p-4"><label className="block"><span className="text-xs font-black text-slate-500">Nombre del cliente *</span><input autoFocus autoComplete="off" value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre completo" className="mt-2 min-h-12 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 text-base outline-none focus:ring-2 focus:ring-[#FF6A00]"/></label><label className="mt-3 block"><span className="text-xs font-black text-slate-500">Teléfono <span className="font-medium text-slate-400">(opcional)</span></span><input inputMode="tel" autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Número telefónico" className="mt-2 min-h-12 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 text-base outline-none focus:ring-2 focus:ring-[#FF6A00]"/></label><button type="button" onClick={captureGps} disabled={gpsLoading} className={`mt-3 flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl border text-sm font-black ${position?'border-emerald-200 bg-emerald-50 text-emerald-700':'border-blue-200 bg-blue-50 text-blue-700'}`}>{gpsLoading?<Loader2 className="h-5 w-5 animate-spin"/>:position?<MapPin className="h-5 w-5"/>:<Crosshair className="h-5 w-5"/>}{gpsLoading?'CAPTURANDO GPS…':position?`UBICACIÓN CAPTURADA${position.accuracy?` · ±${Math.round(position.accuracy)} m`:''}`:'CAPTURAR UBICACIÓN DEL CLIENTE'}</button><div className="mt-3 grid grid-cols-3 gap-2"><PhotoCapture title="Fachada" icon={<Home/>} file={photos.facade} capture="environment" onPick={f=>pick('facade',f)}/><PhotoCapture title="Cliente" icon={<UserRound/>} file={photos.clientPhoto} capture="environment" onPick={f=>pick('clientPhoto',f)}/><PhotoCapture title="Contrato" icon={<FileCheck2/>} file={photos.contract} capture="environment" onPick={f=>pick('contract',f)}/></div><button disabled={saving||gpsLoading} className="mt-4 flex min-h-16 w-full items-center justify-center gap-2 rounded-2xl bg-[#FF6A00] text-base font-black text-white shadow-lg shadow-orange-500/20 disabled:opacity-50">{saving?<Loader2 className="h-6 w-6 animate-spin"/>:<ShieldCheck className="h-5 w-5"/>}{saving?'ENVIANDO…':'GUARDAR Y CONTINUAR'}</button></form>}
 <section className="mt-4"><div className="relative"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente" className="w-full rounded-2xl border border-slate-200 bg-white py-3 pl-11 pr-4 text-sm outline-none focus:ring-2 focus:ring-[#FF6A00]"/></div>{role==='SUPERVISORA'&&pending.length>0&&<div className="mt-3 rounded-2xl border border-amber-200 bg-amber-50 p-3 text-sm font-black text-amber-800">{pending.length} expediente{pending.length===1?'':'s'} pendiente{pending.length===1?'':'s'}</div>}{loading?<div className="flex justify-center p-10"><Loader2 className="h-6 w-6 animate-spin text-[#12224A]"/></div>:<div className="mt-3 space-y-2">{(role==='SUPERVISORA'?[...pending,...filtered.filter(c=>!pending.includes(c))]:filtered).map(c=>{const isPending=c.customerType==='PENDING_SUPERVISOR'||c.lastName==='PENDIENTE';return <article key={c.id} className={`rounded-2xl border bg-white p-3 ${isPending?'border-amber-200':'border-slate-200'}`}><div className="flex items-center gap-3"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${isPending?'bg-amber-50 text-amber-700':'bg-slate-100 text-[#12224A]'}`}><UserRound className="h-5 w-5"/></div><div className="min-w-0 flex-1"><h2 className="truncate text-sm font-black text-[#12224A]">{c.firstName} {c.lastName==='PENDIENTE'?'':c.lastName}</h2><p className="mt-1 text-[11px] text-slate-500">{c.clientNumber}{c.phone?` · ${c.phone}`:''}</p></div>{role==='SUPERVISORA'||role==='ADMIN'?<button onClick={()=>router.push(`/clients/${c.id}/complete`)} className="flex min-h-11 items-center gap-1 rounded-xl bg-[#12224A] px-3 text-xs font-black text-white">Editar<ChevronRight className="h-4 w-4"/></button>:<button onClick={()=>router.push(`/clients/${c.id}`)} className="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-100 text-[#12224A]"><ChevronRight className="h-4 w-4"/></button>}</div>{role==='COBRADOR'&&<div className="mt-2 flex gap-2"><button onClick={()=>router.push(`/clients/${c.id}`)} className="flex min-h-11 flex-1 items-center justify-center gap-2 rounded-xl bg-[#FF6A00] text-xs font-black text-white"><Camera className="h-4 w-4"/>Ver fotos</button>{c.phone&&<a href={`tel:${c.phone}`} className="flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 text-xs font-black text-[#12224A]"><Phone className="h-4 w-4"/>Llamar</a>}</div>}</article>})}</div>}</section></main></AppShell>}
function PhotoCapture({title,icon,file,capture,onPick}:{title:string;icon:React.ReactNode;file:File|null;capture:'user'|'environment';onPick:(f:File|null)=>void}){const src=useMemo(()=>preview(file),[file]);useEffect(()=>()=>{if(src)URL.revokeObjectURL(src);},[src]);return <label className="block cursor-pointer rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-2 text-center active:scale-[.98]">{src?<img src={src} alt={title} className="h-28 w-full rounded-xl object-cover"/>:<div className="flex h-28 flex-col items-center justify-center text-slate-400"><div className="mb-1 h-5 w-5">{icon}</div><Camera className="h-5 w-5"/></div>}<p className="mt-2 text-[11px] font-black text-[#12224A]">{file?'Cambiar':title}</p><input type="file" accept="image/*" capture={capture} className="hidden" onChange={e=>onPick(e.target.files?.[0]||null)}/></label>}
