'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import {
  ArrowLeft, Banknote, CalendarClock, CheckCircle2, Compass, Crosshair,
  Loader2, MapPin, Navigation, Phone, Printer, RefreshCw, Route, ShieldCheck,
  SkipForward, WalletCards, X, XCircle, ClipboardCheck, CloudOff, Cloud,
  LockKeyhole, RotateCcw
} from 'lucide-react';
import BitalisLogo from '@/components/BitalisLogo';

type Client={id:string;clientNumber:string;firstName:string;lastName:string;secondLastName?:string|null;phone:string;latitude?:number|null;longitude?:number|null;riskLevel?:string};
type Credit={id:string;saleId:string;saleNumber?:string|null;clientId:string;principalAmount:number;saldoActual:number;suggestedInstallment:number;paymentFrequency:string;proximaVisita?:string|null;status:string;client:Client};
type Position={lat:number;lng:number;accuracy?:number};
type AuthUser={id:string;email:string;firstName?:string;lastName?:string;role:string};
type CashSession={id:string;openingFund:number|string;currentCash:number|string;expectedCash:number|string;status:string;openedAt?:string};
type Receipt={paymentId:string;clientName:string;clientNumber:string;creditId:string;amount:number;method:string;previousBalance:number;newBalance:number;createdAt:string};
type RouteStats={visited:number;paid:number;noPay:number;rescheduled:number;skipped:number;totalCollected:number};
type SavedProgress={date:string;completed:string[];selectedId:string;stats:RouteStats;updatedAt:string;planIds?:string[];planFrozen?:boolean};

const EMPTY_STATS:RouteStats={visited:0,paid:0,noPay:0,rescheduled:0,skipped:0,totalCollected:0};
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',minimumFractionDigits:2});
const todayMx=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Mexico_City',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const toRad=(v:number)=>(v*Math.PI)/180;
function distanceMeters(a:Position,b:{lat:number;lng:number}){const R=6371000,dLat=toRad(b.lat-a.lat),dLng=toRad(b.lng-a.lng);const x=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLng/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function bearingDegrees(a:Position,b:{lat:number;lng:number}){const lat1=toRad(a.lat),lat2=toRad(b.lat),dLng=toRad(b.lng-a.lng);const y=Math.sin(dLng)*Math.cos(lat2),x=Math.cos(lat1)*Math.sin(lat2)-Math.sin(lat1)*Math.cos(lat2)*Math.cos(dLng);return(Math.atan2(y,x)*180/Math.PI+360)%360;}
function directionLabel(b:number){return['N','NE','E','SE','S','SO','O','NO'][Math.round(b/45)%8];}

export default function CollectorRoutePage(){
  const router=useRouter();
  const [user,setUser]=useState<AuthUser|null>(null),[credits,setCredits]=useState<Credit[]>([]),[position,setPosition]=useState<Position|null>(null);
  const [selectedId,setSelectedId]=useState(''),[tracking,setTracking]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
  const [completed,setCompleted]=useState<string[]>([]),[stats,setStats]=useState<RouteStats>(EMPTY_STATS),[restored,setRestored]=useState(false),[online,setOnline]=useState(true);
  const [notes,setNotes]=useState(''),[noPayReason,setNoPayReason]=useState('NO_TENIA_DINERO'),[rescheduleDate,setRescheduleDate]=useState('');
  const [payOpen,setPayOpen]=useState(false),[paymentAmount,setPaymentAmount]=useState(''),[paymentMethod,setPaymentMethod]=useState<'CASH'|'BANK_TRANSFER'>('CASH');
  const [cashSession,setCashSession]=useState<CashSession|null>(null),[openingFund,setOpeningFund]=useState('0'),[openingCash,setOpeningCash]=useState(false),[receipt,setReceipt]=useState<Receipt|null>(null);
  const [planIds,setPlanIds]=useState<string[]>([]),[planFrozen,setPlanFrozen]=useState(false),[planning,setPlanning]=useState(false);

  const token=()=>localStorage.getItem('bitalis_access_token');
  const routeKey=(uid:string)=>`bitalis_route_progress_${uid}_${todayMx()}`;
  const deviceId=()=>{let id=localStorage.getItem('bitalis_device_id');if(!id){id=`DEV-${crypto.randomUUID()}`;localStorage.setItem('bitalis_device_id',id);}return id;};
  const persist=(uid=user?.id,done=completed,current=selectedId,currentStats=stats,ids=planIds,frozen=planFrozen)=>{if(!uid)return;const data:SavedProgress={date:todayMx(),completed:done,selectedId:current,stats:currentStats,updatedAt:new Date().toISOString(),planIds:ids,planFrozen:frozen};localStorage.setItem(routeKey(uid),JSON.stringify(data));};

  useEffect(()=>{setOnline(navigator.onLine);const on=()=>setOnline(true),off=()=>setOnline(false);window.addEventListener('online',on);window.addEventListener('offline',off);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off);};},[]);
  useEffect(()=>{if(restored&&user?.id)persist();},[completed,selectedId,stats,planIds,planFrozen,restored,user?.id]);

  const loadCash=async(u?:AuthUser|null)=>{const current=u||user;if(!current?.id)return;try{const res=await fetch(`/api/cash-sessions/current?userId=${encodeURIComponent(current.id)}`,{cache:'no-store'});const json=await res.json().catch(()=>({}));if(res.ok)setCashSession(json?.data||null);}catch{}};

  const restoreProgress=async(currentUser:AuthUser,auth:string)=>{
    let local:SavedProgress|null=null;try{const raw=localStorage.getItem(routeKey(currentUser.id));if(raw)local=JSON.parse(raw);}catch{}
    let server:any=null;if(navigator.onLine){try{const res=await fetch(`/api/collections/route-progress?date=${todayMx()}`,{headers:{Authorization:`Bearer ${auth}`},cache:'no-store'});const json=await res.json().catch(()=>({}));if(res.ok)server=json?.data;}catch{}}
    const serverDone=Array.isArray(server?.completedCreditIds)?server.completedCreditIds:[];const merged=Array.from(new Set([...(local?.completed||[]),...serverDone]));
    setCompleted(merged);setSelectedId(local?.selectedId||'');setStats(server?.stats?{...EMPTY_STATS,...server.stats,skipped:local?.stats?.skipped||0}:local?.stats||EMPTY_STATS);
    setPlanIds(Array.isArray(local?.planIds)?local!.planIds!:[]);setPlanFrozen(Boolean(local?.planFrozen&&local?.planIds?.length));setRestored(true);
    if(merged.length>0||local?.planFrozen)setNotice(local?.planFrozen?'Ruta del día recuperada con orden fijo.':`Ruta recuperada: ${merged.length} crédito(s) ya atendidos hoy.`);
  };

  const load=async()=>{const auth=token(),raw=localStorage.getItem('bitalis_auth_user');if(!auth||!raw){router.replace('/');return;}let parsed:AuthUser;try{parsed=JSON.parse(raw);setUser(parsed);}catch{router.replace('/');return;}setLoading(true);setError('');try{const res=await fetch('/api/collections/portfolio',{headers:{Authorization:`Bearer ${auth}`},cache:'no-store'});const json=await res.json().catch(()=>({}));if(res.status===401){router.replace('/');return;}if(!res.ok)throw new Error(json?.error||'No fue posible cargar la cartera.');setCredits((Array.isArray(json?.data)?json.data:[]).filter((c:Credit)=>c.client?.latitude!=null&&c.client?.longitude!=null));await Promise.all([loadCash(parsed),restoreProgress(parsed,auth)]);}catch(e:any){setError(e?.message||'No fue posible cargar la cartera con GPS.');}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  useEffect(()=>{if(!tracking||!navigator.geolocation)return;const id=navigator.geolocation.watchPosition(p=>setPosition({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy}),e=>setError(e.message||'No fue posible obtener tu ubicación.'),{enableHighAccuracy:true,maximumAge:5000,timeout:15000});return()=>navigator.geolocation.clearWatch(id);},[tracking]);

  const pending=useMemo(()=>credits.filter(c=>!completed.includes(c.id)),[credits,completed]);
  const ordered=useMemo(()=>{if(planFrozen&&planIds.length){const map=new Map(pending.map(c=>[c.id,c]));const fixed=planIds.map(id=>map.get(id)).filter(Boolean) as Credit[];const extras=pending.filter(c=>!planIds.includes(c.id));return[...fixed,...extras];}if(!position)return pending;return[...pending].sort((a,b)=>distanceMeters(position,{lat:Number(a.client.latitude),lng:Number(a.client.longitude)})-distanceMeters(position,{lat:Number(b.client.latitude),lng:Number(b.client.longitude)}));},[pending,position,planFrozen,planIds]);
  const selected=ordered.find(c=>c.id===selectedId)||ordered[0]||null,client=selected?.client||null;
  const distance=selected&&position?distanceMeters(position,{lat:Number(client?.latitude),lng:Number(client?.longitude)}):null;
  const bearing=selected&&position?bearingDegrees(position,{lat:Number(client?.latitude),lng:Number(client?.longitude)}):null;
  const arrived=distance!=null&&distance<=80;
  useEffect(()=>{if(selected)setPaymentAmount(String(Math.min(selected.suggestedInstallment||selected.saldoActual,selected.saldoActual)));},[selected?.id]);

  const buildPlan=async(pos:Position,force=false)=>{if(planFrozen&&!force)return;const auth=token();if(!auth||!online)return;setPlanning(true);setError('');try{const res=await fetch(`/api/collections/route-plan?lat=${encodeURIComponent(pos.lat)}&lng=${encodeURIComponent(pos.lng)}&date=${todayMx()}`,{headers:{Authorization:`Bearer ${auth}`},cache:'no-store'});const json=await res.json().catch(()=>({}));if(!res.ok)throw new Error(json?.error||'No fue posible optimizar la ruta.');const ids=Array.isArray(json?.data?.orderedCreditIds)?json.data.orderedCreditIds:Array.isArray(json?.orderedCreditIds)?json.orderedCreditIds:[];if(!ids.length)throw new Error('El optimizador no devolvió destinos.');setPlanIds(ids);setPlanFrozen(true);setSelectedId(ids.find((id:string)=>!completed.includes(id))||'');persist(user?.id,completed,ids[0]||'',stats,ids,true);setNotice(force?'Ruta recalculada y fijada nuevamente.':'Ruta optimizada y fijada para la jornada.');}catch(e:any){setError(e?.message||'No fue posible fijar la ruta.');}finally{setPlanning(false);}};
  const start=()=>{if(!navigator.geolocation){setError('Este dispositivo no permite geolocalización.');return;}setTracking(true);navigator.geolocation.getCurrentPosition(async p=>{const pos={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};setPosition(pos);if(!planFrozen)await buildPlan(pos);},e=>setError(e.message||'Activa el permiso de ubicación para navegar.'),{enableHighAccuracy:true,timeout:15000});};
  const recalc=async()=>{if(!position){setError('Activa GPS antes de recalcular la ruta.');return;}await buildPlan(position,true);};

  const openCashSession=async()=>{if(!position){setError('Activa el GPS antes de abrir caja.');return;}const auth=token();if(!auth)return router.replace('/');const fund=Number(openingFund);if(!Number.isFinite(fund)||fund<0){setError('El fondo inicial no es válido.');return;}setOpeningCash(true);setError('');try{const res=await fetch('/api/cash-sessions/open',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${auth}`},body:JSON.stringify({openingFund:fund,latitude:position.lat,longitude:position.lng,deviceId:deviceId(),openedClientAt:new Date().toISOString(),idempotencyKey:`cash-open-${user?.id}-${todayMx()}`})});const json=await res.json().catch(()=>({}));if(!res.ok)throw new Error(json?.error||'No fue posible abrir caja.');setCashSession(json?.data?.session||json?.data||null);setNotice('Caja abierta correctamente.');}catch(e:any){setError(e?.message||'No fue posible abrir caja.');}finally{setOpeningCash(false);}};
  const next=(message:string)=>{if(!selected)return;const done=Array.from(new Set([...completed,selected.id]));setCompleted(done);setSelectedId('');setNotice(message);setNotes('');setRescheduleDate('');setPayOpen(false);setPaymentAmount('');persist(user?.id,done,'',stats,planIds,planFrozen);window.setTimeout(()=>setNotice(''),3500);};

  const registerVisit=async(result:'SUCCESS'|'NOT_HOME'|'REFUSED'|'RESCHEDULED',reason?:string,doNext=true)=>{if(!selected||!client||!position)throw new Error('Activa el GPS antes de registrar la visita.');if(!online)throw new Error('Sin conexión. La ruta se conserva, pero el resultado debe sincronizarse con internet.');const auth=token();if(!auth)throw new Error('Sesión no disponible.');const extra=result==='RESCHEDULED'&&rescheduleDate?`Reagendado para ${rescheduleDate}. ${notes}`.trim():notes;const res=await fetch('/api/collections/visits',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${auth}`},body:JSON.stringify({clientId:client.id,creditId:selected.id,visitType:'COLLECTION_VISIT',result,noPaymentReason:reason,gpsLatitude:position.lat,gpsLongitude:position.lng,accuracy:position.accuracy,notes:extra||undefined,clientCapturedAt:new Date().toISOString(),idempotencyKey:`route-visit-${selected.id}-${Date.now()}`})});const json=await res.json().catch(()=>({}));if(!res.ok)throw new Error(json?.error||'No fue posible registrar la visita.');if(doNext){const ns={...stats,visited:stats.visited+1,noPay:result==='RESCHEDULED'?stats.noPay:stats.noPay+1,rescheduled:result==='RESCHEDULED'?stats.rescheduled+1:stats.rescheduled};setStats(ns);next(result==='RESCHEDULED'?'Cliente reagendado. Siguiente destino…':'Visita registrada. Siguiente destino…');}};
  const saveVisit=async(result:'NOT_HOME'|'REFUSED'|'RESCHEDULED',reason?:string)=>{setSaving(true);setError('');try{await registerVisit(result,reason,true);}catch(e:any){setError(e?.message||'No fue posible registrar la visita.');}finally{setSaving(false);}};

  const registerPayment=async()=>{if(!selected||!client||!position){setError('Activa el GPS antes de cobrar.');return;}if(!online){setError('Necesitas conexión para confirmar un abono y evitar cobros duplicados.');return;}const amount=Number(paymentAmount);if(!Number.isFinite(amount)||amount<=0){setError('Captura un importe válido.');return;}if(amount>selected.saldoActual){setError('El abono no puede ser mayor al saldo actual.');return;}if(paymentMethod==='CASH'&&!cashSession){setError('Abre la caja del cobrador antes de recibir efectivo.');return;}const auth=token();if(!auth)return router.replace('/');setSaving(true);setError('');try{const capturedAt=new Date().toISOString();const res=await fetch('/api/payments',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${auth}`},body:JSON.stringify({creditId:selected.id,amount,paymentMethod,cashSessionId:paymentMethod==='CASH'?cashSession?.id:undefined,clientCapturedAt:capturedAt,gpsLatitude:position.lat,gpsLongitude:position.lng,notes:notes||undefined,idempotencyKey:`route-payment-${selected.id}-${Date.now()}`})});const json=await res.json().catch(()=>({}));if(!res.ok)throw new Error(json?.error||'No fue posible registrar el abono.');const payment=json?.payment||json?.data||json;await registerVisit('SUCCESS',undefined,false);const newBalance=Math.max(0,selected.saldoActual-amount);setReceipt({paymentId:payment?.id||'PAGO-REGISTRADO',clientName:`${client.firstName} ${client.lastName} ${client.secondLastName||''}`.trim(),clientNumber:client.clientNumber,creditId:selected.id,amount,method:paymentMethod,previousBalance:selected.saldoActual,newBalance,createdAt:capturedAt});const ns={...stats,visited:stats.visited+1,paid:stats.paid+1,totalCollected:stats.totalCollected+amount};setStats(ns);if(paymentMethod==='CASH')await loadCash();next(`Abono ${money.format(amount)} registrado. Siguiente destino…`);await load();}catch(e:any){setError(e?.message||'No fue posible registrar el abono.');}finally{setSaving(false);}};
  const skip=()=>{if(!selected)return;const ns={...stats,skipped:stats.skipped+1};setStats(ns);next('Cliente omitido temporalmente. Siguiente destino…');};

  return <div className="min-h-screen bg-slate-950 text-slate-100 print:bg-white print:text-black">
    <header className="sticky top-0 z-30 border-b border-white/5 bg-slate-950/90 backdrop-blur-xl print:hidden"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3"><div className="flex items-center gap-3"><button onClick={()=>router.push('/dashboard')} className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-800 bg-slate-900"><ArrowLeft className="h-4 w-4"/></button><BitalisLogo size="md" variant="dark"/></div><div className="flex gap-2"><span className={`flex items-center gap-1 rounded-xl border px-3 py-2 text-[10px] font-bold ${online?'border-emerald-400/20 text-emerald-300':'border-amber-400/20 text-amber-200'}`}>{online?<Cloud className="h-3.5 w-3.5"/>:<CloudOff className="h-3.5 w-3.5"/>}{online?'En línea':'Sin señal'}</span><button onClick={()=>router.push('/route/close')} className="rounded-xl border border-slate-800 bg-slate-900 px-3 text-[10px] font-black text-slate-300">Cerrar jornada</button><button onClick={load} className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-800 bg-slate-900"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div></div></header>

    <main className="mx-auto max-w-6xl px-4 py-5 print:hidden">
      <section className="rounded-[28px] border border-emerald-400/10 bg-gradient-to-br from-slate-900 to-emerald-950/20 p-5"><div className="flex flex-wrap items-center gap-2"><div className="inline-flex items-center gap-2 rounded-full border border-emerald-400/15 bg-emerald-400/5 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.16em] text-emerald-300"><Route className="h-3.5 w-3.5"/> Ruta de cobranza</div>{planFrozen&&<div className="inline-flex items-center gap-1 rounded-full border border-blue-400/15 bg-blue-500/5 px-3 py-1.5 text-[10px] font-black text-blue-200"><LockKeyhole className="h-3.5 w-3.5"/>Orden fijo</div>}</div><h1 className="mt-4 text-2xl font-black text-white">Modo cobrador</h1><p className="mt-2 text-sm text-slate-400">El orden se optimiza al iniciar y queda congelado para evitar cambios mientras conduces.</p><div className="mt-4 grid grid-cols-3 gap-2 text-[11px] sm:grid-cols-6"><span className="rounded-lg bg-slate-950 px-3 py-2 text-slate-400">Pendientes <b className="block text-white">{ordered.length}</b></span><span className="rounded-lg bg-emerald-500/10 px-3 py-2 text-emerald-300">Visitados <b className="block">{stats.visited}</b></span><span className="rounded-lg bg-emerald-500/10 px-3 py-2 text-emerald-300">Pagaron <b className="block">{stats.paid}</b></span><span className="rounded-lg bg-orange-500/10 px-3 py-2 text-orange-200">No pagaron <b className="block">{stats.noPay}</b></span><span className="rounded-lg bg-slate-950 px-3 py-2 text-slate-400">Reagendados <b className="block text-white">{stats.rescheduled}</b></span><span className="rounded-lg bg-slate-950 px-3 py-2 text-slate-400">Cobrado <b className="block text-emerald-300">{money.format(stats.totalCollected)}</b></span></div></section>
      {error&&<div className="mt-4 rounded-2xl border border-red-400/20 bg-red-500/10 p-4 text-sm text-red-200">{error}</div>}{notice&&<div className="mt-4 rounded-2xl border border-emerald-400/20 bg-emerald-500/10 p-4 text-sm font-bold text-emerald-200">{notice}</div>}
      <section className="mt-4 rounded-[24px] border border-white/5 bg-slate-900/70 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.14em] text-slate-500">Caja del cobrador</p><p className="mt-1 text-sm font-black text-white">{cashSession?`Caja ${cashSession.status}`:'Sin caja abierta'}</p></div>{cashSession?<div className="flex gap-2"><div className="rounded-xl bg-slate-950 px-3 py-2 text-xs text-slate-400">Fondo <b className="ml-1 text-white">{money.format(Number(cashSession.openingFund||0))}</b></div><div className="rounded-xl bg-emerald-500/10 px-3 py-2 text-xs text-emerald-300">Esperado <b className="ml-1">{money.format(Number(cashSession.expectedCash||0))}</b></div></div>:<div className="flex gap-2"><input inputMode="decimal" value={openingFund} onChange={e=>setOpeningFund(e.target.value)} className="w-28 rounded-xl border border-slate-800 bg-slate-950 px-3 py-2 text-sm text-white"/><button onClick={openCashSession} disabled={openingCash||!position||!online} className="flex items-center gap-2 rounded-xl bg-emerald-500 px-4 py-2 text-xs font-black text-slate-950 disabled:opacity-40">{openingCash?<Loader2 className="h-4 w-4 animate-spin"/>:<Banknote className="h-4 w-4"/>}Abrir caja</button></div>}</div></section>

      <section className="mt-4 grid gap-4 lg:grid-cols-[1fr_.72fr]"><article className="rounded-[26px] border border-white/5 bg-slate-900/70 p-5">
        {!tracking?<button onClick={start} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-emerald-500 px-4 py-4 text-sm font-black text-slate-950"><Navigation className="h-5 w-5"/>Iniciar y optimizar ruta</button>:<div className="flex items-center justify-between gap-2 rounded-2xl border border-emerald-400/15 bg-emerald-400/5 p-3 text-xs font-bold text-emerald-300"><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4"/>GPS activo {position?.accuracy?`· precisión ${Math.round(position.accuracy)} m`:''}</span><button onClick={recalc} disabled={planning||!online} className="flex items-center gap-1 rounded-lg border border-blue-400/20 px-2 py-1.5 text-[10px] text-blue-200 disabled:opacity-40">{planning?<Loader2 className="h-3 w-3 animate-spin"/>:<RotateCcw className="h-3 w-3"/>}Recalcular</button></div>}
        <div className="mt-5 rounded-[24px] border border-slate-800 bg-slate-950 p-5 text-center"><div className="mx-auto flex h-24 w-24 items-center justify-center rounded-full border border-emerald-400/20 bg-emerald-400/5"><Compass className="h-12 w-12 text-emerald-400" style={{transform:`rotate(${bearing||0}deg)`}}/></div><p className="mt-4 text-[10px] font-black uppercase tracking-[.16em] text-slate-500">Siguiente destino</p><h2 className="mt-1 text-xl font-black text-white">{client?`${client.firstName} ${client.lastName}`:'Ruta completada'}</h2><p className="mt-1 text-xs text-slate-500">{client?.clientNumber||'No quedan créditos con GPS'}</p>{selected&&<div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl bg-slate-900 p-3"><p className="text-[9px] uppercase text-slate-600">Saldo</p><p className="mt-1 text-lg font-black text-white">{money.format(selected.saldoActual)}</p></div><div className="rounded-xl bg-slate-900 p-3"><p className="text-[9px] uppercase text-slate-600">Abono sugerido</p><p className="mt-1 text-lg font-black text-emerald-300">{money.format(selected.suggestedInstallment)}</p></div></div>}{distance!=null&&<p className="mt-4 text-3xl font-black text-emerald-300">{distance<1000?`${Math.round(distance)} m`:`${(distance/1000).toFixed(1)} km`}</p>}{bearing!=null&&<p className="mt-1 text-xs text-slate-500">Dirección aproximada: {directionLabel(bearing)}</p>}{arrived&&<div className="mt-4 flex items-center justify-center gap-2 rounded-2xl border border-emerald-400/20 bg-emerald-500/10 p-3 text-sm font-black text-emerald-200"><CheckCircle2 className="h-5 w-5"/>Llegaste al domicilio</div>}</div>
        {selected&&client&&<><div className="mt-4 grid grid-cols-2 gap-2"><a href={`tel:${client.phone}`} className="flex items-center justify-center gap-2 rounded-2xl border border-slate-800 bg-slate-950 px-3 py-3 text-xs font-black"><Phone className="h-4 w-4"/>Llamar</a><button onClick={()=>setPayOpen(true)} className="flex items-center justify-center gap-2 rounded-2xl bg-emerald-500 px-3 py-3 text-xs font-black text-slate-950"><WalletCards className="h-4 w-4"/>Registrar abono</button><a href={`https://www.google.com/maps/dir/?api=1&destination=${client.latitude},${client.longitude}&travelmode=driving`} target="_blank" rel="noreferrer" className="col-span-2 flex items-center justify-center gap-2 rounded-2xl border border-slate-800 bg-slate-900 px-3 py-3 text-xs font-black text-slate-300"><MapPin className="h-4 w-4"/>Respaldo: Google Maps</a></div><div className="mt-4 rounded-[22px] border border-white/5 bg-slate-950 p-4"><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Nota opcional" className="min-h-20 w-full rounded-xl border border-slate-800 bg-slate-900 p-3 text-sm text-white outline-none"/><div className="mt-3 grid grid-cols-2 gap-2"><button disabled={saving||!online} onClick={()=>saveVisit('NOT_HOME','NO_ESTABA')} className="rounded-xl border border-slate-700 bg-slate-900 px-3 py-3 text-xs font-black"><XCircle className="mr-1 inline h-4 w-4"/>No estaba</button><button disabled={saving||!online} onClick={()=>saveVisit('REFUSED',noPayReason)} className="rounded-xl border border-orange-400/20 bg-orange-500/10 px-3 py-3 text-xs font-black text-orange-200">No pagó</button></div><select value={noPayReason} onChange={e=>setNoPayReason(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-800 bg-slate-900 px-3 py-3 text-xs"><option value="NO_TENIA_DINERO">No tenía dinero</option><option value="PROMESA_PAGO">Promesa de pago</option><option value="ESTA_DE_VIAJE">Está de viaje</option><option value="PROBLEMA_FAMILIAR">Problema familiar</option><option value="RECHAZO_PAGAR">Rechazó pagar</option><option value="OTRO">Otro</option></select><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_auto]"><input type="date" value={rescheduleDate} onChange={e=>setRescheduleDate(e.target.value)} className="rounded-xl border border-slate-800 bg-slate-900 px-3 py-3 text-xs"/><button disabled={saving||!rescheduleDate||!online} onClick={()=>saveVisit('RESCHEDULED','PROMESA_PAGO')} className="flex items-center justify-center gap-2 rounded-xl border border-blue-400/20 bg-blue-500/10 px-4 py-3 text-xs font-black text-blue-200 disabled:opacity-40"><CalendarClock className="h-4 w-4"/>Reagendar</button></div><button onClick={skip} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-slate-800 px-3 py-3 text-xs font-black text-slate-400"><SkipForward className="h-4 w-4"/>Omitir y seguir</button></div></>}
        {!selected&&cashSession&&<button onClick={()=>router.push('/route/close')} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-white px-4 py-4 text-sm font-black text-slate-950"><ClipboardCheck className="h-5 w-5"/>Finalizar ruta y hacer arqueo</button>}
      </article><article className="rounded-[26px] border border-white/5 bg-slate-900/70 p-4"><div className="flex items-center justify-between"><div><p className="text-sm font-black">Ruta {planFrozen?'fijada':'sugerida'}</p><p className="mt-1 text-[11px] text-slate-500">{planFrozen?'El orden no cambia mientras te desplazas':'Inicia GPS para fijar el orden'}</p></div>{planFrozen?<LockKeyhole className="h-5 w-5 text-blue-300"/>:<Crosshair className="h-5 w-5 text-emerald-400"/>}</div><div className="mt-4 space-y-2">{ordered.length===0?<div className="rounded-2xl border border-slate-800 bg-slate-950 p-5 text-center text-sm text-slate-500">Ruta completada o sin clientes con GPS.</div>:ordered.map((c,index)=>{const d=position?distanceMeters(position,{lat:Number(c.client.latitude),lng:Number(c.client.longitude)}):null;const active=selected?.id===c.id;return <button key={c.id} onClick={()=>setSelectedId(c.id)} className={`w-full rounded-2xl border p-3 text-left ${active?'border-emerald-400/30 bg-emerald-400/5':'border-slate-800 bg-slate-950'}`}><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-800 text-xs font-black">{index+1}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{c.client.firstName} {c.client.lastName}</p><p className="mt-1 text-[10px] text-slate-500">Saldo {money.format(c.saldoActual)}{d!=null?` · ahora ${d<1000?`${Math.round(d)} m`:`${(d/1000).toFixed(1)} km`}`:''}</p></div><MapPin className="h-4 w-4 text-slate-600"/></div></button>})}</div></article></section>
    </main>

    {payOpen&&selected&&client&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/90 backdrop-blur sm:items-center sm:p-4 print:hidden"><div className="w-full max-w-md rounded-t-[28px] border border-white/10 bg-slate-900 p-5 sm:rounded-[28px]"><div className="flex items-center justify-between"><div><p className="text-lg font-black">Registrar abono</p><p className="mt-1 text-xs text-slate-500">{client.firstName} {client.lastName}</p></div><button onClick={()=>setPayOpen(false)} className="h-9 w-9 rounded-xl bg-slate-800"><X className="mx-auto h-4 w-4"/></button></div><div className="mt-4 rounded-2xl bg-slate-950 p-4"><p className="text-xs text-slate-500">Saldo actual</p><p className="mt-1 text-2xl font-black">{money.format(selected.saldoActual)}</p></div><input inputMode="decimal" value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)} className="mt-4 w-full rounded-xl border border-slate-800 bg-slate-950 px-3 py-3 text-lg font-black"/><button onClick={()=>setPaymentAmount(String(selected.saldoActual))} className="mt-2 text-xs font-black text-emerald-300">Liquidar saldo completo</button><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>setPaymentMethod('CASH')} className={`rounded-xl border px-3 py-3 text-xs font-black ${paymentMethod==='CASH'?'border-emerald-400/30 bg-emerald-500/10 text-emerald-200':'border-slate-800 text-slate-400'}`}>Efectivo</button><button onClick={()=>setPaymentMethod('BANK_TRANSFER')} className={`rounded-xl border px-3 py-3 text-xs font-black ${paymentMethod==='BANK_TRANSFER'?'border-blue-400/30 bg-blue-500/10 text-blue-200':'border-slate-800 text-slate-400'}`}>Transferencia</button></div><button disabled={saving||!online||(paymentMethod==='CASH'&&!cashSession)} onClick={registerPayment} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-500 px-4 py-3.5 text-sm font-black text-slate-950 disabled:opacity-40">{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}Confirmar abono</button></div></div>}
    {receipt&&<div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/90 p-4 backdrop-blur print:static print:block print:bg-white"><div className="w-full max-w-sm rounded-[24px] bg-white p-6 text-slate-900"><div className="text-center"><p className="text-xl font-black">BITALIS</p><p className="text-xs text-slate-500">Comprobante de pago</p></div><div className="my-5 border-y border-dashed border-slate-300 py-4 text-sm"><p><b>Cliente:</b> {receipt.clientName}</p><p><b>Folio:</b> {receipt.clientNumber}</p><p><b>Crédito:</b> {receipt.creditId}</p><p><b>Fecha:</b> {new Date(receipt.createdAt).toLocaleString('es-MX')}</p></div><div className="text-center"><p className="text-3xl font-black">{money.format(receipt.amount)}</p><p className="mt-3 text-xs text-slate-500">Saldo anterior {money.format(receipt.previousBalance)}</p><p className="text-sm font-black">Nuevo saldo {money.format(receipt.newBalance)}</p></div><div className="mt-5 grid grid-cols-2 gap-2 print:hidden"><button onClick={()=>window.print()} className="flex items-center justify-center gap-2 rounded-xl border border-slate-300 px-3 py-3 text-xs font-black"><Printer className="h-4 w-4"/>Imprimir</button><button onClick={()=>setReceipt(null)} className="rounded-xl bg-slate-900 px-3 py-3 text-xs font-black text-white">Continuar</button></div></div></div>}
  </div>;
}
