'use client';

export type QueueState='QUEUED'|'SYNCING'|'SYNCED'|'CONFLICT'|'FAILED';
export type OfflineOperation={id:string;endpoint:string;method:string;body:any;idempotencyKey:string;createdAt:string;state:QueueState;kind:string;attempts:number;ownerId?:string;lastError?:string};
const DB='bitalis-phase15'; const STORE='offline-operations';
function currentOwner(){try{return String(JSON.parse(localStorage.getItem('bitalis_auth_user')||'{}')?.id||'');}catch{return'';}}
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function queueOperation(op:Omit<OfflineOperation,'id'|'createdAt'|'state'|'attempts'|'ownerId'>){const db=await openDb();const row:OfflineOperation={...op,id:crypto.randomUUID(),createdAt:new Date().toISOString(),state:'QUEUED',attempts:0,ownerId:currentOwner()};await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(row);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});window.dispatchEvent(new CustomEvent('bitalis:queue-changed'));return row;}
export async function listQueued():Promise<OfflineOperation[]>{const db=await openDb(),owner=currentOwner();return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>resolve((r.result||[]).filter((row:OfflineOperation)=>row.ownerId===owner).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)));r.onerror=()=>reject(r.error);});}
export async function updateQueued(row:OfflineOperation){const db=await openDb();return new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(row);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}
export async function removeQueued(id:string){const db=await openDb();return new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}
