'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import {ArrowLeft,Camera,CheckCircle2,Crosshair,ExternalLink,Loader2,MapPin,Save,ShoppingCart,ShieldCheck,Trash2} from 'lucide-react';
import AppShell from '@/components/phase15/AppShell';
import EvidenceImage from '@/components/client/EvidenceImage';
import {apiClient} from '@/lib/phase15/apiClient';
import {haptic} from '@/lib/ux/haptics';

type Form={firstName:string;lastName:string;secondLastName:string;phone:string;secondaryPhone:string;email:string;occupation:string;customerType:string;status:string;latitude:string;longitude:string;locationAccuracy:string};
type AddressForm={street:string;block:string;lot:string;neighborhood:string;crossStreets:string;frontOf:string;nextTo:string;notes:string;postalCode:string;city:string;municipality:string;state:string};
const empty:Form={firstName:'',lastName:'',secondLastName:'',phone:'',secondaryPhone:'',email:'',occupation:'',customerType:'NEW',status:'PROSPECT',latitude:'',longitude:'',locationAccuracy:''};
const emptyAddress:AddressForm={street:'',block:'',lot:'',neighborhood:'',crossStreets:'',frontOf:'',nextTo:'',notes:'',postalCode:'',city:'',municipality:'',state:''};
const evidenceTypes=[['FACADE_PHOTO','Fachada'],['CLIENT_PHOTO','Cliente'],['CONTRACT_PHOTO','Contrato']] as const;

function refPart(raw:string,label:string){return raw.match(new RegExp(`(?:${label}):\\s*([^|]+)`,'i'))?.[1]?.trim()||'';}
function splitReferences(value?:string|null){const raw=String(value||'').trim();const crossStreets=refPart(raw,'Entre calles|Entrecalles'),block=refPart(raw,'Manzana'),lot=refPart(raw,'Lote'),frontOf=refPart(raw,'Frente a'),nextTo=refPart(raw,'Al lado de');const notes=refPart(raw,'Referencia')||(!crossStreets&&!block&&!lot&&!frontOf&&!nextTo?raw:'');return {crossStreets,block,lot,frontOf,nextTo,notes};}
function joinReferences(a:AddressForm){return [a.block.trim()?`Manzana: ${a.block.trim()}`:'',a.lot.trim()?`Lote: ${a.lot.trim()}`:'',a.crossStreets.trim()?`Entre calles: ${a.crossStreets.trim()}`:'',a.frontOf.trim()?`Frente a: ${a.frontOf.trim()}`:'',a.nextTo.trim()?`Al lado de: ${a.nextTo.trim()}`:'',a.notes.trim()?`Referencia: ${a.notes.trim()}`:''].filter(Boolean).join(' | ');}

export default function CompleteClientPage(){
 const params=useParams<{id:string}>(),router=useRouter();
 const[data,setData]=useState<any>(null),[form,setForm]=useState<Form>(empty),[address,setAddress]=useState<AddressForm>(emptyAddress),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[gpsBusy,setGpsBusy]=useState(false),[mediaBusy,setMediaBusy]=useState(''),[deleting,setDeleting]=useState(false),[error,setError]=useState(''),[ok,setOk]=useState(false);
 const load=async()=>{setLoading(true);setError('');try{const raw=localStorage.getItem('bitalis_auth_user');const u=raw?JSON.parse(raw):null;if(!['ADMIN','SUPERVISORA'].includes(String(u?.role||'').toUpperCase())){router.replace(`/clients/${params.id}`);return;}const j:any=await apiClient(`/api/clients/${params.id}`);const c=j?.client||j;setData(c);setForm({firstName:c.firstName||'',lastName:c.lastName==='PENDIENTE'?'':c.lastName||'',secondLastName:c.secondLastName||'',phone:c.phone||'',secondaryPhone:c.secondaryPhone||'',email:c.email||'',occupation:c.occupation||'',customerType:c.customerType==='PENDING_SUPERVISOR'?'NEW':c.customerType||'NEW',status:c.status||'PROSPECT',latitude:c.latitude==null?'':String(c.latitude),longitude:c.longitude==null?'':String(c.longitude),locationAccuracy:c.locationAccuracy==null?'':String(c.locationAccuracy)});const a=(c.addresses||[])[0];if(a){const refs=splitReferences(a.references);setAddress({street:a.street||'',block:refs.block,lot:refs.lot||a.exteriorNumber||'',neighborhood:a.neighborhood||'',crossStreets:refs.crossStreets,frontOf:refs.frontOf,nextTo:refs.nextTo,notes:refs.notes,postalCode:a.postalCode||'',city:a.city||'',municipality:a.municipality||'',state:a.state||''});}}catch(e:any){setError(e.message);}finally{setLoading(false);}};useEffect(()=>{void load();},[params.id]);
 const media=useMemo(()=>data?.media||[],[data]),byType=(type:string)=>media.find((m:any)=>m.mediaType===type);
 const hasGps=form.latitude.trim()!==''&&form.longitude.trim()!=='';
 const completeCount=[form.firstName.trim(),form.lastName.trim(),address.street.trim(),address.neighborhood.trim(),hasGps,byType('FACADE_PHOTO'),byType('CLIENT_PHOTO'),byType('CONTRACT_PHOTO')].filter(Boolean).length,progress=Math.round((completeCount/8)*100);
 const accuracy=Number(form.locationAccuracy),accuracyLabel=Number.isFinite(accuracy)&&accuracy>0?(accuracy<=30?`GPS preciso · ±${Math.round(accuracy)} m`:accuracy<=80?`GPS aceptable · ±${Math.round(accuracy)} m`:`GPS por revisar · ±${Math.round(accuracy)} m`):'Precisión no disponible';
 const submit=async(e:FormEvent)=>{e.preventDefault();haptic('tap');const firstName=form.firstName.trim().replace(/\s+/g,' '),lastName=form.lastName.trim().replace(/\s+/g,' ');if(!firstName||!lastName){setError('Nombre y apellido son obligatorios.');return;}if(!address.street.trim()||!address.neighborhood.trim()){setError('Captura al menos calle y colonia.');return;}if(hasGps){const lat=Number(form.latitude),lng=Number(form.longitude);if(!Number.isFinite(lat)||lat < -90||lat > 90||!Number.isFinite(lng)||lng < -180||lng > 180){setError('Revisa las coordenadas. Latitud debe estar entre -90 y 90 y longitud entre -180 y 180.');return;}}setSaving(true);setError('');setOk(false);try{const locationAccuracy=form.locationAccuracy&&Number.isFinite(Number(form.locationAccuracy))?Number(form.locationAccuracy):undefined;await apiClient(`/api/clients/${params.id}`,{method:'PATCH',body:JSON.stringify({firstName,lastName,secondLastName:form.secondLastName.trim()||null,phone:form.phone.trim(),secondaryPhone:form.secondaryPhone.trim()||null,email:form.email.trim()||null,occupation:form.occupation.trim()||null,customerType:form.customerType,status:form.status,latitude:hasGps?Number(form.latitude):undefined,longitude:hasGps?Number(form.longitude):undefined,locationAccuracy})});await apiClient(`/api/clients/${params.id}/addresses`,{method:'POST',body:JSON.stringify({street:address.street.trim(),exteriorNumber:address.lot.trim()||'S/N',neighborhood:address.neighborhood.trim(),references:joinReferences(address)||undefined,postalCode:address.postalCode.trim()||'00000',city:address.city.trim()||address.municipality.trim()||'Pendiente',municipality:address.municipality.trim()||undefined,state:address.state.trim()||'México',country:'MEXICO',latitude:hasGps?Number(form.latitude):undefined,longitude:hasGps?Number(form.longitude):undefined,accuracy:locationAccuracy,isPrimary:true})});haptic('success');setOk(true);await load();}catch(e:any){haptic('error');setError(e.message);}finally{setSaving(false);}};
 const replaceEvidence=async(type:string,file?:File|null)=>{if(!file)return;haptic('tap');setMediaBusy(type);setError('');try{const fd=new FormData();fd.set('mediaType',type);fd.set('file',file);const token=localStorage.getItem('bitalis_access_token');const res=await fetch(`/api/clients/${params.id}/media`,{method:'POST',headers:token?{Authorization:`Bearer ${token}`}:{},body:fd});const j=await res.json().catch(()=>({}));if(!res.ok)throw new Error(j?.error||'No pudimos actualizar la evidencia.');haptic('success');await load();setOk(true);}catch(e:any){haptic('error');setError(e.message);}finally{setMediaBusy('');}};
 const deleteEvidence=async(item:any)=>{if(!item||!confirm('¿Eliminar esta evidencia?'))return;haptic('tap');setMediaBusy(item.mediaType);try{await apiClient(`/api/clients/${params.id}/media?mediaId=${encodeURIComponent(item.id)}`,{method:'DELETE'});haptic('success');await load();}catch(e:any){haptic('error');setError(e.message);}finally{setMediaBusy('');}};
 const deleteClient=async()=>{if(!confirm('¿Eliminar este cliente? Solo se permitirá si no tiene historial financiero.'))return;haptic('tap');setDeleting(true);try{await apiClient(`/api/clients/${params.id}`,{method:'DELETE'});haptic('success');router.replace('/clients');}catch(e:any){haptic('error');setError(e.message);}finally{setDeleting(false);}};
 const captureGps=()=>{if(!navigator.geolocation){setError('Este dispositivo no permite ubicación.');return;}haptic('tap');setGpsBusy(true);setError('');navigator.geolocation.getCurrentPosition(async p=>{const lat=p.coords.latitude,lng=p.coords.longitude;setForm(v=>({...v,latitude:String(lat),longitude:String(lng),locationAccuracy:String(p.coords.accuracy)}));try{const geo:any=await apiClient(`/api/geocode/reverse?lat=${lat}&lon=${lng}`);if(geo?.success){const g=geo.data||{};setAddress(v=>({...v,street:g.street||v.street,lot:g.exteriorNumber||v.lot,neighborhood:g.neighborhood||v.neighborhood,postalCode:g.postalCode||v.postalCode,city:g.city||v.city,municipality:g.municipality||v.municipality,state:g.state||v.state}));}}catch{}haptic('success');setGpsBusy(false);},()=>{haptic('error');setError('No pudimos capturar la ubicación. Revisa el permiso GPS.');setGpsBusy(false);},{enableHighAccuracy:true,timeout:12000,maximumAge:0});};
 const set=(k:keyof Form,v:string)=>setForm(p=>({...p,[k]:v})),setA=(k:keyof AddressForm,v:string)=>setAddress(p=>({...p,[k]:v}));
 const openMap=()=>hasGps&&window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${form.latitude},${form.longitude}`)}`,'_blank','noopener,noreferrer');
 return <AppShell title="Editar cliente"><main className="mx-auto max-w-4xl px-3 py-4 pb-28 sm:px-4 sm:py-5 sm:pb-6">{loading?<div className="flex justify-center p-16"><Loader2 className="h-6 w-6 animate-spin"/></div>:<><button onClick={()=>{haptic('tap');router.push('/clients')}} className="mb-3 flex min-h-11 items-center gap-2 text-sm font-black text-[var(--bitalis-primary)]"><ArrowLeft className="h-4 w-4"/>Clientes</button><section className="rounded-[26px] bg-[var(--bitalis-primary)] p-4 text-white sm:rounded-[28px] sm:p-5"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.14em] text-[var(--bitalis-mint)]"><ShieldCheck className="h-4 w-4"/>Supervisión en campo</div><h1 className="mt-2 text-2xl font-black">Expediente del cliente</h1><p className="mt-2 text-sm text-emerald-50/75">Completa domicilio, ubicación y evidencias. Todo queda disponible para la operación posterior.</p><div className="mt-4"><div className="flex items-center justify-between text-[10px] font-black uppercase tracking-[.12em] text-emerald-50/70"><span>Expediente</span><span>{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[var(--bitalis-action)] transition-all" style={{width:`${progress}%`}}/></div></div></section>{error&&<div role="alert" className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}{ok&&<div className="mt-4 flex gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-700"><CheckCircle2 className="h-5 w-5"/>Expediente guardado.</div>}
 <section className="mt-4 grid grid-cols-3 gap-2">{evidenceTypes.map(([type,label])=>{const item=byType(type),busy=mediaBusy===type;return <article key={type} className="min-w-0 rounded-2xl border border-slate-200 bg-white p-2"><div className="relative"><EvidenceImage storageKey={item?.storageKey} alt={label} className="h-24 w-full sm:h-28"/>{busy&&<div className="absolute inset-0 flex items-center justify-center rounded-xl bg-white/75"><Loader2 className="h-5 w-5 animate-spin text-[var(--bitalis-primary)]"/></div>}</div><p className="mt-2 truncate text-center text-[11px] font-black text-[var(--bitalis-primary)]">{label}</p><div className="mt-2 grid gap-1"><label className="flex min-h-10 cursor-pointer touch-manipulation items-center justify-center rounded-lg bg-[var(--bitalis-primary)] px-1 text-[9px] font-black text-white active:scale-95"><Camera className="mr-1 h-3 w-3"/>{item?'CAMBIAR':'TOMAR'}<input type="file" accept="image/*" capture="environment" className="hidden" onChange={e=>replaceEvidence(type,e.target.files?.[0])}/></label><button type="button" disabled={!item||busy} onClick={()=>deleteEvidence(item)} className="flex min-h-10 items-center justify-center rounded-lg bg-red-50 px-1 text-[9px] font-black text-red-700 active:scale-95 disabled:opacity-35"><Trash2 className="mr-1 h-3 w-3"/>QUITAR</button></div></article>})}</section>
 <form id="client-complete-form" onSubmit={submit} className="mt-4 space-y-4"><section className="grid gap-3 rounded-[24px] border border-slate-200 bg-white p-4 sm:grid-cols-2"><h2 className="text-sm font-black text-[var(--bitalis-primary)] sm:col-span-2">Datos del cliente</h2><Field label="Nombre" value={form.firstName} onChange={v=>set('firstName',v)} required/><Field label="Apellido" value={form.lastName} onChange={v=>set('lastName',v)} required/><Field label="Segundo apellido" value={form.secondLastName} onChange={v=>set('secondLastName',v)}/><Field label="Teléfono principal" value={form.phone} onChange={v=>set('phone',v)} inputMode="tel"/><Field label="Teléfono adicional" value={form.secondaryPhone} onChange={v=>set('secondaryPhone',v)} inputMode="tel" placeholder="Opcional"/></section>
 <section className="grid gap-3 rounded-[24px] border border-slate-200 bg-white p-4 sm:grid-cols-2"><h2 className="text-sm font-black text-[var(--bitalis-primary)] sm:col-span-2">Domicilio</h2><Field label="Calle * · automática por GPS" value={address.street} onChange={v=>setA('street',v)} required/><Field label="Manzana" value={address.block} onChange={v=>setA('block',v)}/><Field label="Lote" value={address.lot} onChange={v=>setA('lot',v)}/><Field label="Colonia * · automática por GPS" value={address.neighborhood} onChange={v=>setA('neighborhood',v)} required/><Field label="Código postal" value={address.postalCode} onChange={v=>setA('postalCode',v)} inputMode="numeric"/><Field label="Municipio / ciudad" value={address.municipality||address.city} onChange={v=>{setA('municipality',v);setA('city',v)}}/><Field label="Entre calles" value={address.crossStreets} onChange={v=>setA('crossStreets',v)} placeholder="Ej. Calle A y Calle B"/><Field label="Frente a" value={address.frontOf} onChange={v=>setA('frontOf',v)} placeholder="Ej. parque o tienda"/><Field label="Al lado de" value={address.nextTo} onChange={v=>setA('nextTo',v)} placeholder="Ej. farmacia"/><label className="block sm:col-span-2"><span className="text-xs font-black text-slate-500">Nota o referencia del domicilio</span><textarea value={address.notes} onChange={e=>setA('notes',e.target.value)} rows={3} className="mt-2 w-full rounded-2xl border border-slate-200 bg-slate-50 p-4 text-base outline-none focus:ring-2 focus:ring-[var(--bitalis-action)]" placeholder="Ej. portón verde, junto a farmacia, casa con reja negra"/></label></section>
 <section className="rounded-[24px] border border-emerald-100 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-black text-[var(--bitalis-primary)]">Ubicación del domicilio</h2><p className="mt-1 text-[11px] text-slate-500">Puedes recapturar con GPS o corregir las coordenadas manualmente.</p></div>{hasGps&&<button type="button" onClick={openMap} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700" aria-label="Abrir ubicación en mapa"><ExternalLink className="h-4 w-4"/></button>}</div><button type="button" onClick={captureGps} disabled={gpsBusy} className={`mt-3 flex min-h-14 w-full touch-manipulation items-center justify-center gap-2 rounded-2xl border text-xs font-black active:scale-[.98] ${hasGps?'border-emerald-200 bg-emerald-50 text-emerald-700':'border-slate-200 bg-[var(--bitalis-surface-soft)] text-[var(--bitalis-primary)]'}`}>{gpsBusy?<Loader2 className="h-4 w-4 animate-spin"/>:hasGps?<MapPin className="h-4 w-4"/>:<Crosshair className="h-4 w-4"/>}{gpsBusy?'CAPTURANDO…':hasGps?'RECAPTURAR GPS':'CAPTURAR GPS'}</button><div className="mt-3 grid grid-cols-2 gap-2"><Field label="Latitud" value={form.latitude} onChange={v=>{set('latitude',v);set('locationAccuracy','')}} inputMode="decimal" placeholder="19.432608"/><Field label="Longitud" value={form.longitude} onChange={v=>{set('longitude',v);set('locationAccuracy','')}} inputMode="decimal" placeholder="-99.133209"/></div>{hasGps&&<div className={`mt-3 rounded-xl px-3 py-2 text-[10px] font-bold ${Number.isFinite(accuracy)&&accuracy>80?'bg-amber-50 text-amber-800':'bg-emerald-50 text-emerald-700'}`}>{accuracyLabel}</div>}</section>
 <button disabled={saving} className="hidden min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-[var(--bitalis-action)] text-sm font-black text-white active:scale-[.98] disabled:opacity-50 sm:flex">{saving?<Loader2 className="h-5 w-5 animate-spin"/>:<Save className="h-5 w-5"/>}{saving?'GUARDANDO…':'GUARDAR EXPEDIENTE'}</button></form>
 <button type="button" onClick={()=>{haptic('tap');router.push(`/sales/new?clientId=${params.id}`)}} className="mt-3 hidden min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-[var(--bitalis-primary)] text-sm font-black text-white active:scale-[.98] sm:flex"><ShoppingCart className="h-5 w-5"/>CONTINUAR A VENTA</button><button type="button" onClick={deleteClient} disabled={deleting} className="mt-4 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl border border-red-200 bg-red-50 text-xs font-black text-red-700 active:scale-[.98] disabled:opacity-50">{deleting?<Loader2 className="h-4 w-4 animate-spin"/>:<Trash2 className="h-4 w-4"/>}Eliminar cliente</button>
 <div className="fixed inset-x-0 bottom-[calc(64px+env(safe-area-inset-bottom))] z-40 border-t border-slate-200 bg-white/95 p-2 shadow-[0_-10px_30px_rgba(15,23,42,.10)] backdrop-blur sm:hidden"><div className="mx-auto grid max-w-4xl grid-cols-[1fr_auto] gap-2"><button type="submit" form="client-complete-form" disabled={saving} className="flex min-h-14 items-center justify-center gap-2 rounded-2xl bg-[var(--bitalis-action)] px-4 text-sm font-black text-white active:scale-[.98] disabled:opacity-50">{saving?<Loader2 className="h-5 w-5 animate-spin"/>:<Save className="h-5 w-5"/>}{saving?'GUARDANDO…':'GUARDAR'}</button><button type="button" onClick={()=>{haptic('tap');router.push(`/sales/new?clientId=${params.id}`)}} className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[var(--bitalis-primary)] text-white active:scale-95" aria-label="Continuar a venta"><ShoppingCart className="h-5 w-5"/></button></div></div></>}</main></AppShell>}
function Field({label,value,onChange,required=false,inputMode,placeholder}:{label:string;value:string;onChange:(v:string)=>void;required?:boolean;inputMode?:any;placeholder?:string}){return <label className="block"><span className="text-xs font-black text-slate-500">{label}</span><input required={required} inputMode={inputMode} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="mt-2 min-h-12 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 text-base outline-none focus:ring-2 focus:ring-[var(--bitalis-action)]"/></label>}
