'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import {ArrowLeft,Camera,CheckCircle2,Loader2,MapPin,ShoppingCart,ShieldCheck,Trash2} from 'lucide-react';
import AppShell from '@/components/phase15/AppShell';
import EvidenceImage from '@/components/client/EvidenceImage';
import {apiClient} from '@/lib/phase15/apiClient';

type Form={firstName:string;lastName:string;secondLastName:string;phone:string;secondaryPhone:string;email:string;occupation:string;customerType:string;status:string;latitude:string;longitude:string};
type AddressForm={street:string;exteriorNumber:string;interiorNumber:string;neighborhood:string;references:string;postalCode:string;city:string;municipality:string;state:string};
const empty:Form={firstName:'',lastName:'',secondLastName:'',phone:'',secondaryPhone:'',email:'',occupation:'',customerType:'NEW',status:'PROSPECT',latitude:'',longitude:''};
const emptyAddress:AddressForm={street:'',exteriorNumber:'',interiorNumber:'',neighborhood:'',references:'',postalCode:'',city:'',municipality:'',state:''};
const evidenceTypes=[['FACADE_PHOTO','Fachada'],['CLIENT_PHOTO','Cliente'],['CONTRACT_PHOTO','Contrato']] as const;

export default function CompleteClientPage(){
 const params=useParams<{id:string}>(),router=useRouter();
 const[data,setData]=useState<any>(null),[form,setForm]=useState<Form>(empty),[address,setAddress]=useState<AddressForm>(emptyAddress),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[mediaBusy,setMediaBusy]=useState(''),[deleting,setDeleting]=useState(false),[error,setError]=useState(''),[ok,setOk]=useState(false);
 const load=async()=>{setLoading(true);try{const raw=localStorage.getItem('bitalis_auth_user');const u=raw?JSON.parse(raw):null;if(!['ADMIN','SUPERVISORA'].includes(String(u?.role||'').toUpperCase())){router.replace(`/clients/${params.id}`);return;}const j:any=await apiClient(`/api/clients/${params.id}`);const c=j?.client||j;setData(c);setForm({firstName:c.firstName||'',lastName:c.lastName==='PENDIENTE'?'':c.lastName||'',secondLastName:c.secondLastName||'',phone:c.phone||'',secondaryPhone:c.secondaryPhone||'',email:c.email||'',occupation:c.occupation||'',customerType:c.customerType==='PENDING_SUPERVISOR'?'NEW':c.customerType||'NEW',status:c.status||'PROSPECT',latitude:c.latitude==null?'':String(c.latitude),longitude:c.longitude==null?'':String(c.longitude)});const a=(c.addresses||[])[0];if(a)setAddress({street:a.street||'',exteriorNumber:a.exteriorNumber||'',interiorNumber:a.interiorNumber||'',neighborhood:a.neighborhood||'',references:a.references||'',postalCode:a.postalCode||'',city:a.city||'',municipality:a.municipality||'',state:a.state||''});}catch(e:any){setError(e.message);}finally{setLoading(false);}};useEffect(()=>{load();},[params.id]);
 const media=useMemo(()=>data?.media||[],[data]);const byType=(type:string)=>media.find((m:any)=>m.mediaType===type);
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!form.firstName.trim()||!form.lastName.trim()){setError('Nombre y apellido son obligatorios.');return;}if(!address.street.trim()||!address.neighborhood.trim()){setError('Captura al menos calle y colonia.');return;}setSaving(true);setError('');setOk(false);try{await apiClient(`/api/clients/${params.id}`,{method:'PATCH',body:JSON.stringify({firstName:form.firstName.trim(),lastName:form.lastName.trim(),secondLastName:form.secondLastName.trim()||null,phone:form.phone.trim(),secondaryPhone:form.secondaryPhone.trim()||null,email:form.email.trim()||null,occupation:form.occupation.trim()||null,customerType:form.customerType,status:form.status,latitude:form.latitude?Number(form.latitude):undefined,longitude:form.longitude?Number(form.longitude):undefined})});await apiClient(`/api/clients/${params.id}/addresses`,{method:'POST',body:JSON.stringify({street:address.street.trim(),exteriorNumber:address.exteriorNumber.trim()||'S/N',interiorNumber:address.interiorNumber.trim()||undefined,neighborhood:address.neighborhood.trim(),references:address.references.trim()||undefined,postalCode:address.postalCode.trim()||'00000',city:address.city.trim()||address.municipality.trim()||'Pendiente',municipality:address.municipality.trim()||undefined,state:address.state.trim()||'México',country:'MEXICO',latitude:form.latitude?Number(form.latitude):undefined,longitude:form.longitude?Number(form.longitude):undefined,isPrimary:true})});setOk(true);await load();}catch(e:any){setError(e.message);}finally{setSaving(false);}};
 const replaceEvidence=async(type:string,file?:File|null)=>{if(!file)return;setMediaBusy(type);setError('');try{const fd=new FormData();fd.set('mediaType',type);fd.set('file',file);const token=localStorage.getItem('bitalis_access_token');const res=await fetch(`/api/clients/${params.id}/media`,{method:'POST',headers:token?{Authorization:`Bearer ${token}`}:{},body:fd});const j=await res.json().catch(()=>({}));if(!res.ok)throw new Error(j?.error||'No pudimos actualizar la evidencia.');await load();setOk(true);}catch(e:any){setError(e.message);}finally{setMediaBusy('');}};
 const deleteEvidence=async(item:any)=>{if(!item||!confirm('¿Eliminar esta evidencia?'))return;setMediaBusy(item.mediaType);try{await apiClient(`/api/clients/${params.id}/media?mediaId=${encodeURIComponent(item.id)}`,{method:'DELETE'});await load();}catch(e:any){setError(e.message);}finally{setMediaBusy('');}};
 const deleteClient=async()=>{if(!confirm('¿Eliminar este cliente? Solo se permitirá si no tiene historial financiero.'))return;setDeleting(true);try{await apiClient(`/api/clients/${params.id}`,{method:'DELETE'});router.replace('/clients');}catch(e:any){setError(e.message);}finally{setDeleting(false);}};
 const captureGps=()=>{if(!navigator.geolocation){setError('Este dispositivo no permite ubicación.');return;}navigator.geolocation.getCurrentPosition(p=>setForm(v=>({...v,latitude:String(p.coords.latitude),longitude:String(p.coords.longitude)})),()=>setError('No pudimos capturar la ubicación.'),{enableHighAccuracy:true,timeout:10000});};
 const set=(k:keyof Form,v:string)=>setForm(p=>({...p,[k]:v})),setA=(k:keyof AddressForm,v:string)=>setAddress(p=>({...p,[k]:v}));
 return <AppShell title="Editar cliente"><main className="mx-auto max-w-4xl px-4 py-5">{loading?<div className="flex justify-center p-16"><Loader2 className="h-6 w-6 animate-spin"/></div>:<><button onClick={()=>router.push('/clients')} className="mb-4 flex min-h-11 items-center gap-2 text-sm font-black text-[#12224A]"><ArrowLeft className="h-4 w-4"/>Clientes</button><section className="rounded-[28px] bg-[#12224A] p-5 text-white"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.14em] text-[#C79A3B]"><ShieldCheck className="h-4 w-4"/>Supervisión en campo</div><h1 className="mt-3 text-2xl font-black">Expediente del cliente</h1><p className="mt-2 text-sm text-slate-300">Completa domicilio y evidencias; después puedes pasar directo a la venta.</p></section>{error&&<div className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}{ok&&<div className="mt-4 flex gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-700"><CheckCircle2 className="h-5 w-5"/>Expediente guardado.</div>}
 <section className="mt-4 grid grid-cols-3 gap-2">{evidenceTypes.map(([type,label])=>{const item=byType(type);return <article key={type} className="rounded-2xl border border-slate-200 bg-white p-2"><EvidenceImage storageKey={item?.storageKey} alt={label} className="h-28 w-full"/><p className="mt-2 text-center text-[11px] font-black text-[#12224A]">{label}</p><div className="mt-2 grid grid-cols-2 gap-1"><label className="flex min-h-9 cursor-pointer items-center justify-center rounded-lg bg-[#12224A] text-[9px] font-black text-white"><Camera className="mr-1 h-3 w-3"/>Cambiar<input type="file" accept="image/*" capture="environment" className="hidden" onChange={e=>replaceEvidence(type,e.target.files?.[0])}/></label><button type="button" disabled={!item} onClick={()=>deleteEvidence(item)} className="flex min-h-9 items-center justify-center rounded-lg bg-red-50 text-[9px] font-black text-red-700 disabled:opacity-40"><Trash2 className="mr-1 h-3 w-3"/>Quitar</button></div></article>})}</section>
 <form onSubmit={submit} className="mt-4 space-y-4"><section className="grid gap-3 rounded-[24px] border border-slate-200 bg-white p-4 sm:grid-cols-2"><h2 className="sm:col-span-2 text-sm font-black text-[#12224A]">Datos del cliente</h2><Field label="Nombre" value={form.firstName} onChange={v=>set('firstName',v)} required/><Field label="Apellido" value={form.lastName} onChange={v=>set('lastName',v)} required/><Field label="Segundo apellido" value={form.secondLastName} onChange={v=>set('secondLastName',v)}/><Field label="Teléfono" value={form.phone} onChange={v=>set('phone',v)} inputMode="tel"/></section>
 <section className="grid gap-3 rounded-[24px] border border-slate-200 bg-white p-4 sm:grid-cols-2"><h2 className="sm:col-span-2 text-sm font-black text-[#12224A]">Domicilio</h2><Field label="Calle *" value={address.street} onChange={v=>setA('street',v)} required/><Field label="Número" value={address.exteriorNumber} onChange={v=>setA('exteriorNumber',v)}/><Field label="Colonia *" value={address.neighborhood} onChange={v=>setA('neighborhood',v)} required/><Field label="Entrecalles" value={address.references} onChange={v=>setA('references',v)}/><Field label="Código postal" value={address.postalCode} onChange={v=>setA('postalCode',v)} inputMode="numeric"/><Field label="Municipio / ciudad" value={address.municipality||address.city} onChange={v=>{setA('municipality',v);setA('city',v)}}/><label className="sm:col-span-2 block"><span className="text-xs font-black text-slate-500">Nota o referencia del domicilio</span><textarea value={address.references} onChange={e=>setA('references',e.target.value)} rows={3} className="mt-2 w-full rounded-2xl border border-slate-200 bg-slate-50 p-4 outline-none focus:ring-2 focus:ring-[#FF6A00]" placeholder="Ej. portón verde, junto a farmacia, entre Calle A y Calle B"/></label><button type="button" onClick={captureGps} className="sm:col-span-2 flex min-h-12 items-center justify-center gap-2 rounded-2xl border border-blue-200 bg-blue-50 text-xs font-black text-blue-700"><MapPin className="h-4 w-4"/>{form.latitude&&form.longitude?'Actualizar coordenadas':'Capturar coordenadas'}</button>{form.latitude&&form.longitude&&<p className="sm:col-span-2 text-center text-[10px] text-slate-500">{Number(form.latitude).toFixed(6)}, {Number(form.longitude).toFixed(6)}</p>}</section>
 <button disabled={saving} className="flex min-h-14 w-full items-center justify-center rounded-2xl bg-[#FF6A00] text-sm font-black text-white disabled:opacity-50">{saving?<Loader2 className="h-5 w-5 animate-spin"/>:'GUARDAR EXPEDIENTE'}</button></form>
 <button type="button" onClick={()=>router.push(`/sales/new?clientId=${params.id}`)} className="mt-3 flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-[#12224A] text-sm font-black text-white"><ShoppingCart className="h-5 w-5"/>CONTINUAR A VENTA</button><button type="button" onClick={deleteClient} disabled={deleting} className="mt-4 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl border border-red-200 bg-red-50 text-xs font-black text-red-700 disabled:opacity-50">{deleting?<Loader2 className="h-4 w-4 animate-spin"/>:<Trash2 className="h-4 w-4"/>}Eliminar cliente</button></>}</main></AppShell>}
function Field({label,value,onChange,required=false,inputMode}:{label:string;value:string;onChange:(v:string)=>void;required?:boolean;inputMode?:any}){return <label className="block"><span className="text-xs font-black text-slate-500">{label}</span><input required={required} inputMode={inputMode} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 min-h-12 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 outline-none focus:ring-2 focus:ring-[#FF6A00]"/></label>}
