'use client';

import {useEffect,useMemo,useState} from 'react';
import {BarChart3,Loader2,ShieldAlert,ShoppingBag,Users,WalletCards} from 'lucide-react';
import AppShell from '@/components/phase15/AppShell';
import {apiClient} from '@/lib/phase15/apiClient';

const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'});
export default function ReportsPage(){const[sales,setSales]=useState<any[]>([]),[portfolio,setPortfolio]=useState<any[]>([]),[clients,setClients]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{(async()=>{try{const [s,p,c]:any[]=await Promise.all([apiClient('/api/sales'),apiClient('/api/collections/portfolio'),apiClient('/api/clients?page=1&limit=200')]);setSales(s?.sales||s?.data||[]);setPortfolio(p?.data||[]);setClients(c?.data||[]);}catch(e:any){setError(e.message);}finally{setLoading(false);}})();},[]);const totals=useMemo(()=>({sales:sales.reduce((n,x)=>n+Number(x.totalAmount||0),0),cartera:portfolio.reduce((n,x)=>n+Number(x.saldoActual||0),0),critical:portfolio.filter(x=>['HIGH','CRITICAL'].includes(String(x.client?.riskLevel||''))).length}),[sales,portfolio]);return <AppShell title="Reportes"><div className="mx-auto max-w-7xl px-4 py-5"><section className="rounded-[28px] bg-[#12224A] p-5 text-white"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.14em] text-[#C79A3B]"><BarChart3 className="h-4 w-4"/>Datos reales</div><h1 className="mt-3 text-2xl font-black">Reportes operativos</h1><p className="mt-2 text-sm text-slate-300">Resumen responsive sin modificar las reglas del backend.</p></section>{error&&<div className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}{loading?<div className="flex justify-center p-14"><Loader2 className="h-7 w-7 animate-spin text-[#12224A]"/></div>:<><section className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{[[ShoppingBag,'Ventas',money.format(totals.sales)],[WalletCards,'Cartera',money.format(totals.cartera)],[Users,'Clientes',clients.length],[ShieldAlert,'Riesgo alto',totals.critical]].map(([I,l,v]:any)=><div key={l} className="rounded-3xl border border-slate-200 bg-white p-4"><I className="h-5 w-5 text-[#C79A3B]"/><p className="mt-3 text-[10px] font-black uppercase text-slate-400">{l}</p><p className="mt-1 text-xl font-black text-[#12224A]">{v}</p></div>)}</section><section className="mt-5 rounded-3xl border border-slate-200 bg-white p-5"><h2 className="font-black text-[#12224A]">Cartera por nivel de riesgo</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{['LOW','MEDIUM','HIGH','CRITICAL'].map(r=>{const rows=portfolio.filter(x=>String(x.client?.riskLevel||'LOW')===r);return <div key={r} className="rounded-2xl bg-slate-50 p-4"><p className="text-[10px] font-black text-slate-400">{r}</p><p className="mt-1 text-lg font-black text-[#12224A]">{rows.length}</p><p className="text-xs text-slate-500">{money.format(rows.reduce((s,x)=>s+Number(x.saldoActual||0),0))}</p></div>})}</div></section></>}</div></AppShell>}
