'use client';
import {FormEvent,useRef,useState,type ReactNode} from 'react';
import {AlertCircle,Camera,CheckCircle2,Crosshair,FileCheck2,Home,Images,Info,Loader2,MapPin,Send,UserRound,X} from 'lucide-react';
import AppShell,{useShellPermissions} from '@/components/phase15/AppShell';
import {apiClient,newIdempotencyKey} from '@/lib/phase15/apiClient';
import {haptic} from '@/lib/ux/haptics';

type Photos={facade:File|null;clientPhoto:File|null;contract:File|null};
type Geo={address?:string;neighborhood?:string;postalCode?:string;city?:string;municipality?:string;state?:string};
type Notice={type:'success'|'error'|'info';title:string;message:string}|null;
const emptyPhotos=():Photos=>({facade:null,clientPhoto:null,contract:null});
const input='min-h-14 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 text-base outline-none focus:border-[var(--bitalis-action)] focus:ring-4 focus:ring-emerald-500/10';

async function compressImage(file:File){if(!file.type.startsWith('image/'))return file;const bitmap=await createImageBitmap(file),scale=Math.min(1,1280/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');if(!ctx){bitmap.close();return file}ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',.76));bitmap.close();return blob?new File([blob],file.name.replace(/\.[^.]+$/,'.jpg'),{type:'image/jpeg'}):file}

export default function QuickClientIntake(){
 const permissions=useShellPermissions(),nameRef=useRef<HTMLInputElement|null>(null);
 const[name,setName]=useState(''),[phone,setPhone]=useState(''),[photos,setPhotos]=useState<Photos>(emptyPhotos),[position,setPosition]=useState<{lat:number;lng:number;accuracy?:number}|null>(null),[geo,setGeo]=useState<Geo>({}),[saving,setSaving]=useState(false),[gpsLoading,setGpsLoading]=useState(false),[notice,setNotice]=useState<Notice>(null);
 const photoCount=Object.values(photos).filter(Boolean).length,canCreate=true;
 const popup=(type:NonNullable<Notice>['type'],title:string,message:string)=>setNotice({type,title,message});
 const clearSensitiveForm=()=>{setName('');setPhone('');setPhotos(emptyPhotos());setPosition(null);setGeo({});nameRef.current?.focus()};
 const pick=async(key:keyof Photos,file?:File|null)=>{if(!file)return;haptic('tap');try{const compact=await compressImage(file);setPhotos(current=>({...current,[key]:compact}));haptic('success')}catch{setPhotos(current=>({...current,[key]:file}));popup('info','Fotografía agregada','La imagen se conservará en su tamaño original.')}};
 const captureGps=()=>{haptic('tap');if(!navigator.geolocation){popup('error','GPS no disponible','Este dispositivo no permite capturar ubicación.');return}setGpsLoading(true);navigator.geolocation.getCurrentPosition(async result=>{const next={lat:result.coords.latitude,lng:result.coords.longitude,accuracy:result.coords.accuracy};setPosition(next);try{const json:any=await apiClient(`/api/geocode/reverse?lat=${next.lat}&lon=${next.lng}`);setGeo(json?.success?json.data||{}:{});popup('success','Ubicación capturada','La supervisora recibirá las coordenadas, calle, colonia y datos disponibles de la zona.');haptic('success')}catch{setGeo({});popup('success','Coordenadas capturadas','La supervisora podrá completar posteriormente la dirección.')}finally{setGpsLoading(false)}},()=>{popup('error','No se pudo obtener la ubicación','Activa el GPS, permite el acceso a la ubicación e intenta nuevamente.');setGpsLoading(false);haptic('error')},{enableHighAccuracy:true,maximumAge:0,timeout:12000})};
 const submit=async(event:FormEvent)=>{event.preventDefault();haptic('tap');if(!name.trim()){nameRef.current?.focus();return popup('error','Falta información','Escribe el nombre completo del cliente.')}if(!position)return popup('error','Falta la ubicación','Captura las coordenadas del domicilio antes de enviar.');if(!canCreate)return popup('error','Acceso no disponible',permissions===null?'Estamos validando tu acceso. Espera un momento e intenta nuevamente.':'Tu usuario no tiene habilitada el Alta rápida.');setSaving(true);try{const form=new FormData(),key=newIdempotencyKey('field-client');form.set('name',name.trim().replace(/\s+/g,' '));form.set('phone',phone.trim());if(photos.facade)form.set('facade',photos.facade);if(photos.clientPhoto)form.set('clientPhoto',photos.clientPhoto);if(photos.contract)form.set('contract',photos.contract);form.set('latitude',String(position.lat));form.set('longitude',String(position.lng));if(position.accuracy!=null)form.set('locationAccuracy',String(position.accuracy));Object.entries(geo).forEach(([keyName,value])=>value&&form.set(keyName,String(value)));form.set('idempotencyKey',key);await apiClient('/api/clients/intake',{method:'POST',timeoutMs:45000,idempotencyKey:key,body:form});clearSensitiveForm();popup('success','Alta enviada','La supervisora recibió la información. El formulario y las fotografías fueron eliminados de este dispositivo.');haptic('success')}catch(e:any){popup('error','No se pudo enviar',e?.message||'Revisa tu conexión e intenta nuevamente.');haptic('error')}finally{setSaving(false)}};

 return <AppShell title="Alta rápida"><main className="mx-auto w-full max-w-xl px-3 py-4 sm:px-4"><section className="rounded-[24px] bg-[var(--bitalis-primary)] p-4 text-white"><p className="text-[10px] font-black uppercase tracking-[.14em] text-[var(--bitalis-mint)]">Captura protegida</p><h1 className="mt-1 text-xl font-black">Alta rápida</h1><p className="mt-1 text-xs text-emerald-50/80">Solo captura y envío. Después no podrás consultar el expediente.</p></section>
 <form onSubmit={submit} autoComplete="off" className="bitalis-form-card mt-3 space-y-3 p-3 sm:p-4"><F label="Nombre completo *"><input ref={nameRef} autoComplete="off" value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre y apellidos" className={input}/></F><F label="Teléfono (opcional)"><input type="tel" inputMode="tel" autoComplete="off" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Teléfono" className={input}/></F>
 <section className="rounded-2xl border border-emerald-100 bg-emerald-50/60 p-3"><div className="flex gap-2"><MapPin className="h-5 w-5 text-emerald-700"/><div><p className="text-xs font-black text-[var(--bitalis-primary)]">Ubicación del domicilio *</p><p className="text-[10px] leading-4 text-slate-500">Solo supervisión verá coordenadas, calle, colonia y demás detalle.</p></div></div><button type="button" onClick={captureGps} disabled={gpsLoading} className="mt-3 flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-[var(--bitalis-action)] px-3 text-sm font-black text-white disabled:opacity-50">{gpsLoading?<Loader2 className="h-5 w-5 animate-spin"/>:<Crosshair className="h-5 w-5"/>}{gpsLoading?'CAPTURANDO…':position?'UBICACIÓN LISTA · ACTUALIZAR':'CAPTURAR UBICACIÓN'}</button></section>
 <section className="rounded-2xl border border-slate-200 p-3"><div className="flex items-center justify-between text-xs font-black text-[var(--bitalis-primary)]"><span className="flex items-center gap-2"><Images className="h-4 w-4"/>FOTOGRAFÍAS OPCIONALES</span><span>{photoCount}/3</span></div><p className="mt-1 text-[10px] leading-4 text-slate-500">Puedes enviar el alta sin fotografías o agregar solamente las que tengas disponibles.</p><div className="mt-3 grid grid-cols-1 gap-2 min-[360px]:grid-cols-3"><Photo title="Fachada" icon={<Home/>} file={photos.facade} onPick={file=>pick('facade',file)}/><Photo title="Cliente" icon={<UserRound/>} file={photos.clientPhoto} onPick={file=>pick('clientPhoto',file)}/><Photo title="Contrato" icon={<FileCheck2/>} file={photos.contract} onPick={file=>pick('contract',file)}/></div></section>
 <div className="bitalis-form-sticky-actions"><button disabled={saving||gpsLoading} className="flex min-h-16 w-full items-center justify-center gap-2 rounded-2xl bg-[var(--bitalis-action)] px-4 text-base font-black text-white shadow-lg disabled:opacity-40">{saving?<Loader2 className="h-6 w-6 animate-spin"/>:<Send className="h-5 w-5"/>}{saving?'ENVIANDO…':'ENVIAR A SUPERVISIÓN'}</button></div></form></main>{notice&&<NoticePopup notice={notice} onClose={()=>setNotice(null)}/>}</AppShell>
}
function F({label,children}:{label:string;children:ReactNode}){return <label className="block"><span className="bitalis-form-label">{label}</span>{children}</label>}
function Photo({title,icon,file,onPick}:{title:string;icon:ReactNode;file:File|null;onPick:(file:File|null)=>void}){const id=`capture-${title.toLowerCase()}`;return <label htmlFor={id} className={`flex min-h-20 cursor-pointer items-center gap-3 rounded-2xl border px-3 py-3 min-[360px]:min-h-24 min-[360px]:flex-col min-[360px]:justify-center ${file?'border-emerald-200 bg-emerald-50 text-emerald-700':'border-slate-200 bg-white text-slate-600'}`}><span className="[&>svg]:h-5 [&>svg]:w-5">{file?<CheckCircle2/>:icon}</span><span className="text-[10px] font-black">{file?`${title} lista`:title}</span><span className="flex items-center gap-1 text-[9px] opacity-70"><Camera className="h-3 w-3"/>Opcional</span><input id={id} hidden type="file" accept="image/*" capture="environment" onChange={e=>{onPick(e.target.files?.[0]||null);e.currentTarget.value=''}}/></label>}
function NoticePopup({notice,onClose}:{notice:NonNullable<Notice>;onClose:()=>void}){const success=notice.type==='success',error=notice.type==='error',Icon=success?CheckCircle2:error?AlertCircle:Info;return <div className="fixed inset-0 z-[180] flex items-end bg-slate-950/55 p-0 sm:items-center sm:justify-center sm:p-4" role="presentation" onClick={onClose}><section role="alertdialog" aria-modal="true" aria-labelledby="quick-notice-title" onClick={e=>e.stopPropagation()} className="bitalis-bottom-sheet w-full p-4 pb-[max(1rem,env(safe-area-inset-bottom))] sm:max-w-sm sm:rounded-[28px] sm:p-5"><div className="flex items-start justify-between gap-3"><div className={`flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl ${success?'bg-emerald-50 text-emerald-700':error?'bg-red-50 text-red-700':'bg-blue-50 text-blue-700'}`}><Icon className="h-6 w-6"/></div><button type="button" onClick={onClose} className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-slate-100 text-slate-600" aria-label="Cerrar aviso"><X className="h-5 w-5"/></button></div><h2 id="quick-notice-title" className="mt-4 text-xl font-black text-[var(--bitalis-primary)]">{notice.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{notice.message}</p><button type="button" autoFocus onClick={onClose} className={`mt-5 min-h-14 w-full rounded-2xl px-4 text-sm font-black text-white ${error?'bg-red-600':'bg-[var(--bitalis-action)]'}`}>ENTENDIDO</button></section></div>}
