'use client';

import {useEffect,useMemo,useState} from 'react';
import {Banknote,CheckCircle2,Coins,Loader2,RefreshCw,Search,UserRound,WalletCards} from 'lucide-react';
import AppShell from '@/components/phase15/AppShell';
import {apiClient} from '@/lib/phase15/apiClient';
import {haptic} from '@/lib/ux/haptics';

type Item={id:string;saleId:string;saleNumber:string;amount:number;paymentMethod:string;status:string;createdAt:string;seller?:{firstName?:string;lastName?:string;email?:string};client?:{clientNumber?:string;firstName?:string;lastName?:string};sellerCommission:number;sellerRate:number;adminHandoffEstimate:number};
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'});

export default function SupervisorDownPaymentsPage(){
 const[data,setData]=useState<Item[]>([]),[totals,setTotals]=useState<any>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const j:any=await apiClient('/api/supervision/down-payments');setData(Array.isArray(j?.data)?j.data:[]);setTotals(j?.totals||{});}catch(e:any){setError(e?.message||'No pudimos cargar los enganches.');}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return data;return data.filter(x=>`${x.saleNumber} ${x.client?.clientNumber||''} ${x.client?.firstName||''} ${x.client?.lastName||''} ${x.seller?.firstName||''} ${x.seller?.lastName||''} ${x.seller?.email||''}`.toLowerCase().includes(q));},[data,query]);
 const sellers=useMemo(()=>{const map=new Map<string,{name:string,count:number,enganches:number,commission:number,admin:number}>();data.forEach(x=>{const name=x.seller?`${x.seller.firstName||''} ${x.seller.lastName||''}`.trim()||x.seller.email||'Sin asignar':'Sin asignar';const current=map.get(name)||{name,count:0,enganches:0,commission:0,admin:0};current.count++;current.enganches+=x.amount;current.commission+=x.sellerCommission;current.admin+=x.adminHandoffEstimate;map.set(name,current);});return [...map.values()].sort((a,b)=>b.enganches-a.enganches);},[data]);
 return <AppShell title="Enganches"><main className="mx-auto max-w-7xl px-3 py-4 sm:px-4 sm:py-5"><section className="rounded-[26px] bg-[#12224A] p-4 text-white sm:p-7"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.14em] text-[#C79A3B]"><Banknote className="h-4 w-4"/>Corte de supervisión</div><h1 className="mt-2 text-xl font-black sm:text-2xl">Enganches del día</h1><p className="mt-2 max-w-2xl text-xs leading-5 text-slate-300 sm:text-sm">Control del efectivo recibido en ventas supervisadas y desglose por vendedora. Los importes provienen del motor financiero existente.</p></section>{error&&<div role="alert" className="mt-3 rounded-2xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}
 <section className="mt-3 grid grid-cols-2 gap-2 lg:grid-cols-4"><K I={WalletCards} l="Enganches" v={money.format(Number(totals.downPayments||0))}/><K I={Coins} l="A vendedoras" v={money.format(Number(totals.sellerCommissions||0))}/><K I={Banknote} l="Entrega admin" v={money.format(Number(totals.adminHandoffEstimate||0))}/><K I={CheckCircle2} l="Operaciones" v={data.length}/></section>
 <section className="mt-3 rounded-3xl border border-slate-200 bg-white p-3 sm:p-4"><div className="flex items-center justify-between gap-2"><div><h2 className="text-sm font-black text-[#12224A]">Desglose por vendedora</h2><p className="mt-1 text-[10px] text-slate-500">Enganche recibido → comisión calculada → entrega al administrador</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[9px] font-black text-slate-500">{sellers.length} VENDEDORA{ sellers.length===1?'':'S'}</span></div><div className="mt-3 space-y-2">{sellers.map(s=><div key={s.name} className="rounded-2xl bg-slate-50 p-3"><div className="flex items-center justify-between gap-2"><p className="min-w-0 truncate text-xs font-black text-[#12224A]">{s.name}</p><span className="shrink-0 text-[9px] font-bold text-slate-400">{s.count} op.</span></div><div className="mt-2 grid grid-cols-3 gap-1.5"><Mini l="Recibido" v={money.format(s.enganches)}/><Mini l="Vendedora" v={money.format(s.commission)}/><Mini l="Admin" v={money.format(s.admin)}/></div></div>)}{!sellers.length&&!loading&&<p className="py-5 text-center text-xs text-slate-400">Sin movimientos para desglosar.</p>}</div></section>
 <div className="mt-3 flex gap-2"><div className="relative min-w-0 flex-1"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cliente, venta o vendedora" className="min-h-12 w-full rounded-2xl border border-slate-200 bg-white pl-10 pr-3 text-sm outline-none focus:ring-2 focus:ring-[#FF6A00]"/></div><button onClick={()=>{haptic('tap');load();}} aria-label="Actualizar enganches" className="flex min-h-12 shrink-0 items-center gap-2 rounded-2xl border border-slate-200 bg-white px-3 text-xs font-black text-[#12224A] active:scale-95"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/><span className="hidden sm:inline">Actualizar</span></button></div>
 {loading?<div className="flex justify-center p-12"><Loader2 className="h-7 w-7 animate-spin text-[#12224A]"/></div>:<section className="mt-3 space-y-2">{filtered.map(x=><article key={x.id} className="rounded-3xl border border-slate-200 bg-white p-3 shadow-sm sm:p-4"><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-700"><UserRound className="h-5 w-5"/></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><h2 className="truncate text-sm font-black text-[#12224A]">{x.client?`${x.client.firstName||''} ${x.client.lastName||''}`.trim():'Cliente'}</h2><p className="mt-0.5 truncate text-[10px] text-slate-500">{x.saleNumber} · {x.client?.clientNumber||'Sin folio'}</p></div><p className="shrink-0 text-lg font-black text-emerald-700">{money.format(x.amount)}</p></div><div className="mt-2 grid grid-cols-3 gap-1.5"><Mini l="Vendedora" v={x.seller?`${x.seller.firstName||''} ${x.seller.lastName||''}`.trim()||x.seller.email||'Asignada':'Sin dato'}/><Mini l="Comisión" v={`${money.format(x.sellerCommission)}${x.sellerRate?` · ${(x.sellerRate*100).toFixed(1)}%`:''}`}/><Mini l="Entrega admin" v={money.format(x.adminHandoffEstimate)}/></div><p className="mt-2 text-[9px] text-slate-400">{new Date(x.createdAt).toLocaleString('es-MX')} · {String(x.paymentMethod).replaceAll('_',' ')} · {x.status}</p></div></div></article>)}{!filtered.length&&<div className="rounded-3xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-500">{query?'No encontramos movimientos con esa búsqueda.':'No hay enganches supervisados registrados hoy.'}</div>}</section>}
 <div className="mt-4 rounded-3xl border border-amber-200 bg-amber-50 p-3 text-[11px] leading-5 text-amber-900"><b>Importante:</b> “Entrega admin” es un desglose operativo del enganche menos la comisión calculada de la vendedora. No crea movimientos de caja, no registra una entrega física y no sustituye el cierre/arqueo oficial.</div></main></AppShell>
}
function K({I,l,v}:{I:any;l:string;v:any}){return <div className="min-w-0 rounded-2xl border border-slate-200 bg-white p-3 sm:rounded-3xl sm:p-4"><I className="h-4 w-4 text-[#C79A3B] sm:h-5 sm:w-5"/><p className="mt-2 text-[9px] font-black uppercase text-slate-400 sm:text-[10px]">{l}</p><p className="mt-1 truncate text-base font-black text-[#12224A] sm:text-lg">{v}</p></div>}
function Mini({l,v}:{l:string;v:string}){return <div className="min-w-0 rounded-xl bg-slate-50 p-2"><p className="truncate text-[8px] font-black uppercase text-slate-400">{l}</p><p className="mt-1 truncate text-[10px] font-black text-[#12224A]" title={v}>{v}</p></div>}
