'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowRightLeft,Boxes,Camera,CalendarClock,CheckCircle2,ClipboardList,Loader2,PackageCheck,PackagePlus,Search,ShoppingCart,Warehouse,X} from 'lucide-react';
import {useRouter} from 'next/navigation';
import AppShell,{useShellPermissions} from '@/components/phase15/AppShell';
import {apiClient,newIdempotencyKey} from '@/lib/phase15/apiClient';
import {haptic} from '@/lib/ux/haptics';

type Product={id:string;sku?:string;barcode?:string|null;name:string;status?:string;minStock?:number;maxStock?:number;reorderPoint?:number;images?:Array<{url?:string;isPrimary?:boolean;isMain?:boolean}>};
type WarehouseRow={id:string;name:string;code?:string;isActive?:boolean};
type Stock={quantityOnHand:number;quantityReserved:number;quantityAvailable:number;productId:string;warehouseId:string;warehouse?:WarehouseRow};
type ProductRow={product:Product;stocks:Stock[];physical:number;reserved:number;available:number};
const n=(v:any)=>Number(v||0);
const imageOf=(p:Product)=>p.images?.find(x=>x.isPrimary||x.isMain)?.url||p.images?.[0]?.url||'';

export default function InventoryPage(){
 const router=useRouter(),permissions=useShellPermissions(),canManage=!!permissions?.has('inventory.manage');
 const[products,setProducts]=useState<Product[]>([]),[stocks,setStocks]=useState<Stock[]>([]),[warehouses,setWarehouses]=useState<WarehouseRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState<'ALL'|'NO_STOCK'|'CRITICAL'|'OVERSTOCK'>('ALL'),[selected,setSelected]=useState<ProductRow|null>(null),[warehouseId,setWarehouseId]=useState(''),[quantity,setQuantity]=useState('1'),[reason,setReason]=useState('Entrada manual de mercancía'),[saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);setError('');try{const[a,b,c]:any[]=await Promise.all([apiClient('/api/products'),apiClient('/api/inventory'),apiClient('/api/warehouses')]);setProducts((a?.products||[]).filter((p:Product)=>p.status!=='DISCONTINUED'));setStocks(b?.inventory||[]);setWarehouses((c?.warehouses||[]).filter((w:WarehouseRow)=>w.isActive!==false));}catch(e:any){setError(e?.message||'No pudimos relacionar productos e inventario.');}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const rows=useMemo<ProductRow[]>(()=>products.map(product=>{const own=stocks.filter(stock=>stock.productId===product.id);return{product,stocks:own,physical:own.reduce((s,x)=>s+n(x.quantityOnHand),0),reserved:own.reduce((s,x)=>s+n(x.quantityReserved),0),available:own.reduce((s,x)=>s+n(x.quantityAvailable),0)}}),[products,stocks]);
 const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase('es-MX');return rows.filter(row=>{const text=`${row.product.name} ${row.product.sku||''} ${row.product.barcode||''} ${row.stocks.map(x=>x.warehouse?.name||'').join(' ')}`.toLocaleLowerCase('es-MX'),reorder=n(row.product.reorderPoint??row.product.minStock),max=row.product.maxStock==null?null:n(row.product.maxStock);return(!q||text.includes(q))&&(filter==='ALL'||filter==='NO_STOCK'&&row.physical===0||filter==='CRITICAL'&&row.available<=reorder||filter==='OVERSTOCK'&&max!==null&&row.available>max)}).sort((a,b)=>Number(b.physical===0)-Number(a.physical===0)||a.product.name.localeCompare(b.product.name,'es-MX'));},[rows,query,filter]);
 const totals=useMemo(()=>({physical:rows.reduce((s,x)=>s+x.physical,0),reserved:rows.reduce((s,x)=>s+x.reserved,0),available:rows.reduce((s,x)=>s+x.available,0),without:rows.filter(x=>x.physical===0).length,critical:rows.filter(x=>x.available<=n(x.product.reorderPoint??x.product.minStock)).length}),[rows]);
 const selectedStock=selected?.stocks.find(x=>x.warehouseId===warehouseId),currentAvailable=n(selectedStock?.quantityAvailable),nextAvailable=currentAvailable+n(quantity);
 const openAdd=(row:ProductRow)=>{haptic('tap');setSelected(row);setWarehouseId(row.stocks[0]?.warehouseId||warehouses[0]?.id||'');setQuantity('1');setReason(row.physical===0?'Existencia inicial':'Entrada manual de mercancía');setError('');setNotice('')};
 const close=()=>{if(!saving)setSelected(null)};
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!selected||!warehouseId)return setError('Selecciona un almacén.');const amount=Number(quantity);if(!Number.isInteger(amount)||amount<=0)return setError('La cantidad debe ser un entero mayor a cero.');if(!reason.trim())return setError('Explica el origen de la mercancía.');setSaving(true);setError('');try{const key=newIdempotencyKey('stock-in');await apiClient('/api/inventory/operations',{method:'POST',idempotencyKey:key,body:JSON.stringify({operation:'ADJUSTMENT_IN',warehouseId,productId:selected.product.id,quantity:amount,reason:reason.trim(),idempotencyKey:key})});setSelected(null);setNotice(`${amount} unidad(es) agregadas a ${selected.product.name}.`);haptic('success');await load()}catch(e:any){setError(e?.message||'No pudimos agregar la existencia.');haptic('error')}finally{setSaving(false)}};
 return <AppShell title="Inventario"><main className="mx-auto max-w-7xl px-3 py-3 sm:px-4 sm:py-5">
  <section className="rounded-[24px] bg-[var(--bitalis-primary)] p-4 text-white sm:rounded-[28px] sm:p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[var(--bitalis-mint)]">Catálogo + existencias</p><h1 className="mt-1 text-xl font-black sm:text-2xl">Inventario por producto</h1><p className="mt-1 max-w-xl text-xs leading-5 text-emerald-50/80 sm:text-sm">Todos los productos aparecen aunque todavía no tengan stock. Busca, selecciona y agrega disponibilidad al almacén correspondiente.</p></div>{canManage&&<button onClick={()=>router.push('/orders')} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-[var(--bitalis-action)] px-4 text-xs font-black text-white"><ShoppingCart className="h-4 w-4"/>CREAR COMPRA</button>}</div></section>
  {error&&!selected&&<Alert tone="error" text={error}/>} {notice&&<Alert tone="success" text={notice}/>}
  <section className="mt-3 grid grid-cols-2 gap-2 lg:grid-cols-5"><Kpi icon={<Boxes/>} label="Físico" value={totals.physical}/><Kpi icon={<PackageCheck/>} label="Disponible" value={totals.available}/><Kpi icon={<Warehouse/>} label="Reservado" value={totals.reserved}/><Kpi icon={<PackagePlus/>} label="Sin existencia" value={totals.without} warning={totals.without>0}/><Kpi icon={<AlertTriangle/>} label="Críticos" value={totals.critical} warning={totals.critical>0}/></section>
  {canManage&&<div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><Nav onClick={()=>router.push('/inventory/operations')} icon={<ClipboardList/>} label="MOVIMIENTOS"/><Nav onClick={()=>router.push('/inventory/counts')} icon={<ArrowRightLeft/>} label="CONTEOS"/><Nav onClick={()=>router.push('/inventory/lots')} icon={<CalendarClock/>} label="LOTES"/><Nav onClick={()=>router.push('/products')} icon={<PackagePlus/>} label="PRODUCTOS"/></div>}
  <div className="relative mt-3"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} autoComplete="off" placeholder="Nombre, SKU o código de barras" aria-label="Buscar productos en inventario" className="min-h-14 w-full rounded-2xl border border-slate-200 bg-white pl-12 pr-4 text-base outline-none focus:border-[var(--bitalis-action)] focus:ring-4 focus:ring-emerald-500/10"/></div>
  <div data-no-swipe className="mt-3 flex gap-2 overflow-x-auto pb-1"><Chip active={filter==='ALL'} onClick={()=>setFilter('ALL')} label={`Todos ${rows.length}`}/><Chip active={filter==='NO_STOCK'} onClick={()=>setFilter('NO_STOCK')} label={`Sin existencia ${totals.without}`}/><Chip active={filter==='CRITICAL'} onClick={()=>setFilter('CRITICAL')} label={`Críticos ${totals.critical}`}/><Chip active={filter==='OVERSTOCK'} onClick={()=>setFilter('OVERSTOCK')} label="Sobrestock"/></div>
  {loading?<div className="flex justify-center p-12"><Loader2 className="h-7 w-7 animate-spin text-[var(--bitalis-primary)]"/></div>:<section className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.map(row=><ProductCard key={row.product.id} row={row} canManage={canManage} onAdd={()=>openAdd(row)}/>)}{!filtered.length&&<div className="rounded-3xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500 md:col-span-2 xl:col-span-3">No encontramos productos con esa búsqueda.</div>}</section>}
  {selected&&<div data-no-swipe className="fixed inset-0 z-[180] flex items-end bg-slate-950/55 sm:items-center sm:justify-center sm:p-4" onClick={close}><form onSubmit={submit} onClick={e=>e.stopPropagation()} className="bitalis-bottom-sheet max-h-[92dvh] w-full overflow-y-auto p-4 pb-[max(1rem,env(safe-area-inset-bottom))] sm:max-w-lg sm:rounded-[28px] sm:p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-[10px] font-black uppercase tracking-[.14em] text-[var(--bitalis-action)]">Entrada de existencia</p><h2 className="mt-1 truncate text-xl font-black text-[var(--bitalis-primary)]">{selected.product.name}</h2><p className="mt-1 text-xs text-slate-500">{selected.product.sku||'Sin SKU'}{selected.product.barcode?` · ${selected.product.barcode}`:''}</p></div><button type="button" disabled={saving} onClick={close} className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-slate-100"><X className="h-5 w-5"/></button></div>{error&&<Alert tone="error" text={error}/>}<label className="mt-4 block"><span className="bitalis-form-label">Almacén o sucursal *</span><select required value={warehouseId} onChange={e=>setWarehouseId(e.target.value)} className="min-h-14 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 text-base"><option value="">Seleccionar almacén</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}{w.code?` · ${w.code}`:''}</option>)}</select></label><div className="mt-3 grid grid-cols-2 gap-2"><Metric label="Disponible actual" value={currentAvailable}/><Metric label="Quedará disponible" value={nextAvailable} strong/></div><label className="mt-3 block"><span className="bitalis-form-label">Cantidad que ingresa *</span><input required min="1" step="1" inputMode="numeric" type="number" value={quantity} onChange={e=>setQuantity(e.target.value)} className="min-h-14 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 text-xl font-black"/></label><label className="mt-3 block"><span className="bitalis-form-label">Origen o motivo *</span><textarea required rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ej. Compra recibida, existencia inicial o ajuste verificado" className="w-full rounded-2xl border border-slate-200 bg-slate-50 p-4"/></label><p className="mt-3 rounded-2xl bg-amber-50 p-3 text-xs leading-5 text-amber-800">La entrada quedará registrada en Kardex. No modifica unidades reservadas ni borra movimientos anteriores.</p><button disabled={saving||!warehouseId} className="mt-4 flex min-h-16 w-full items-center justify-center gap-2 rounded-2xl bg-[var(--bitalis-action)] px-4 text-base font-black text-white disabled:opacity-40">{saving?<Loader2 className="h-5 w-5 animate-spin"/>:<PackagePlus className="h-5 w-5"/>}{saving?'AGREGANDO…':`AGREGAR ${n(quantity)} DISPONIBLE`}</button></form></div>}
 </main></AppShell>;
}

function ProductCard({row,canManage,onAdd}:{row:ProductRow;canManage:boolean;onAdd:()=>void}){const p=row.product,image=imageOf(p),critical=row.available<=n(p.reorderPoint??p.minStock);return <article className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex gap-3 p-4">{image?<img src={image} alt={p.name} loading="lazy" className="h-16 w-16 shrink-0 rounded-2xl object-cover"/>:<div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl bg-slate-100"><Camera className="h-6 w-6 text-slate-300"/></div>}<div className="min-w-0 flex-1"><p className="truncate text-[10px] font-black uppercase text-slate-400">{p.sku||'SIN SKU'}{p.barcode?` · ${p.barcode}`:''}</p><h2 className="mt-1 line-clamp-2 text-base font-black leading-5 text-[var(--bitalis-primary)]">{p.name}</h2><span className={`mt-2 inline-flex rounded-full px-2 py-1 text-[9px] font-black ${row.physical===0?'bg-amber-50 text-amber-800':critical?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-700'}`}>{row.physical===0?'SIN EXISTENCIA':critical?'STOCK CRÍTICO':'DISPONIBLE'}</span></div></div><div className="grid grid-cols-3 border-y border-slate-100 bg-slate-50/70"><Metric label="Físico" value={row.physical}/><Metric label="Reservado" value={row.reserved}/><Metric label="Disponible" value={row.available} strong/></div><div className="p-3"><p className="mb-2 truncate text-[10px] text-slate-500">{row.stocks.length?row.stocks.map(x=>`${x.warehouse?.name||'Almacén'}: ${n(x.quantityAvailable)}`).join(' · '):'Aún no está relacionado con ningún almacén'}</p>{canManage&&<button onClick={onAdd} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-[var(--bitalis-primary)] px-3 text-xs font-black text-white"><PackagePlus className="h-4 w-4"/>{row.physical===0?'AGREGAR EXISTENCIA INICIAL':'AGREGAR DISPONIBLE'}</button>}</div></article>}
function Kpi({icon,label,value,warning}:{icon:React.ReactNode;label:string;value:number;warning?:boolean}){return <div className={`rounded-2xl border p-3 ${warning?'border-amber-200 bg-amber-50':'border-slate-200 bg-white'}`}><span className={warning?'text-amber-700':'text-[var(--bitalis-action)]'}>{icon}</span><p className="mt-2 text-[9px] font-black uppercase text-slate-400">{label}</p><p className={`mt-1 text-xl font-black ${warning?'text-amber-800':'text-[var(--bitalis-primary)]'}`}>{value.toLocaleString('es-MX')}</p></div>}
function Metric({label,value,strong}:{label:string;value:number;strong?:boolean}){return <div className="min-w-0 border-r border-slate-100 p-3 text-center last:border-r-0"><p className="text-[8px] font-black uppercase text-slate-400">{label}</p><p className={`mt-1 text-lg font-black ${strong?'text-emerald-700':'text-[var(--bitalis-primary)]'}`}>{value.toLocaleString('es-MX')}</p></div>}
function Chip({active,onClick,label}:{active:boolean;onClick:()=>void;label:string}){return <button onClick={onClick} className={`min-h-11 shrink-0 rounded-full px-4 text-xs font-black ${active?'bg-[var(--bitalis-primary)] text-white':'border border-slate-200 bg-white text-slate-600'}`}>{label}</button>}
function Nav({onClick,icon,label}:{onClick:()=>void;icon:React.ReactNode;label:string}){return <button onClick={onClick} className="flex min-h-12 items-center justify-center gap-1 rounded-2xl border border-slate-200 bg-white px-2 text-[9px] font-black text-[var(--bitalis-primary)]">{icon}{label}</button>}
function Alert({tone,text}:{tone:'error'|'success';text:string}){return <div className={`mt-3 flex gap-2 rounded-2xl border p-3 text-sm font-bold ${tone==='error'?'border-red-200 bg-red-50 text-red-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{tone==='success'?<CheckCircle2 className="h-5 w-5 shrink-0"/>:<AlertTriangle className="h-5 w-5 shrink-0"/>}{text}</div>}
