'use client';

import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {Bell,CloudUpload,Database,KeyRound,LockKeyhole,Settings,ShieldCheck,Smartphone} from 'lucide-react';
import AppShell from '@/components/phase15/AppShell';

export default function SettingsPage(){const router=useRouter();const[user,setUser]=useState<any>(null),[installable,setInstallable]=useState(false);useEffect(()=>{try{const raw=localStorage.getItem('bitalis_auth_user');if(raw)setUser(JSON.parse(raw));}catch{}const standalone=window.matchMedia('(display-mode: standalone)').matches;setInstallable(!standalone);},[]);return <AppShell title="Configuración"><div className="mx-auto max-w-5xl px-4 py-5"><section className="rounded-[28px] bg-[#12224A] p-5 text-white"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.14em] text-[#C79A3B]"><Settings className="h-4 w-4"/>Producción</div><h1 className="mt-3 text-2xl font-black">Configuración</h1><p className="mt-2 text-sm text-slate-300">Preferencias de experiencia, seguridad y estado PWA.</p></section><div className="mt-5 grid gap-3 sm:grid-cols-2"><Card I={ShieldCheck} title="Sesión" text={`${user?.email||'Usuario'} · ${user?.role||'Rol no disponible'}`}/><Card I={Database} title="Backend" text="MySQL + Prisma. El servidor permanece como autoridad financiera."/><Card I={LockKeyhole} title="Seguridad" text="Las acciones sensibles siguen validadas en backend por permisos y contexto de usuario."/><Card I={Smartphone} title="PWA" text={installable?'Disponible para instalar desde el navegador compatible.':'BITALIS se está ejecutando como aplicación instalada.'}/><button onClick={()=>router.push('/sync')} className="rounded-3xl border border-orange-200 bg-orange-50 p-5 text-left shadow-sm"><CloudUpload className="h-5 w-5 text-[#FF6A00]"/><h2 className="mt-3 font-black text-[#12224A]">Sincronización offline</h2><p className="mt-2 text-sm leading-6 text-slate-600">Revisa operaciones pendientes, errores de sincronización e inténtalas enviar nuevamente.</p></button><Card I={Bell} title="Notificaciones" text="Centro de alertas disponible. Web Push se habilita cuando el navegador y la configuración del servidor lo permiten."/><Card I={KeyRound} title="Credenciales" text="Las contraseñas y secretos nunca se muestran ni almacenan desde esta pantalla."/></div><div className="mt-5 rounded-3xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900"><b>Mejora de seguridad pendiente de migración:</b> la aplicación histórica todavía usa token de acceso en almacenamiento del navegador. La Fase 15 deja documentada la migración recomendada a cookies HttpOnly/SameSite sin romper el login productivo actual.</div></div></AppShell>}
function Card({I,title,text}:{I:any;title:string;text:string}){return <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><I className="h-5 w-5 text-[#C79A3B]"/><h2 className="mt-3 font-black text-[#12224A]">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></article>}
