'use client';

import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,Boxes,ChartNoAxesCombined,Loader2,ReceiptText,ShieldAlert,Users,WalletCards,Sparkles,Route,Clock3,ChevronRight} from 'lucide-react';
import {useRouter} from 'next/navigation';
import AppShell from '@/components/phase15/AppShell';
import {apiClient} from '@/lib/phase15/apiClient';
import {haptic} from '@/lib/ux/haptics';

const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0});
const riskWeight:Record<string,number>={CRITICAL:4,HIGH:3,MEDIUM:2,LOW:1};

export default function ControlCenterPage(){
 const router=useRouter();
 const[data,setData]=useState<any>({}),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const [clients,sales,portfolio,inventory,notifications]=await Promise.allSettled([apiClient('/api/clients?page=1&limit=100'),apiClient('/api/sales'),apiClient('/api/collections/portfolio?scope=all'),apiClient('/api/inventory'),apiClient('/api/notifications')]);setData({clients:clients.status==='fulfilled'?clients.value:null,sales:sales.status==='fulfilled'?sales.value:null,portfolio:portfolio.status==='fulfilled'?portfolio.value:null,inventory:inventory.status==='fulfilled'?inventory.value:null,notifications:notifications.status==='fulfilled'?notifications.value:null});}catch(e:any){setError(e.message);}finally{setLoading(false);}})();},[]);
 const clients=Array.isArray(data.clients?.data)?data.clients.data:Array.isArray(data.clients?.clients)?data.clients.clients:[];
 const sales=Array.isArray(data.sales?.data)?data.sales.data:Array.isArray(data.sales?.sales)?data.sales.sales:[];
 const portfolio=Array.isArray(data.portfolio?.data)?data.portfolio.data:[];
 const inv=Array.isArray(data.inventory?.data)?data.inventory.data:Array.isArray(data.inventory?.inventory)?data.inventory.inventory:[];
 const alerts=Array.isArray(data.notifications?.data)?data.notifications.data:Array.isArray(data.notifications?.notifications)?data.notifications.notifications:[];
 const cartera=portfolio.reduce((s:number,x:any)=>s+Number(x.saldoActual||0),0);
 const critical=portfolio.filter((x:any)=>['HIGH','CRITICAL'].includes(String(x.client?.riskLevel||''))).length;
 const overdue=portfolio.filter((x:any)=>x.collection?.overdue).length;
 const promises=portfolio.filter((x:any)=>x.collection?.latestRescheduleDate).length;
 const approved=sales.filter((x:any)=>['APPROVED','COMPLETED'].includes(String(x.status)));
 const sold=approved.reduce((s:number,x:any)=>s+Number(x.totalAmount||0),0);
 const priority=useMemo(()=>[...portfolio].map((x:any)=>{const risk=String(x.client?.riskLevel||'LOW');const score=(riskWeight[risk]||1)*20+(x.collection?.overdue?35:0)+(x.collection?.latestRescheduleDate?15:0)+Math.min(20,Math.round(Number(x.saldoActual||0)/500));return{...x,_score:score};}).sort((a:any,b:any)=>b._score-a._score),[portfolio]);
 const situations=useMemo(()=>{const a:{level:'red'|'amber'|'green';title:string;detail:string;path:string}[]=[];if(critical)a.push({level:'red',title:`${critical} cliente${critical===1?'':'s'} en riesgo alto`,detail:'Prioriza revisión y cobranza antes de que aumente la mora.',path:'/portfolio'});if(overdue)a.push({level:'red',title:`${overdue} crédito${overdue===1?'':'s'} vencido${overdue===1?'':'s'}`,detail:'La cartera vencida requiere intervención hoy.',path:'/portfolio'});if(promises)a.push({level:'amber',title:`${promises} promesa${promises===1?'':'s'} de pago activa${promises===1?'':'s'}`,detail:'Verifica cumplimiento y reagenda sólo con evidencia.',path:'/portfolio'});if(alerts.length)a.push({level:'amber',title:`${alerts.length} alerta${alerts.length===1?'':'s'} operativa${alerts.length===1?'':'s'}`,detail:'Revisa incidencias y excepciones pendientes.',path:'/notifications'});if(!a.length)a.push({level:'green',title:'Operación estable',detail:'No hay excepciones críticas detectadas en este momento.',path:'/dashboard'});return a.slice(0,4);},[critical,overdue,promises,alerts.length]);
 const go=(path:string)=>{haptic('tap');router.push(path)};
 return <AppShell title="Centro de mando"><div className="mx-auto max-w-7xl px-3 py-3 sm:px-4 sm:py-5">
  <section className="overflow-hidden rounded-[28px] bg-[var(--bitalis-primary)] p-4 text-white shadow-lg shadow-emerald-950/10 sm:p-6"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.14em] text-[var(--bitalis-mint)]"><Sparkles className="h-4 w-4"/>BITALIS Intelligence</div><h1 className="mt-2 text-2xl font-black sm:text-3xl">Centro de mando</h1><p className="mt-1 max-w-2xl text-xs leading-5 text-emerald-50/80 sm:text-sm">Excepciones, cartera y siguiente mejor acción para dirigir la operación sin revisar pantalla por pantalla.</p></div><ChartNoAxesCombined className="h-6 w-6 shrink-0 text-[var(--bitalis-mint)]"/></div></section>
  {error&&<div className="mt-3 rounded-2xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}
  {loading?<div className="flex justify-center p-16"><Loader2 className="h-7 w-7 animate-spin text-[var(--bitalis-primary)]"/></div>:<>
   <section className="mt-3 grid grid-cols-2 gap-2 sm:mt-5 lg:grid-cols-6">{[[Users,'Clientes',clients.length],[ReceiptText,'Ventas',approved.length],[WalletCards,'Cartera',money.format(cartera)],[ShieldAlert,'Riesgo alto',critical],[Clock3,'Vencidos',overdue],[AlertTriangle,'Alertas',alerts.length]].map(([Icon,label,value]:any)=><div key={label} className="rounded-2xl border border-[var(--bitalis-border)] bg-white p-3 shadow-sm"><Icon className="h-4 w-4 text-[var(--bitalis-action)]"/><p className="mt-2 text-[9px] font-black uppercase tracking-[.1em] text-slate-400">{label}</p><p className="mt-1 break-words text-base font-black text-[var(--bitalis-primary)]">{value}</p></div>)}</section>
   <section className="mt-4 grid gap-3 lg:grid-cols-[1.1fr_.9fr]">
    <article className="rounded-[24px] border border-[var(--bitalis-border)] bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.12em] text-[var(--bitalis-action)]">Atención requerida</p><h2 className="mt-1 text-lg font-black text-[var(--bitalis-primary)]">Excepciones de hoy</h2></div><ShieldAlert className="h-5 w-5 text-[var(--bitalis-action)]"/></div><div className="mt-3 space-y-2">{situations.map((x,i)=><button key={i} onClick={()=>go(x.path)} className="flex min-h-16 w-full items-center gap-3 rounded-2xl bg-slate-50 p-3 text-left active:scale-[.99]"><span className={`h-3 w-3 shrink-0 rounded-full ${x.level==='red'?'bg-red-500':x.level==='amber'?'bg-amber-400':'bg-emerald-500'}`}/><span className="min-w-0 flex-1"><b className="block text-sm text-[var(--bitalis-primary)]">{x.title}</b><span className="mt-0.5 block text-[11px] leading-4 text-slate-500">{x.detail}</span></span><ChevronRight className="h-4 w-4 shrink-0 text-slate-300"/></button>)}</div></article>
    <article className="rounded-[24px] border border-[var(--bitalis-border)] bg-white p-4 shadow-sm"><div className="flex items-center gap-2"><Route className="h-5 w-5 text-[var(--bitalis-action)]"/><div><p className="text-[10px] font-black uppercase tracking-[.12em] text-[var(--bitalis-action)]">Siguiente mejor acción</p><h2 className="text-lg font-black text-[var(--bitalis-primary)]">Prioridad de cobranza</h2></div></div>{priority.slice(0,5).map((x:any,i:number)=><button key={x.id||i} onClick={()=>go(`/collections?credit=${x.id}`)} className="mt-2 flex min-h-14 w-full items-center gap-3 rounded-2xl bg-slate-50 p-3 text-left"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-[var(--bitalis-primary)] text-xs font-black text-white">{i+1}</span><span className="min-w-0 flex-1"><b className="block truncate text-sm text-[var(--bitalis-primary)]">{x.client?.firstName} {x.client?.lastName}</b><span className="block text-[10px] text-slate-500">Score {x._score} · {x.client?.riskLevel||'LOW'}</span></span><b className="text-xs text-[var(--bitalis-primary)]">{money.format(Number(x.saldoActual||0))}</b></button>)}{!priority.length&&<p className="mt-4 text-sm text-slate-500">Sin cartera activa.</p>}</article>
   </section>
   <section className="mt-3 grid gap-3 lg:grid-cols-2"><article className="rounded-[24px] border border-[var(--bitalis-border)] bg-white p-4"><h2 className="font-black text-[var(--bitalis-primary)]">Pulso comercial</h2><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-2xl bg-slate-50 p-3"><p className="text-[9px] font-black uppercase text-slate-400">Monto vendido</p><b className="mt-1 block text-lg text-[var(--bitalis-primary)]">{money.format(sold)}</b></div><div className="rounded-2xl bg-slate-50 p-3"><p className="text-[9px] font-black uppercase text-slate-400">Promesas activas</p><b className="mt-1 block text-lg text-[var(--bitalis-primary)]">{promises}</b></div></div></article><article className="rounded-[24px] border border-[var(--bitalis-border)] bg-white p-4"><div className="flex items-center gap-2"><Boxes className="h-5 w-5 text-[var(--bitalis-action)]"/><h2 className="font-black text-[var(--bitalis-primary)]">Stock a vigilar</h2></div><div className="mt-3 space-y-2">{inv.slice(0,4).map((x:any,i:number)=><div key={x.id||i} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><span className="truncate text-sm font-bold">{x.product?.name||x.name||x.sku||'Producto'}</span><b className="ml-3 text-sm">{x.availableQuantity??x.available??x.quantity??0}</b></div>)}{!inv.length&&<p className="text-sm text-slate-500">Sin datos de stock.</p>}</div></article></section>
  </>}
 </div></AppShell>;
}