'use client';

import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {AlertTriangle,Banknote,CheckCircle2,ClipboardCheck,Loader2,ReceiptText,RefreshCw,WalletCards} from 'lucide-react';
import AppShell from '@/components/phase15/AppShell';
import {apiClient} from '@/lib/phase15/apiClient';

type User={id:string;role:string};
type Movement={id?:string;type?:string;amount?:number|string;description?:string;reference?:string;createdAt?:string};
type CashSession={id:string;status:string;openingFund?:number|string;currentCash?:number|string;expectedCash?:number|string;countedCash?:number|string|null;varianceAmount?:number|string|null;openedAt?:string;closedAt?:string|null;movements?:Movement[];payments?:any[];expenses?:any[]};
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'});
const n=(v:any)=>Number.isFinite(Number(v))?Number(v):0;

export default function CashPage(){
  const router=useRouter();
  const[user,setUser]=useState<User|null>(null),[session,setSession]=useState<CashSession|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=async()=>{const raw=localStorage.getItem('bitalis_auth_user');if(!raw){router.replace('/');return;}let u:User;try{u=JSON.parse(raw);setUser(u);}catch{router.replace('/');return;}setLoading(true);setError('');try{const j:any=await apiClient(`/api/cash-sessions/current?userId=${encodeURIComponent(u.id)}`);setSession(j?.data?.session||j?.data||j?.session||null);}catch(e:any){setError(e.message||'No pudimos cargar tu caja.');}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const summary=useMemo(()=>{const movements=session?.movements||[];const sum=(types:string[])=>movements.filter(m=>types.includes(String(m.type||''))).reduce((a,m)=>a+n(m.amount),0);return{payments:sum(['PAYMENT']),downPayments:sum(['DOWN_PAYMENT']),expenses:sum(['EXPENSE']),withdrawals:sum(['WITHDRAWAL']),refunds:sum(['REFUND'])};},[session]);
  const expected=n(session?.expectedCash),counted=session?.countedCash==null?null:n(session?.countedCash),variance=session?.varianceAmount==null?(counted==null?null:counted-expected):n(session?.varianceAmount);const squared=variance!=null&&Math.abs(variance)<0.01;
  return <AppShell title="Caja"><div className="mx-auto max-w-6xl px-4 py-5">
    <section className="rounded-[28px] bg-[#12224A] p-5 text-white"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#C79A3B]">Control de efectivo</p><h1 className="mt-2 text-2xl font-black">Caja</h1><p className="mt-2 text-sm text-slate-300">Apertura, movimientos, arqueo y cierre sin editar operaciones históricas.</p></div><button onClick={load} className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white/10" aria-label="Actualizar caja"><RefreshCw className={`h-5 w-5 ${loading?'animate-spin':''}`}/></button></div></section>
    {error&&<div className="mt-4 flex items-center gap-2 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700"><AlertTriangle className="h-5 w-5"/>{error}</div>}
    {loading?<div className="flex justify-center p-14"><Loader2 className="h-7 w-7 animate-spin text-[#12224A]"/></div>:!session?<section className="mt-4 rounded-[28px] border border-slate-200 bg-white p-6 text-center"><Banknote className="mx-auto h-9 w-9 text-[#C79A3B]"/><h2 className="mt-3 text-lg font-black text-[#12224A]">No hay caja activa</h2><p className="mt-2 text-sm text-slate-500">La caja se abre desde el flujo de ruta cuando el cobrador inicia su jornada.</p><button onClick={()=>router.push('/route')} className="mt-5 min-h-12 w-full rounded-2xl bg-[#FF6A00] px-4 text-sm font-black text-white">IR A RUTA Y ABRIR CAJA</button></section>:<>
      <section className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4"><K label="Fondo inicial" value={money.format(n(session.openingFund))} icon={WalletCards}/><K label="Cobros" value={money.format(summary.payments)} icon={Banknote}/><K label="Esperado" value={money.format(expected)} icon={ReceiptText}/><K label="Estado" value={String(session.status||'OPEN')} icon={ClipboardCheck}/></section>
      <section className="mt-4 rounded-[28px] border border-slate-200 bg-white p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.12em] text-slate-400">Resumen de movimientos</p><h2 className="mt-1 text-lg font-black text-[#12224A]">Caja de la jornada</h2></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-[10px] font-black text-slate-600">{session.status}</span></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-5">{[['Enganches',summary.downPayments],['Gastos',summary.expenses],['Retiros',summary.withdrawals],['Reembolsos',summary.refunds],['Actual',n(session.currentCash)]].map(([l,v]:any)=><div key={l} className="rounded-2xl bg-slate-50 p-3"><p className="text-[9px] font-black uppercase text-slate-400">{l}</p><p className="mt-1 text-sm font-black text-[#12224A]">{money.format(v)}</p></div>)}</div></section>
      <section className={`mt-4 rounded-[28px] border p-5 ${variance==null?'border-slate-200 bg-white':squared?'border-emerald-200 bg-emerald-50':'border-red-200 bg-red-50'}`}><div className="flex items-center gap-3">{variance==null?<ClipboardCheck className="h-7 w-7 text-[#C79A3B]"/>:squared?<CheckCircle2 className="h-7 w-7 text-emerald-600"/>:<AlertTriangle className="h-7 w-7 text-red-600"/>}<div><p className="text-[10px] font-black uppercase tracking-[.12em] text-slate-500">Arqueo</p><h2 className={`text-xl font-black ${variance==null?'text-[#12224A]':squared?'text-emerald-700':'text-red-700'}`}>{variance==null?'Pendiente de conteo':squared?'CUADRADO':'DIFERENCIA'}</h2></div></div>{counted!=null&&<div className="mt-4 grid grid-cols-3 gap-2"><div><p className="text-[9px] uppercase text-slate-400">Esperado</p><p className="font-black">{money.format(expected)}</p></div><div><p className="text-[9px] uppercase text-slate-400">Contado</p><p className="font-black">{money.format(counted)}</p></div><div><p className="text-[9px] uppercase text-slate-400">Diferencia</p><p className="font-black">{money.format(variance||0)}</p></div></div>}<button onClick={()=>router.push('/route/close')} disabled={['CLOSED','CANCELLED'].includes(String(session.status))} className="mt-5 min-h-12 w-full rounded-2xl bg-[#12224A] px-4 text-sm font-black text-white disabled:opacity-40">{['CLOSED','CANCELLED'].includes(String(session.status))?'CAJA CERRADA':'HACER ARQUEO / CERRAR CAJA'}</button></section>
      <section className="mt-4 overflow-hidden rounded-[28px] border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="font-black text-[#12224A]">Movimientos recientes</h2></div><div className="divide-y divide-slate-100">{(session.movements||[]).slice(0,12).map((m,i)=><div key={m.id||i} className="flex items-center justify-between gap-3 p-4"><div><p className="text-sm font-black text-[#12224A]">{String(m.type||'MOVIMIENTO').replaceAll('_',' ')}</p><p className="mt-1 text-[10px] text-slate-400">{m.description||m.reference||'Operación de caja'}{m.createdAt?` · ${new Date(m.createdAt).toLocaleString('es-MX')}`:''}</p></div><p className="shrink-0 text-sm font-black text-[#12224A]">{money.format(n(m.amount))}</p></div>)}{!(session.movements||[]).length&&<div className="p-8 text-center text-sm text-slate-500">Sin movimientos todavía.</div>}</div></section>
    </>}
  </div></AppShell>;
}
function K({label,value,icon:Icon}:{label:string;value:string;icon:any}){return <div className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><Icon className="h-5 w-5 text-[#C79A3B]"/><p className="mt-3 text-[9px] font-black uppercase tracking-[.1em] text-slate-400">{label}</p><p className="mt-1 break-words text-lg font-black text-[#12224A]">{value}</p></div>}
