'use client';

import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {AlertTriangle,Banknote,CheckCircle2,ClipboardCheck,Loader2,Navigation,ReceiptText,RefreshCw,Signal,SignalZero,WalletCards} from 'lucide-react';
import AppShell from '@/components/phase15/AppShell';
import {apiClient} from '@/lib/phase15/apiClient';
import {haptic} from '@/lib/ux/haptics';

type User={id:string;role:string};
type Movement={id?:string;type?:string;amount?:number|string;description?:string;reference?:string;createdAt?:string};
type CashSession={id:string;status:string;openingFund?:number|string;currentCash?:number|string;expectedCash?:number|string;countedCash?:number|string|null;varianceAmount?:number|string|null;openedAt?:string;closedAt?:string|null;movements?:Movement[];payments?:any[];expenses?:any[]};
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'});
const n=(v:any)=>Number.isFinite(Number(v))?Number(v):0;

export default function CashPage(){
  const router=useRouter();
  const[user,setUser]=useState<User|null>(null),[session,setSession]=useState<CashSession|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[online,setOnline]=useState(true);
  const load=async()=>{const raw=localStorage.getItem('bitalis_auth_user');if(!raw){router.replace('/');return;}let u:User;try{u=JSON.parse(raw);setUser(u);}catch{router.replace('/');return;}setLoading(true);setError('');try{const j:any=await apiClient(`/api/cash-sessions/current?userId=${encodeURIComponent(u.id)}`);setSession(j?.data?.session||j?.data||j?.session||null);}catch(e:any){setError(e.message||'No pudimos cargar tu caja.');}finally{setLoading(false);}};
  useEffect(()=>{void load();setOnline(navigator.onLine);const sync=()=>setOnline(navigator.onLine);window.addEventListener('online',sync);window.addEventListener('offline',sync);return()=>{window.removeEventListener('online',sync);window.removeEventListener('offline',sync)};},[]);
  const summary=useMemo(()=>{const movements=session?.movements||[];const sum=(types:string[])=>movements.filter(m=>types.includes(String(m.type||''))).reduce((a,m)=>a+n(m.amount),0);return{payments:sum(['PAYMENT']),downPayments:sum(['DOWN_PAYMENT']),expenses:sum(['EXPENSE']),withdrawals:sum(['WITHDRAWAL']),refunds:sum(['REFUND'])};},[session]);
  const expected=n(session?.expectedCash),counted=session?.countedCash==null?null:n(session?.countedCash),variance=session?.varianceAmount==null?(counted==null?null:counted-expected):n(session?.varianceAmount);const squared=variance!=null&&Math.abs(variance)<0.01;
  return <AppShell title="Caja"><div className="mx-auto max-w-6xl px-3 py-3 sm:px-4 sm:py-5">
    <section className="rounded-[28px] bg-[var(--bitalis-primary)] p-4 text-white shadow-[0_18px_45px_-28px_rgba(6,43,36,.9)] sm:p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[var(--bitalis-mint)]">Cierre seguro de jornada</p><h1 className="mt-1 text-2xl font-black">Caja del cobrador</h1><p className="mt-1 text-xs text-emerald-50/75 sm:text-sm">Efectivo recibido, movimientos y arqueo en un solo lugar.</p></div><button onClick={()=>{haptic('tap');void load()}} className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/10 active:scale-95" aria-label="Actualizar caja"><RefreshCw className={`h-5 w-5 ${loading?'animate-spin':''}`}/></button></div><div className={`mt-3 flex items-center gap-2 rounded-2xl px-3 py-2 text-[10px] font-black ${online?'bg-emerald-400/15 text-emerald-100':'bg-amber-400/15 text-amber-100'}`}>{online?<Signal className="h-4 w-4"/>:<SignalZero className="h-4 w-4"/>}{online?'CAJA CONECTADA':'SIN CONEXIÓN · CONSERVA TU CONTEO'}</div></section>
    {error&&<div className="mt-3 flex items-center gap-2 rounded-2xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700 sm:mt-4 sm:p-4"><AlertTriangle className="h-5 w-5"/>{error}</div>}
    {loading?<div className="flex justify-center p-10 sm:p-14"><Loader2 className="h-7 w-7 animate-spin text-[var(--bitalis-primary)]"/></div>:!session?<section className="mt-3 rounded-[28px] border border-slate-200 bg-white p-6 text-center"><Banknote className="mx-auto h-9 w-9 text-[var(--bitalis-action)]"/><h2 className="mt-2 text-lg font-black text-[var(--bitalis-primary)]">Aún no inicias tu jornada</h2><p className="mt-1 text-sm text-slate-500">Abre la ruta para registrar el fondo inicial y comenzar a cobrar.</p><button onClick={()=>{haptic('tap');router.push('/route')}} className="mt-5 flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-[var(--bitalis-action)] px-4 text-sm font-black text-white active:scale-[.99]"><Navigation className="h-5 w-5"/>ABRIR RUTA Y CAJA</button></section>:<>
      <section className="mt-3 grid grid-cols-2 gap-2 sm:mt-4 sm:gap-3 lg:grid-cols-4"><K label="Fondo inicial" value={money.format(n(session.openingFund))} icon={WalletCards}/><K label="Cobros" value={money.format(summary.payments)} icon={Banknote}/><K label="Efectivo esperado" value={money.format(expected)} icon={ReceiptText}/><K label="Estado" value={String(session.status||'OPEN')==='OPEN'?'ABIERTA':String(session.status||'')} icon={ClipboardCheck}/></section>
      <section className="mt-3 rounded-[24px] border border-slate-200 bg-white p-4 sm:mt-4 sm:rounded-[28px] sm:p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.12em] text-slate-400 sm:text-[10px]">Resumen</p><h2 className="mt-1 text-base font-black text-[#12224A] sm:text-lg">Caja de la jornada</h2></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[9px] font-black text-slate-600 sm:px-3 sm:py-1.5 sm:text-[10px]">{session.status}</span></div><div className="mt-3 grid grid-cols-2 gap-2 sm:mt-4 sm:grid-cols-5">{[['Enganches',summary.downPayments],['Gastos',summary.expenses],['Retiros',summary.withdrawals],['Reembolsos',summary.refunds],['Actual',n(session.currentCash)]].map(([l,v]:any)=><div key={l} className="rounded-xl bg-slate-50 p-2.5 sm:rounded-2xl sm:p-3"><p className="text-[9px] font-black uppercase text-slate-400">{l}</p><p className="mt-1 text-sm font-black text-[#12224A]">{money.format(v)}</p></div>)}</div></section>
      <section className={`mt-3 rounded-[24px] border p-4 sm:mt-4 sm:rounded-[28px] sm:p-5 ${variance==null?'border-slate-200 bg-white':squared?'border-emerald-200 bg-emerald-50':'border-red-200 bg-red-50'}`}><div className="flex items-center gap-3">{variance==null?<ClipboardCheck className="h-6 w-6 text-[#C79A3B] sm:h-7 sm:w-7"/>:squared?<CheckCircle2 className="h-6 w-6 text-emerald-600 sm:h-7 sm:w-7"/>:<AlertTriangle className="h-6 w-6 text-red-600 sm:h-7 sm:w-7"/>}<div><p className="text-[9px] font-black uppercase tracking-[.12em] text-slate-500 sm:text-[10px]">Arqueo</p><h2 className={`text-lg font-black sm:text-xl ${variance==null?'text-[#12224A]':squared?'text-emerald-700':'text-red-700'}`}>{variance==null?'Pendiente de conteo':squared?'CUADRADO':'DIFERENCIA'}</h2></div></div>{counted!=null&&<div className="mt-3 grid grid-cols-3 gap-2 sm:mt-4"><div><p className="text-[9px] uppercase text-slate-400">Esperado</p><p className="text-sm font-black sm:text-base">{money.format(expected)}</p></div><div><p className="text-[9px] uppercase text-slate-400">Contado</p><p className="text-sm font-black sm:text-base">{money.format(counted)}</p></div><div><p className="text-[9px] uppercase text-slate-400">Diferencia</p><p className="text-sm font-black sm:text-base">{money.format(variance||0)}</p></div></div>}<button onClick={()=>router.push('/route/close')} disabled={['CLOSED','CANCELLED'].includes(String(session.status))} className="mt-4 min-h-12 w-full rounded-2xl bg-[#12224A] px-4 text-sm font-black text-white disabled:opacity-40 sm:mt-5">{['CLOSED','CANCELLED'].includes(String(session.status))?'CAJA CERRADA':'HACER ARQUEO / CERRAR CAJA'}</button></section>
      <button onClick={()=>{haptic('tap');router.push('/route')}} className="mt-3 flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 text-sm font-black text-[var(--bitalis-primary)] active:scale-[.99]"><Navigation className="h-5 w-5"/>CONTINUAR RUTA</button><section className="mt-3 overflow-hidden rounded-[28px] border border-slate-200 bg-white"><div className="border-b border-slate-100 p-4 sm:p-5"><h2 className="font-black text-[var(--bitalis-primary)]">Movimientos recientes</h2><p className="mt-1 text-xs text-slate-400">Últimas operaciones registradas en esta caja.</p></div><div className="divide-y divide-slate-100">{(session.movements||[]).slice(0,12).map((m,i)=><div key={m.id||i} className="flex items-center justify-between gap-3 p-3 sm:p-4"><div className="min-w-0"><p className="truncate text-sm font-black text-[var(--bitalis-primary)]">{String(m.type||'MOVIMIENTO').replaceAll('_',' ')}</p><p className="mt-1 truncate text-[10px] text-slate-400">{m.description||m.reference||'Operación de caja'}{m.createdAt?` · ${new Date(m.createdAt).toLocaleString('es-MX')}`:''}</p></div><p className="shrink-0 text-sm font-black text-[var(--bitalis-primary)]">{money.format(n(m.amount))}</p></div>)}{!(session.movements||[]).length&&<div className="p-8 text-center text-sm text-slate-500">Aún no hay cobros ni movimientos.</div>}</div></section>
    </>}
  </div></AppShell>;
}
function K({label,value,icon:Icon}:{label:string;value:string;icon:any}){return <div className="rounded-3xl border border-slate-200 bg-white p-3 shadow-sm sm:p-4"><Icon className="h-5 w-5 text-[var(--bitalis-action)]"/><p className="mt-2 text-[9px] font-black uppercase tracking-[.1em] text-slate-400 sm:mt-3">{label}</p><p className="mt-1 break-words text-base font-black text-[var(--bitalis-primary)] sm:text-lg">{value}</p></div>}
