'use client';

import {useEffect,useMemo,useState} from 'react';
import {Boxes,Loader2,Package,Search,Tag,Plus,Pencil,Trash2,X,Save,AlertTriangle} from 'lucide-react';
import AppShell,{useShellPermissions} from '@/components/phase15/AppShell';
import {apiClient} from '@/lib/phase15/apiClient';

type Price={priceType?:string;amount?:number|string;price?:number|string;isActive?:boolean};
type Stock={quantityOnHand?:number;quantityReserved?:number;quantityAvailable?:number};
type Product={id:string;sku:string;barcode?:string|null;name:string;description?:string|null;brand?:string|null;status?:string;costPrice?:number|string;minStock?:number;reorderPoint?:number;maxStock?:number;prices?:Price[];stocks?:Stock[];images?:Array<{url?:string;isPrimary?:boolean;isMain?:boolean}>};
type FormState={sku:string;barcode:string;name:string;description:string;brand:string;costPrice:string;listPrice:string;minimumPrice:string;minStock:string;reorderPoint:string;maxStock:string;status:string};
const emptyForm:FormState={sku:'',barcode:'',name:'',description:'',brand:'',costPrice:'0',listPrice:'0',minimumPrice:'0',minStock:'0',reorderPoint:'0',maxStock:'100',status:'ACTIVE'};
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'});const n=(v:any)=>Number(v||0);
function priceOf(p:Product,type:string){const x=(p.prices||[]).find(x=>x.priceType===type&&x.isActive!==false);return x?n(x.amount??x.price):0;}
function imageOf(p:Product){const imgs=p.images||[];return imgs.find(x=>x.isPrimary||x.isMain)?.url||imgs[0]?.url||null;}

export default function ProductsPage(){
 const permissions=useShellPermissions();const canManage=!!permissions?.has('inventory.manage');
 const[products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[modalOpen,setModalOpen]=useState(false),[editing,setEditing]=useState<Product|null>(null),[form,setForm]=useState<FormState>(emptyForm),[saving,setSaving]=useState(false),[deletingId,setDeletingId]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const j:any=await apiClient('/api/products');setProducts(Array.isArray(j?.products)?j.products:[]);}catch(e:any){setError(e?.message||'No pudimos consultar los productos.');}finally{setLoading(false);}};useEffect(()=>{void load();},[]);
 const filtered=useMemo(()=>products.filter(p=>`${p.sku||''} ${p.name||''} ${p.description||''} ${p.brand||''}`.toLowerCase().includes(query.toLowerCase())),[products,query]);const active=products.filter(p=>p.status!=='INACTIVE'&&p.status!=='DISCONTINUED').length;
 const openNew=()=>{setEditing(null);setForm(emptyForm);setError('');setModalOpen(true);};
 const openEdit=(p:Product)=>{setEditing(p);setForm({sku:p.sku||'',barcode:p.barcode||'',name:p.name||'',description:p.description||'',brand:p.brand||'',costPrice:String(n(p.costPrice)),listPrice:String(priceOf(p,'LIST')||priceOf(p,'LIST_PRICE')),minimumPrice:String(priceOf(p,'MINIMUM_AUTHORIZED')),minStock:String(p.minStock??0),reorderPoint:String(p.reorderPoint??0),maxStock:String(p.maxStock??100),status:p.status||'ACTIVE'});setError('');setModalOpen(true);};
 const save=async()=>{if(!form.sku.trim()||!form.name.trim()){setError('SKU y nombre son obligatorios.');return;}setSaving(true);setError('');const payload={sku:form.sku.trim(),barcode:form.barcode.trim()||null,name:form.name.trim(),description:form.description.trim()||null,brand:form.brand.trim()||null,costPrice:Number(form.costPrice||0),minStock:Number(form.minStock||0),reorderPoint:Number(form.reorderPoint||0),maxStock:Number(form.maxStock||100),status:form.status,prices:[{priceType:'LIST',amount:Number(form.listPrice||0)},{priceType:'MINIMUM_AUTHORIZED',amount:Number(form.minimumPrice||0)}]};try{await apiClient(editing?`/api/products/${editing.id}`:'/api/products',{method:editing?'PATCH':'POST',body:JSON.stringify(payload)});setModalOpen(false);await load();}catch(e:any){setError(e?.message||'No se pudo guardar el producto.');}finally{setSaving(false);}};
 const remove=async(p:Product)=>{if(!confirm(`Eliminar ${p.name} (${p.sku})?\n\nSolo se permitirá si no tiene historial operativo.`))return;setDeletingId(p.id);setError('');try{await apiClient(`/api/products/${p.id}`,{method:'DELETE'});await load();}catch(e:any){setError(e?.message||'No se pudo eliminar el producto.');}finally{setDeletingId('');}};
 return <AppShell title="Productos"><main className="mx-auto max-w-7xl px-3 py-3 sm:px-4 sm:py-5">
  <section className="rounded-[24px] bg-[#12224A] p-4 text-white sm:rounded-[28px] sm:p-5"><div className="flex items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#C79A3B]">Catálogo comercial</p><h1 className="mt-1 text-xl font-black sm:text-2xl">Productos</h1><p className="mt-1 text-xs text-slate-300 sm:text-sm">Catálogo, costos y precios autorizados.</p></div>{canManage&&<button onClick={openNew} className="flex min-h-12 shrink-0 items-center gap-2 rounded-2xl bg-[var(--bitalis-action)] px-4 text-xs font-black text-white"><Plus className="h-4 w-4"/>NUEVO</button>}</div></section>
  {error&&<div role="alert" className="mt-3 rounded-2xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}
  <section className="mt-3 grid grid-cols-2 gap-2 sm:gap-3"><K icon={<Package/>} label="Productos" value={products.length}/><K icon={<Tag/>} label="Activos" value={active}/></section>
  <div className="relative mt-3"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar producto o SKU" aria-label="Buscar productos" className="min-h-12 w-full rounded-2xl border border-slate-200 bg-white pl-11 pr-4 text-sm outline-none focus:ring-2 focus:ring-[var(--bitalis-action)]"/></div>
  {loading?<div className="flex justify-center p-12"><Loader2 className="h-6 w-6 animate-spin text-[#12224A]"/></div>:<section className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.map(p=>{const price=priceOf(p,'LIST')||priceOf(p,'LIST_PRICE'),stock=(p.stocks||[]).reduce((a,x)=>a+n(x.quantityAvailable??(n(x.quantityOnHand)-n(x.quantityReserved))),0),image=imageOf(p);return <article key={p.id} className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex gap-3">{image?<img src={image} alt={p.name} className="h-16 w-16 shrink-0 rounded-2xl object-cover"/>:<div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl bg-slate-100"><Boxes className="h-6 w-6 text-slate-400"/></div>}<div className="min-w-0 flex-1"><p className="text-[9px] font-black uppercase text-slate-400">{p.sku||'SIN SKU'}</p><h2 className="truncate text-base font-black text-[#12224A]">{p.name}</h2><p className="mt-1 truncate text-[11px] text-slate-500">{p.brand||p.description||'Sin descripción'}</p></div><Status value={p.status||'ACTIVE'}/></div><div className="mt-3 grid grid-cols-2 gap-2"><Metric label="Precio lista" value={price?money.format(price):'—'}/><Metric label="Disponible" value={(p.stocks||[]).length?stock.toLocaleString('es-MX'):'—'}/></div>{canManage&&<div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>openEdit(p)} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-emerald-50 text-xs font-black text-emerald-800"><Pencil className="h-4 w-4"/>EDITAR</button><button disabled={deletingId===p.id} onClick={()=>remove(p)} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-red-50 text-xs font-black text-red-700 disabled:opacity-50">{deletingId===p.id?<Loader2 className="h-4 w-4 animate-spin"/>:<Trash2 className="h-4 w-4"/>}ELIMINAR</button></div>}</article>})}{!filtered.length&&<div className="rounded-3xl border border-slate-200 bg-white p-8 text-center text-sm text-slate-500 md:col-span-2 xl:col-span-3">No hay productos que coincidan.</div>}</section>}
  {modalOpen&&<div data-no-swipe className="fixed inset-0 z-[170] overflow-y-auto bg-slate-950/60 p-3" onClick={()=>!saving&&setModalOpen(false)}><section onClick={e=>e.stopPropagation()} className="mx-auto my-3 max-w-xl rounded-[28px] bg-white p-4 shadow-2xl sm:p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.12em] text-[var(--bitalis-action)]">{editing?'Editar producto':'Nuevo producto'}</p><h2 className="mt-1 text-xl font-black text-[var(--bitalis-primary)]">{editing?.name||'Agregar al catálogo'}</h2></div><button disabled={saving} onClick={()=>setModalOpen(false)} className="flex h-11 w-11 items-center justify-center rounded-2xl bg-slate-100"><X className="h-5 w-5"/></button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="SKU" value={form.sku} onChange={v=>setForm({...form,sku:v})}/><Field label="Código de barras" value={form.barcode} onChange={v=>setForm({...form,barcode:v})}/><div className="sm:col-span-2"><Field label="Nombre" value={form.name} onChange={v=>setForm({...form,name:v})}/></div><Field label="Marca" value={form.brand} onChange={v=>setForm({...form,brand:v})}/><label><span className="text-xs font-black text-slate-500">Estado</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="mt-2 min-h-12 w-full rounded-2xl border border-slate-200 bg-slate-50 px-3"><option value="ACTIVE">Activo</option><option value="INACTIVE">Inactivo</option><option value="DISCONTINUED">Descontinuado</option></select></label><div className="sm:col-span-2"><Field label="Descripción" value={form.description} onChange={v=>setForm({...form,description:v})}/></div><Num label="Costo" value={form.costPrice} onChange={v=>setForm({...form,costPrice:v})}/><Num label="Precio lista" value={form.listPrice} onChange={v=>setForm({...form,listPrice:v})}/><Num label="Precio mínimo autorizado" value={form.minimumPrice} onChange={v=>setForm({...form,minimumPrice:v})}/><Num label="Stock mínimo" value={form.minStock} onChange={v=>setForm({...form,minStock:v})}/><Num label="Punto de reorden" value={form.reorderPoint} onChange={v=>setForm({...form,reorderPoint:v})}/><Num label="Stock máximo" value={form.maxStock} onChange={v=>setForm({...form,maxStock:v})}/></div><div className="mt-4 flex gap-3 rounded-2xl bg-amber-50 p-3 text-[11px] font-bold leading-5 text-amber-800"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0"/>Eliminar solo está disponible para productos sin historial. Para productos usados, selecciona Descontinuado.</div><button disabled={saving} onClick={save} className="mt-4 flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-[var(--bitalis-action)] text-sm font-black text-white disabled:opacity-50">{saving?<Loader2 className="h-5 w-5 animate-spin"/>:<Save className="h-5 w-5"/>}{editing?'GUARDAR CAMBIOS':'AGREGAR PRODUCTO'}</button></section></div>}
 </main></AppShell>;
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block"><span className="text-xs font-black text-slate-500">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="mt-2 min-h-12 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm outline-none focus:border-[var(--bitalis-action)]"/></label>}
function Num({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block"><span className="text-xs font-black text-slate-500">{label}</span><input inputMode="decimal" value={value} onChange={e=>onChange(e.target.value)} className="mt-2 min-h-12 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 text-sm outline-none focus:border-[var(--bitalis-action)]"/></label>}
function K({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="rounded-3xl border border-slate-200 bg-white p-4"><div className="text-[#C79A3B]">{icon}</div><p className="mt-2 text-[10px] font-black uppercase text-slate-400">{label}</p><p className="text-2xl font-black text-[#12224A]">{value}</p></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-slate-50 p-3"><p className="text-[9px] font-black uppercase text-slate-400">{label}</p><p className="mt-1 text-base font-black text-[#12224A]">{value}</p></div>}
function Status({value}:{value:string}){const off=value!=='ACTIVE';return <span className={`h-fit shrink-0 rounded-full px-2 py-1 text-[8px] font-black ${off?'bg-slate-100 text-slate-500':'bg-emerald-50 text-emerald-700'}`}>{value==='DISCONTINUED'?'DESCONT.':value==='INACTIVE'?'INACTIVO':'ACTIVO'}</span>}
