'use client';

import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {AlertTriangle,Banknote,Boxes,ChevronRight,ClipboardList,Coins,MapPinned,RefreshCw,Repeat2,Route,ShieldCheck,ShoppingBag,TrendingUp,UserCog,UserPlus,Users,WalletCards,Camera,Sparkles} from 'lucide-react';
import AppShell,{useShellPermissions,useShellSessionUser} from '@/components/phase15/AppShell';
import {apiClient} from '@/lib/phase15/apiClient';
import {haptic} from '@/lib/ux/haptics';

type ModuleItem=[string,string,string,any,string];
const money=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0});

const sellerModules:ModuleItem[]=[['Alta rápida','Fotos + GPS + nombre','/clients/new',Camera,'clients.create'],['Nueva venta','Contado o crédito','/sales/new',ShoppingBag,'sales.create'],['Clientes','CRM y prospectos','/clients',Users,'clients.view'],['Productos','Catálogo visual','/products',Boxes,'inventory.view'],['Renovaciones','Seguimiento','/renewals',Repeat2,'renewals.view'],['Comisiones','Ventas y total','/commissions',Coins,'commissions.view']];
const supervisorModules:ModuleItem[]=[['Alta rápida','Campo: fotos + GPS','/clients/new',Camera,'clients.create'],['Enganches','Corte y entrega diaria','/supervision/down-payments',Banknote,'sales.view'],['Renovaciones','Cartera por renovar','/renewals',Repeat2,'renewals.view'],['Autorizaciones','Pendientes del equipo','/authorizations',ShieldCheck,'sales.approve'],['Centro de control','Operación 360','/control-center',TrendingUp,'reports.view'],['Ruta','Cobranza en campo','/route',MapPinned,'route.view'],['Caja','Diferencias y arqueo','/cash',Banknote,'cash.view'],['Reportes','Equipo y zona','/reports',ClipboardList,'reports.view']];
const roleModules:Record<string,ModuleItem[]>={COBRADOR:[['Ruta','Navegar y visitar','/route',Route,'route.view'],['Cobrar','Cobro rápido','/collections',WalletCards,'collections.view'],['Clientes','Expediente 360','/clients',Users,'clients.view'],['Caja','Efectivo y arqueo','/cash',Banknote,'cash.view'],['Comisiones','Cobranza efectiva','/commissions',Coins,'commissions.view']],VENDEDORA:sellerModules,VENDEDOR:sellerModules,SUPERVISORA:supervisorModules,SUPERVISOR:supervisorModules,ADMIN:[['Usuarios','Roles y permisos','/settings/users',UserCog,'users.manage'],['Clientes','CRM 360','/clients',Users,'clients.view'],['Ventas','Operación comercial','/sales',ShoppingBag,'sales.view'],['Autorizaciones','Excepciones','/authorizations',ShieldCheck,'sales.approve'],['Reportes','Analítica','/reports',ClipboardList,'reports.view'],['Comisiones','Esquemas y cálculo','/commissions',Coins,'commissions.view']]};

export default function Dashboard(){
 const router=useRouter();
 const permissions=useShellPermissions();
 const user=useShellSessionUser();
 const[portfolio,setPortfolio]=useState<any[]>([]),[sales,setSales]=useState<any[]>([]),[clients,setClients]=useState<any[]>([]),[cash,setCash]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refreshKey,setRefreshKey]=useState(0);
 const go=(p:string)=>{haptic('tap');router.push(p)};
 const canCollections=permissions?.has('collections.view')===true,canSalesView=permissions?.has('sales.view')===true,canSalesCreate=permissions?.has('sales.create')===true,canClientsView=permissions?.has('clients.view')===true,canClientsCreate=permissions?.has('clients.create')===true,canCash=permissions?.has('cash.view')===true,canRoute=permissions?.has('route.view')===true;

 useEffect(()=>{if(!user)return;let alive=true;setLoading(true);setError('');if(!canCollections)setPortfolio([]);if(!canSalesView)setSales([]);if(!canClientsView)setClients([]);if(!canCash)setCash(null);(async()=>{const [p,s,c,cs]=await Promise.allSettled([canCollections?apiClient('/api/collections/portfolio'):Promise.resolve(null),canSalesView?apiClient('/api/sales'):Promise.resolve(null),canClientsView?apiClient('/api/clients?page=1&limit=100'):Promise.resolve(null),canCash?apiClient(`/api/cash-sessions/current?userId=${encodeURIComponent(user.id)}`):Promise.resolve(null)]);if(!alive)return;const failed:string[]=[];if(canCollections){if(p.status==='fulfilled')setPortfolio((p.value as any)?.data||[]);else failed.push('cobranza');}if(canSalesView){if(s.status==='fulfilled')setSales((s.value as any)?.sales||(s.value as any)?.data||[]);else failed.push('ventas');}if(canClientsView){if(c.status==='fulfilled')setClients((c.value as any)?.data||[]);else failed.push('clientes');}if(canCash){if(cs.status==='fulfilled')setCash((cs.value as any)?.data||null);else failed.push('caja');}if(failed.length)setError(`Algunos datos no se actualizaron: ${failed.join(', ')}. Puedes seguir trabajando con el resto de la información.`);setLoading(false);})();return()=>{alive=false;};},[user,canCollections,canSalesView,canClientsView,canCash,refreshKey]);

 const retry=()=>{haptic('tap');setRefreshKey(value=>value+1);};
 const role=String(user?.role||'').toUpperCase();
 const modules=(roleModules[role]||[]).filter(([, , , ,permission])=>permissions?.has(permission));
 const cartera=portfolio.reduce((sum,x)=>sum+Number(x.saldoActual||0),0),overdue=portfolio.filter(x=>x.collection?.overdue||['HIGH','CRITICAL'].includes(String(x.client?.riskLevel||''))).length,promises=portfolio.filter(x=>x.collection?.latestRescheduleDate).length,approvedSales=sales.filter(x=>['APPROVED','COMPLETED'].includes(x.status)),creditSales=approvedSales.filter(x=>x.saleType==='CREDIT').length,salesAmount=approvedSales.reduce((s,x)=>s+Number(x.totalAmount||0),0);
 const name=[user?.firstName,user?.lastName].filter(Boolean).join(' ')||user?.email||'Usuario';
 const isCollector=role==='COBRADOR',isSeller=['VENDEDORA','VENDEDOR'].includes(role),isSupervisor=['SUPERVISORA','SUPERVISOR'].includes(role),isAdmin=role==='ADMIN';
 const heroTitle=isCollector?'Tu jornada de cobranza':isSeller?'Captura rápida y venta en campo':isSupervisor?'Supervisión operativa en campo':'Resumen ejecutivo de hoy';
 const kpis=useMemo(()=>{const items:any[]=[];if(isCollector){if(canCollections)items.push([WalletCards,'Cobros pendientes',portfolio.length],[TrendingUp,'Cartera',money.format(cartera)],[AlertTriangle,'Atrasados',overdue],[Repeat2,'Promesas',promises]);if(canClientsView&&canCollections)items.push([Users,'Clientes',new Set(portfolio.map(x=>x.clientId)).size]);if(canCash)items.push([Banknote,'Caja actual',cash?money.format(Number(cash.expectedCash||0)):'Sin abrir']);return items;}if(isSeller){if(canSalesView)items.push([ShoppingBag,'Ventas',approvedSales.length],[TrendingUp,'Monto vendido',money.format(salesAmount)],[WalletCards,'Ventas crédito',creditSales]);if(canClientsView)items.push([Users,'Clientes',clients.length]);return items;}if(canSalesView)items.push([ShoppingBag,'Ventas',approvedSales.length]);if(canCollections)items.push([WalletCards,'Cartera',money.format(cartera)],[AlertTriangle,'Riesgo alto',overdue]);if(canClientsView)items.push([Users,'Clientes',clients.length]);return items;},[isCollector,isSeller,canCollections,canClientsView,canCash,canSalesView,portfolio,cartera,overdue,promises,cash,approvedSales.length,salesAmount,clients.length,creditSales]);
 const heroActions=(isCollector&&(canCollections||canRoute))||((isSeller||isSupervisor)&&(canClientsCreate||canSalesCreate));

 return <AppShell title="Inicio"><div className="mx-auto max-w-7xl px-3 py-3 sm:px-4 sm:py-5">
  <section className={`overflow-hidden bg-[var(--bitalis-primary)] text-white shadow-lg shadow-emerald-950/10 ${isAdmin?'rounded-[24px] p-4':'rounded-[28px] p-4 sm:p-7'}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[var(--bitalis-mint)]">{role||'BITALIS'}</p><h1 className={`${isAdmin?'mt-1 text-xl':'mt-2 text-2xl sm:text-3xl'} truncate font-black`}>Hola, {name}</h1><p className={`${isAdmin?'mt-1':'mt-2'} text-sm leading-5 text-emerald-50/80`}>{heroTitle}</p></div><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-white/10"><Sparkles className="h-5 w-5 text-[var(--bitalis-mint)]"/></div></div>{heroActions&&isCollector&&<div className={`mt-5 grid gap-2 ${canCollections&&canRoute?'grid-cols-2':'grid-cols-1'}`}>{canCollections&&<button onClick={()=>go('/collections')} className="min-h-14 rounded-2xl bg-[var(--bitalis-action)] px-2 text-xs font-black active:scale-95">+ COBRAR</button>}{canRoute&&<button onClick={()=>go('/route')} className="min-h-14 rounded-2xl bg-white/10 px-2 text-xs font-black active:scale-95">VER RUTA</button>}</div>}{heroActions&&(isSeller||isSupervisor)&&<div className={`mt-5 grid gap-2 ${canClientsCreate&&canSalesCreate?'grid-cols-2':'grid-cols-1'}`}>{canClientsCreate&&<button onClick={()=>go('/clients/new')} className="min-h-14 rounded-2xl bg-[var(--bitalis-action)] px-2 text-xs font-black active:scale-95">ALTA RÁPIDA</button>}{canSalesCreate&&<button onClick={()=>go('/sales/new')} className="min-h-14 rounded-2xl bg-white/10 px-2 text-xs font-black active:scale-95">NUEVA VENTA</button>}</div>}</section>
  {error&&<div className="mt-4 flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-3 text-sm font-bold text-amber-900"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0"/><div className="min-w-0 flex-1"><p>{error}</p><button type="button" onClick={retry} disabled={loading} className="mt-2 inline-flex min-h-11 items-center gap-2 rounded-xl bg-white px-3 text-xs font-black text-[var(--bitalis-primary)] shadow-sm disabled:opacity-50"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>REINTENTAR ACTUALIZACIÓN</button></div></div>}
  {kpis.length>0&&<section className={`${isAdmin?'mt-3':'mt-4'} grid grid-cols-2 gap-2 sm:gap-3 lg:grid-cols-4`}>{loading?Array.from({length:Math.min(Math.max(kpis.length,1),isCollector?6:4)}).map((_,i)=><div key={i} className="min-h-[92px] rounded-2xl border border-[var(--bitalis-border)] bg-white p-3 shadow-sm"><div className="h-4 w-4 rounded bg-emerald-100"/><div className="mt-3 h-2.5 w-20 rounded bg-slate-100"/><div className="mt-2 h-5 w-24 max-w-full rounded bg-slate-100"/></div>):kpis.map(([Icon,l,v]:any)=><K key={l} I={Icon} l={l} v={v} compact={isAdmin}/>)}</section>}
  <div className={`${isAdmin?'mt-4':'mt-6'} flex items-center justify-between gap-3`}><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[var(--bitalis-action)]">{isAdmin?'Administración':'Accesos'}</p><h2 className="text-lg font-black text-[var(--bitalis-primary)] sm:text-xl">{isAdmin?'Gestión rápida':'Tu operación'}</h2></div>{(isSeller||isSupervisor)&&canClientsCreate&&<button onClick={()=>go('/clients/new')} className="flex min-h-11 items-center gap-2 rounded-xl bg-white px-3 text-xs font-black text-[var(--bitalis-primary)] shadow-sm"><UserPlus className="h-4 w-4"/><span className="hidden min-[370px]:inline">Cliente</span></button>}</div>
  <section className={`${isAdmin?'mt-2 grid grid-cols-2 gap-2':'mt-3 grid gap-2 sm:grid-cols-2 sm:gap-3'} lg:grid-cols-3 xl:grid-cols-4`}>{modules.map(([title,sub,path,Icon])=><button key={path} onClick={()=>go(path)} className={`border border-[var(--bitalis-border)] bg-white text-left shadow-sm active:scale-[.98] ${isAdmin?'flex min-h-[86px] flex-col justify-between gap-2 rounded-2xl p-3':'flex min-h-[92px] items-center gap-3 rounded-3xl p-3 sm:min-h-28 sm:p-4'}`}><div className={`${isAdmin?'h-9 w-9 rounded-xl':'h-11 w-11 rounded-2xl'} flex shrink-0 items-center justify-center bg-[var(--bitalis-primary)] text-white`}><Icon className="h-5 w-5"/></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-1"><p className="truncate text-sm font-black text-[var(--bitalis-primary)]">{title}</p>{isAdmin&&<ChevronRight className="h-3.5 w-3.5 shrink-0 text-slate-300"/>}</div><p className="mt-0.5 line-clamp-2 text-[10px] leading-3 text-slate-500">{sub}</p></div>{!isAdmin&&<ChevronRight className="h-4 w-4 shrink-0 text-slate-300"/>}</button>)}</section>
 </div></AppShell>;
}
function K({I,l,v,compact=false}:{I:any;l:string;v:any;compact?:boolean}){return <div className={`min-w-0 border border-[var(--bitalis-border)] bg-white shadow-sm ${compact?'rounded-2xl p-3':'rounded-3xl p-3 sm:p-4'}`}><I className={`${compact?'h-4 w-4':'h-5 w-5'} text-[var(--bitalis-action)]`}/><p className={`${compact?'mt-2 text-[8px]':'mt-3 text-[9px]'} truncate font-black uppercase tracking-[.09em] text-slate-400`}>{l}</p><p className={`${compact?'text-base':'text-lg'} mt-1 break-words font-black leading-tight text-[var(--bitalis-primary)]`}>{v}</p></div>}
