'use client';

import {useEffect,useMemo,useState} from 'react';
import {Check,KeyRound,Loader2,MinusCircle,Plus,Search,ShieldCheck,UserCog,Users,X} from 'lucide-react';
import AppShell from '@/components/phase15/AppShell';
import {apiClient} from '@/lib/phase15/apiClient';

type Override={user_id:string;permission_code:string;effect:'ALLOW'|'DENY'};
type User={id:string;email:string;phone?:string|null;firstName:string;lastName:string;accountStatus:string;permissionVersion:number;role?:string|null;permissionOverrides?:Override[];effectivePermissionCodes?:string[]};
type Role={id:string;name:string;description?:string|null;permissionCodes:string[]};
type Permission={id:string;code:string;description?:string|null};
const defaultPermissions=['dashboard.view','clients.view','clients.create','clients.edit','clients.delete','sales.view','sales.create','sales.approve','collections.view','collections.collect','route.view','route.manage','cash.view','cash.operate','cash.close','inventory.view','inventory.manage','renewals.view','renewals.manage','commissions.view','reports.view','audit.view','users.manage','settings.manage'];
const roles=['ADMIN','SUPERVISORA','VENDEDORA','COBRADOR'];
const areaLabels:Record<string,string>={dashboard:'Panel',clients:'Clientes',sales:'Ventas',collections:'Cobranza',route:'Rutas',cash:'Caja',inventory:'Stock',renewals:'Renovaciones',commissions:'Comisiones',reports:'Reportes',audit:'Auditoría',users:'Usuarios',settings:'Configuración'};
const actionLabels:Record<string,string>={view:'Ver',create:'Crear',edit:'Editar',delete:'Eliminar',approve:'Autorizar',collect:'Cobrar',manage:'Administrar',operate:'Operar',close:'Cerrar'};
const permissionLabel=(code:string)=>{const[area,action]=code.split('.');return `${actionLabels[action]||action||'Acceso'} · ${areaLabels[area]||area||code}`;};
const statusStyle=(s:string)=>s==='ACTIVE'?'bg-emerald-50 text-emerald-700':s==='LOCKED'?'bg-amber-50 text-amber-700':'bg-red-50 text-red-700';

export default function UsersSettingsPage(){
 const[users,setUsers]=useState<User[]>([]),[roleData,setRoleData]=useState<Role[]>([]),[permissions,setPermissions]=useState<Permission[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[activeRole,setActiveRole]=useState('SUPERVISORA'),[showCreate,setShowCreate]=useState(false),[activeUserId,setActiveUserId]=useState(''),[resetUserId,setResetUserId]=useState(''),[resetPassword,setResetPassword]=useState('');
 const[form,setForm]=useState({firstName:'',lastName:'',email:'',phone:'',password:'',role:'VENDEDORA'});
 const load=async()=>{setLoading(true);setError('');try{const j:any=await apiClient('/api/admin/access');setUsers(j.users||[]);setRoleData(j.roles||[]);setPermissions(j.permissions||[]);}catch(e:any){setError(e.message||'No se pudo cargar usuarios y permisos.');}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const allCodes=useMemo(()=>Array.from(new Set([...defaultPermissions,...permissions.map(p=>p.code)])).sort(),[permissions]);
 const selected=new Set(roleData.find(r=>r.name===activeRole)?.permissionCodes||[]);
 const filtered=users.filter(u=>`${u.firstName} ${u.lastName} ${u.email} ${u.role}`.toLowerCase().includes(query.toLowerCase()));
 const activeUser=users.find(u=>u.id===activeUserId)||null,resetUser=users.find(u=>u.id===resetUserId)||null;
 const post=async(body:any,message?:string)=>{setSaving(true);setError('');setNotice('');try{await apiClient('/api/admin/access',{method:'POST',body:JSON.stringify(body)} as any);await load();if(message)setNotice(message);return true;}catch(e:any){setError(e.message||'No se pudo guardar.');return false;}finally{setSaving(false);}};
 const createUser=async()=>{const ok=await post({action:'createUser',...form},`Usuario ${form.email.trim().toLowerCase()} creado y activo.`);if(ok){setShowCreate(false);setForm({firstName:'',lastName:'',email:'',phone:'',password:'',role:'VENDEDORA'});}};
 const doReset=async()=>{if(!resetUser)return;const ok=await post({action:'resetPassword',userId:resetUser.id,password:resetPassword},`Contraseña restablecida para ${resetUser.email}.`);if(ok){setResetUserId('');setResetPassword('');}};
 const togglePermission=async(code:string)=>{const next=new Set(selected);next.has(code)?next.delete(code):next.add(code);await post({action:'setRolePermissions',role:activeRole,permissionCodes:Array.from(next)});};
 const effectFor=(u:User,code:string)=>u.permissionOverrides?.find(x=>x.permission_code===code)?.effect||'INHERIT';
 const setOverride=(u:User,code:string,effect:'ALLOW'|'DENY'|'INHERIT')=>post({action:'setUserPermissionOverride',userId:u.id,permissionCode:code,effect});
 return <AppShell title="Usuarios y permisos"><main className="mx-auto max-w-7xl px-3 py-3 sm:px-4 sm:py-5">
  <section className="rounded-[24px] bg-[#12224A] p-4 text-white sm:rounded-[30px] sm:p-7"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.14em] text-[#C79A3B]"><ShieldCheck className="h-4 w-4"/>Operación real</div><h1 className="mt-2 text-xl font-black sm:text-2xl">Usuarios y permisos</h1><p className="mt-1 max-w-2xl text-xs leading-5 text-slate-300 sm:text-sm">Crea cuentas reales, asigna el rol, entrega una contraseña temporal y controla el acceso desde aquí.</p></div><button onClick={()=>setShowCreate(v=>!v)} className="flex min-h-11 shrink-0 items-center gap-2 rounded-xl bg-[#FF6A00] px-3 text-[10px] font-black sm:min-h-12 sm:rounded-2xl sm:px-4 sm:text-xs"><Plus className="h-4 w-4"/><span className="hidden sm:inline">Nuevo usuario</span></button></div></section>
  {error&&<div role="alert" className="mt-3 rounded-2xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}{notice&&<div className="mt-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-bold text-emerald-700">{notice}</div>}
  {showCreate&&<section className="mt-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:rounded-3xl"><h2 className="font-black text-[#12224A]">Dar acceso a una persona</h2><p className="mt-1 text-xs text-slate-500">El correo será su usuario. La contraseña debe tener 8+ caracteres, mayúscula, minúscula y número.</p><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[['Nombre','firstName'],['Apellidos','lastName'],['Correo','email'],['Teléfono','phone'],['Contraseña temporal','password']].map(([label,key])=><label key={key} className="text-xs font-bold text-slate-600">{label}<input autoComplete={key==='password'?'new-password':key==='email'?'email':'off'} inputMode={key==='email'?'email':key==='phone'?'tel':undefined} type={key==='password'?'password':key==='email'?'email':'text'} value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-1 min-h-12 w-full rounded-2xl border border-slate-200 px-4 outline-none focus:ring-2 focus:ring-[#FF6A00]"/></label>)}<label className="text-xs font-bold text-slate-600">Rol<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className="mt-1 min-h-12 w-full rounded-2xl border border-slate-200 px-4">{roles.map(r=><option key={r}>{r}</option>)}</select></label></div><button disabled={saving||!form.firstName.trim()||!form.lastName.trim()||!form.email.trim()||!form.password} onClick={createUser} className="mt-4 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-[#12224A] text-sm font-black text-white disabled:opacity-40">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Check className="h-4 w-4"/>}CREAR Y ACTIVAR USUARIO</button></section>}
  {loading?<div className="flex justify-center p-16"><Loader2 className="h-7 w-7 animate-spin text-[#12224A]"/></div>:<section className="mt-4 grid gap-4 lg:grid-cols-[1.05fr_.95fr] sm:mt-5 sm:gap-5">
   <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:rounded-3xl"><div className="flex items-center gap-2 text-sm font-black text-[#12224A]"><Users className="h-5 w-5"/>Usuarios reales</div><p className="mt-1 text-xs text-slate-500">{users.length} cuentas registradas · {users.filter(u=>u.accountStatus==='ACTIVE').length} activas</p><div className="relative mt-3"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nombre, correo o rol" className="min-h-12 w-full rounded-2xl border border-slate-200 pl-11 pr-4"/></div><div className="mt-3 space-y-2">{filtered.map(u=><div key={u.id} className="rounded-2xl border border-slate-200 p-3"><div className="flex items-start gap-3"><button onClick={()=>setActiveUserId(u.id)} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-slate-100 text-[#12224A]" aria-label={`Permisos de ${u.firstName}`}><UserCog className="h-5 w-5"/></button><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate font-black text-[#12224A]">{u.firstName} {u.lastName}</p><p className="truncate text-xs text-slate-500">{u.email}</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-[9px] font-black ${statusStyle(u.accountStatus)}`}>{u.accountStatus==='ACTIVE'?'ACTIVO':u.accountStatus}</span></div><div className="mt-2 grid grid-cols-2 gap-2"><select value={u.role||''} onChange={e=>post({action:'setUserRole',userId:u.id,role:e.target.value},'Rol actualizado.')} className="min-h-10 rounded-xl border border-slate-200 px-2 text-[11px] font-bold"><option value="" disabled>Sin rol</option>{roles.map(r=><option key={r}>{r}</option>)}</select><select value={u.accountStatus} onChange={e=>post({action:'setUserStatus',userId:u.id,status:e.target.value},'Estado actualizado.')} className="min-h-10 rounded-xl border border-slate-200 px-2 text-[11px] font-bold"><option value="ACTIVE">Activo</option><option value="INACTIVE">Inactivo</option><option value="LOCKED">Bloqueado</option><option value="SUSPENDED">Suspendido</option></select></div><div className="mt-2 grid grid-cols-2 gap-2"><button onClick={()=>setActiveUserId(u.id)} className="min-h-10 rounded-xl border border-slate-200 bg-slate-50 text-[9px] font-black text-[#12224A]">PERMISOS</button><button onClick={()=>{setResetUserId(u.id);setResetPassword('');}} className="min-h-10 rounded-xl border border-amber-200 bg-amber-50 text-[9px] font-black text-amber-800"><KeyRound className="mr-1 inline h-3.5 w-3.5"/>NUEVA CLAVE</button></div></div></div></div>)}</div></article>
   <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:rounded-3xl"><div className="flex items-center gap-2 text-sm font-black text-[#12224A]"><KeyRound className="h-5 w-5"/>Permisos por rol</div><p className="mt-1 text-xs leading-5 text-slate-500">Los cuatro roles ya nacen con permisos operativos base. Puedes afinarlos aquí.</p><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-2">{roles.map(r=><button key={r} onClick={()=>setActiveRole(r)} className={`min-h-11 rounded-xl text-[10px] font-black ${activeRole===r?'bg-[#12224A] text-white':'bg-slate-100 text-slate-600'}`}>{r}</button>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-2">{allCodes.map(code=><button key={code} disabled={saving} onClick={()=>togglePermission(code)} className={`flex min-h-12 items-center justify-between rounded-2xl border px-3 text-left text-[11px] font-black ${selected.has(code)?'border-emerald-200 bg-emerald-50 text-emerald-800':'border-slate-200 bg-white text-slate-500'}`}><span className="truncate pr-2">{permissionLabel(code)}</span><span className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full ${selected.has(code)?'bg-emerald-500 text-white':'bg-slate-100'}`}>{selected.has(code)&&<Check className="h-3.5 w-3.5"/>}</span></button>)}</div></article>
  </section>}
  {resetUser&&<div className="fixed inset-0 z-[130] flex items-end bg-slate-950/70 p-0 backdrop-blur-sm sm:items-center sm:justify-center sm:p-4" onClick={()=>setResetUserId('')}><section onClick={e=>e.stopPropagation()} className="w-full rounded-t-[30px] bg-white p-5 sm:max-w-md sm:rounded-[30px]"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#C79A3B]">Restablecer acceso</p><h2 className="mt-1 text-xl font-black text-[#12224A]">{resetUser.firstName} {resetUser.lastName}</h2><p className="mt-1 text-xs text-slate-500">{resetUser.email}</p></div><button onClick={()=>setResetUserId('')} className="flex h-11 w-11 items-center justify-center rounded-2xl bg-slate-100"><X className="h-5 w-5"/></button></div><label className="mt-4 block text-xs font-bold text-slate-600">Nueva contraseña temporal<input autoFocus autoComplete="new-password" type="password" value={resetPassword} onChange={e=>setResetPassword(e.target.value)} className="mt-2 min-h-14 w-full rounded-2xl border border-slate-200 px-4 text-base outline-none focus:ring-2 focus:ring-[#FF6A00]"/></label><p className="mt-2 text-[11px] leading-5 text-slate-500">Mínimo 8 caracteres, una mayúscula, una minúscula y un número. Si la cuenta estaba bloqueada por intentos fallidos se desbloqueará.</p><button disabled={saving||!resetPassword} onClick={doReset} className="mt-4 flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-[#FF6A00] text-sm font-black text-white disabled:opacity-40">{saving?<Loader2 className="h-5 w-5 animate-spin"/>:<KeyRound className="h-5 w-5"/>}RESTABLECER CONTRASEÑA</button></section></div>}
  {activeUser&&<div className="fixed inset-0 z-[120] flex items-end bg-slate-950/70 backdrop-blur-sm sm:items-center sm:justify-center sm:p-4" onClick={()=>setActiveUserId('')}><section onClick={e=>e.stopPropagation()} className="max-h-[90vh] w-full overflow-y-auto rounded-t-[30px] bg-white p-4 sm:max-w-3xl sm:rounded-[30px] sm:p-5"><div className="sticky top-0 z-10 -mx-1 flex items-start justify-between bg-white/95 px-1 pb-3 backdrop-blur"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#C79A3B]">Permisos individuales</p><h2 className="mt-1 text-xl font-black text-[#12224A]">{activeUser.firstName} {activeUser.lastName}</h2><p className="mt-1 text-xs text-slate-500">Rol: {activeUser.role||'Sin rol'}</p></div><button onClick={()=>setActiveUserId('')} className="flex h-11 w-11 items-center justify-center rounded-2xl bg-slate-100"><X className="h-5 w-5"/></button></div><div className="space-y-2">{allCodes.map(code=>{const effect=effectFor(activeUser,code),inherited=roleData.find(r=>r.name===activeUser.role)?.permissionCodes.includes(code)||false,effective=activeUser.effectivePermissionCodes?.includes(code)||false;return <article key={code} className="rounded-2xl border border-slate-200 p-3"><div className="flex items-center justify-between gap-2"><div className="min-w-0"><p className="truncate text-xs font-black text-[#12224A]">{permissionLabel(code)}</p><p className="mt-1 text-[9px] text-slate-500">Rol: {inherited?'permitido':'no permitido'} · Acceso final: {effective?'permitido':'denegado'}</p></div><span className={`rounded-full px-2 py-1 text-[9px] font-black ${effective?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700'}`}>{effective?'SÍ':'NO'}</span></div><div className="mt-2 grid grid-cols-3 gap-1.5"><button disabled={saving} onClick={()=>setOverride(activeUser,code,'INHERIT')} className={`min-h-10 rounded-xl text-[9px] font-black ${effect==='INHERIT'?'bg-slate-700 text-white':'bg-slate-100 text-slate-500'}`}>HEREDAR</button><button disabled={saving} onClick={()=>setOverride(activeUser,code,'ALLOW')} className={`min-h-10 rounded-xl text-[9px] font-black ${effect==='ALLOW'?'bg-emerald-500 text-white':'bg-emerald-50 text-emerald-700'}`}><Check className="mx-auto h-3.5 w-3.5"/></button><button disabled={saving} onClick={()=>setOverride(activeUser,code,'DENY')} className={`min-h-10 rounded-xl text-[9px] font-black ${effect==='DENY'?'bg-red-500 text-white':'bg-red-50 text-red-700'}`}><MinusCircle className="mx-auto h-3.5 w-3.5"/></button></div></article>})}</div></section></div>}
 </main></AppShell>;
}
