'use client';

import {useEffect,useMemo,useState} from 'react';
import {Check,KeyRound,Loader2,Plus,Search,ShieldCheck,UserCog,Users} from 'lucide-react';
import AppShell from '@/components/phase15/AppShell';
import {apiClient} from '@/lib/phase15/apiClient';

type User={id:string;email:string;phone?:string|null;firstName:string;lastName:string;accountStatus:string;permissionVersion:number;role?:string|null};
type Role={id:string;name:string;description?:string|null;permissionCodes:string[]};
type Permission={id:string;code:string;description?:string|null};
const defaultPermissions=['dashboard.view','clients.view','clients.create','clients.edit','clients.delete','sales.view','sales.create','sales.approve','collections.view','collections.collect','route.view','route.manage','cash.view','cash.operate','cash.close','inventory.view','inventory.manage','renewals.view','renewals.manage','commissions.view','reports.view','audit.view','users.manage','settings.manage'];
const roles=['ADMIN','SUPERVISORA','VENDEDORA','COBRADOR'];

export default function UsersSettingsPage(){
 const[users,setUsers]=useState<User[]>([]),[roleData,setRoleData]=useState<Role[]>([]),[permissions,setPermissions]=useState<Permission[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[activeRole,setActiveRole]=useState('SUPERVISORA'),[showCreate,setShowCreate]=useState(false);
 const[form,setForm]=useState({firstName:'',lastName:'',email:'',phone:'',password:'',role:'VENDEDORA'});
 const load=async()=>{setLoading(true);setError('');try{const j:any=await apiClient('/api/admin/access');setUsers(j.users||[]);setRoleData(j.roles||[]);setPermissions(j.permissions||[]);}catch(e:any){setError(e.message||'No se pudo cargar usuarios y permisos.');}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const allCodes=useMemo(()=>Array.from(new Set([...defaultPermissions,...permissions.map(p=>p.code)])).sort(),[permissions]);
 const selected=new Set(roleData.find(r=>r.name===activeRole)?.permissionCodes||[]);
 const filtered=users.filter(u=>`${u.firstName} ${u.lastName} ${u.email} ${u.role}`.toLowerCase().includes(query.toLowerCase()));
 const post=async(body:any)=>{setSaving(true);setError('');try{await apiClient('/api/admin/access',{method:'POST',body:JSON.stringify(body)} as any);await load();}catch(e:any){setError(e.message||'No se pudo guardar.');}finally{setSaving(false);}};
 const createUser=async()=>{await post({action:'createUser',...form});setShowCreate(false);setForm({firstName:'',lastName:'',email:'',phone:'',password:'',role:'VENDEDORA'});};
 const togglePermission=async(code:string)=>{const next=new Set(selected);next.has(code)?next.delete(code):next.add(code);await post({action:'setRolePermissions',role:activeRole,permissionCodes:Array.from(next)});};
 return <AppShell title="Usuarios y permisos"><main className="mx-auto max-w-7xl px-4 py-5"><section className="rounded-[30px] bg-[#12224A] p-5 text-white sm:p-7"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.14em] text-[#C79A3B]"><ShieldCheck className="h-4 w-4"/>Administración de acceso</div><h1 className="mt-3 text-2xl font-black">Usuarios y permisos</h1><p className="mt-2 max-w-2xl text-sm text-slate-300">Crea usuarios, cambia roles, bloquea cuentas y define qué módulos puede utilizar cada rol.</p></div><button onClick={()=>setShowCreate(v=>!v)} className="flex min-h-12 shrink-0 items-center gap-2 rounded-2xl bg-[#FF6A00] px-4 text-xs font-black"><Plus className="h-4 w-4"/>Usuario</button></div></section>
 {error&&<div className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}
 {showCreate&&<section className="mt-4 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="font-black text-[#12224A]">Nuevo usuario</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[['Nombre','firstName'],['Apellidos','lastName'],['Correo','email'],['Teléfono','phone'],['Contraseña temporal','password']].map(([label,key])=><label key={key} className="text-xs font-bold text-slate-600">{label}<input type={key==='password'?'password':'text'} value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-1 min-h-12 w-full rounded-2xl border border-slate-200 px-4 outline-none focus:ring-2 focus:ring-[#FF6A00]"/></label>)}<label className="text-xs font-bold text-slate-600">Rol<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className="mt-1 min-h-12 w-full rounded-2xl border border-slate-200 px-4">{roles.map(r=><option key={r}>{r}</option>)}</select></label></div><button disabled={saving} onClick={createUser} className="mt-4 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-[#12224A] text-sm font-black text-white disabled:opacity-50">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Check className="h-4 w-4"/>}Crear usuario</button></section>}
 {loading?<div className="flex justify-center p-16"><Loader2 className="h-7 w-7 animate-spin text-[#12224A]"/></div>:<><section className="mt-5 grid gap-5 lg:grid-cols-[1.05fr_.95fr]"><article className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div><div className="flex items-center gap-2 text-sm font-black text-[#12224A]"><Users className="h-5 w-5"/>Usuarios</div><p className="mt-1 text-xs text-slate-500">{users.length} cuentas registradas</p></div></div><div className="relative mt-3"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar usuario" className="min-h-12 w-full rounded-2xl border border-slate-200 pl-11 pr-4"/></div><div className="mt-3 space-y-2">{filtered.map(u=><div key={u.id} className="rounded-2xl border border-slate-200 p-3"><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-slate-100 text-[#12224A]"><UserCog className="h-5 w-5"/></div><div className="min-w-0 flex-1"><p className="truncate font-black text-[#12224A]">{u.firstName} {u.lastName}</p><p className="truncate text-xs text-slate-500">{u.email}</p><div className="mt-2 grid grid-cols-2 gap-2"><select value={u.role||'VENDEDORA'} onChange={e=>post({action:'setUserRole',userId:u.id,role:e.target.value})} className="min-h-10 rounded-xl border border-slate-200 px-2 text-[11px] font-bold">{roles.map(r=><option key={r}>{r}</option>)}</select><select value={u.accountStatus} onChange={e=>post({action:'setUserStatus',userId:u.id,status:e.target.value})} className="min-h-10 rounded-xl border border-slate-200 px-2 text-[11px] font-bold"><option>ACTIVE</option><option>INACTIVE</option><option>LOCKED</option><option>SUSPENDED</option></select></div></div></div></div>)}</div></article>
 <article className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-2 text-sm font-black text-[#12224A]"><KeyRound className="h-5 w-5"/>Permisos por rol</div><p className="mt-1 text-xs leading-5 text-slate-500">Estos permisos complementan el RBAC del servidor. Cambiar un rol incrementa la versión de permisos de sus usuarios.</p><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-2">{roles.map(r=><button key={r} onClick={()=>setActiveRole(r)} className={`min-h-11 rounded-xl text-[10px] font-black ${activeRole===r?'bg-[#12224A] text-white':'bg-slate-100 text-slate-600'}`}>{r}</button>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-2">{allCodes.map(code=><button key={code} disabled={saving} onClick={()=>togglePermission(code)} className={`flex min-h-12 items-center justify-between rounded-2xl border px-3 text-left text-[11px] font-black ${selected.has(code)?'border-emerald-200 bg-emerald-50 text-emerald-800':'border-slate-200 bg-white text-slate-500'}`}><span className="truncate pr-2">{code}</span><span className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full ${selected.has(code)?'bg-emerald-500 text-white':'bg-slate-100'}`}>{selected.has(code)&&<Check className="h-3.5 w-3.5"/>}</span></button>)}</div></article></section></>}
 </main></AppShell>;
}
