'use client';

import {useEffect,useMemo,useState} from 'react';
import {CheckCircle2,Clock3,Loader2,Search,ShieldCheck,SlidersHorizontal,X,XCircle} from 'lucide-react';
import AppShell from '@/components/phase15/AppShell';
import {apiClient} from '@/lib/phase15/apiClient';
import {haptic} from '@/lib/ux/haptics';

type Item={id:string;type:string;status:string;reason?:string|null;createdAt:string;proposedPrice?:number|null;minimumPrice?:number|null;sale?:{saleNumber:string;client?:{firstName:string;lastName:string;clientNumber:string}};product?:{name:string;sku:string}};
type Decision={item:Item;value:'APPROVED'|'REJECTED'}|null;
const visibleReason=(value?:string|null)=>String(value||'').split('\nMETA:')[0].split('\nRESOLUCIÓN:')[0];
const typeLabel=(value:string)=>value.replaceAll('_',' ').toLowerCase().replace(/(^|\s)\S/g,m=>m.toUpperCase());
const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();

export default function AuthorizationsPage(){
 const[items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[query,setQuery]=useState(''),[type,setType]=useState('ALL'),[decision,setDecision]=useState<Decision>(null),[reason,setReason]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const j:any=await apiClient('/api/authorizations');setItems(j?.data||[]);}catch(e:any){setError(e.message||'No pudimos cargar las autorizaciones.');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const pending=useMemo(()=>items.filter(x=>x.status==='PENDING'),[items]);
 const types=useMemo(()=>Array.from(new Set(pending.map(x=>x.type))),[pending]);
 const visible=useMemo(()=>{const terms=normalize(query).split(/\s+/).filter(Boolean);return pending.filter(item=>{if(type!=='ALL'&&item.type!==type)return false;const name=item.sale?.client?`${item.sale.client.firstName} ${item.sale.client.lastName} ${item.sale.client.clientNumber}`:item.product?`${item.product.name} ${item.product.sku}`:'';const text=normalize(`${name} ${item.sale?.saleNumber||''} ${item.type} ${visibleReason(item.reason)}`);return terms.every(term=>text.includes(term));});},[pending,query,type]);
 const openDecision=(item:Item,value:'APPROVED'|'REJECTED')=>{haptic('tap');setReason('');setDecision({item,value});};
 const close=()=>{if(!busy){setDecision(null);setReason('');}};
 const save=async()=>{if(!decision)return;const clean=reason.trim();if(decision.value==='REJECTED'&&clean.length<5){setError('Escribe un motivo de rechazo de al menos 5 caracteres.');return;}setBusy(decision.item.id);setError('');try{await apiClient(`/api/authorizations/${decision.item.id}`,{method:'PATCH',body:JSON.stringify({decision:decision.value,reason:clean})});haptic('success');setDecision(null);setReason('');await load();}catch(e:any){setError(e.message||'No pudimos guardar la decisión.');haptic('error');}finally{setBusy('');}};
 return <AppShell title="Autorizaciones"><main className="mx-auto max-w-7xl px-3 py-3 sm:px-4 sm:py-5">
  <section className="rounded-[26px] bg-[var(--bitalis-primary)] p-4 text-white sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.14em] text-[var(--bitalis-mint)]"><ShieldCheck className="h-4 w-4"/>Supervisión segura</p><h1 className="mt-2 text-2xl font-black">Autorizaciones pendientes</h1><p className="mt-1 text-xs leading-5 text-emerald-50/75">Decide excepciones con motivo, trazabilidad y una sola acción por solicitud.</p></div><div className="rounded-2xl bg-white/10 px-3 py-2 text-center"><b className="block text-2xl text-[var(--bitalis-mint)]">{pending.length}</b><span className="text-[9px] font-black uppercase">Pendientes</span></div></div></section>
  {error&&<div role="alert" className="mt-3 flex items-start justify-between gap-2 rounded-2xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700"><span>{error}</span><button onClick={()=>setError('')} className="h-8 w-8 shrink-0 rounded-lg" aria-label="Cerrar error"><X className="mx-auto h-4 w-4"/></button></div>}
  <section className="sticky top-[76px] z-20 mt-3 rounded-[22px] border border-slate-200 bg-slate-50/95 p-2 shadow-sm backdrop-blur sm:static sm:p-3"><div className="relative"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cliente, folio, producto, motivo…" className="min-h-12 w-full rounded-2xl border border-slate-200 bg-white pl-11 pr-11 text-sm outline-none focus:ring-2 focus:ring-[var(--bitalis-action)]"/>{query&&<button onClick={()=>setQuery('')} className="absolute right-1 top-1/2 flex h-10 w-10 -translate-y-1/2 items-center justify-center" aria-label="Limpiar búsqueda"><X className="h-4 w-4"/></button>}</div><div data-no-swipe className="mt-2 flex gap-2 overflow-x-auto pb-1"><Filter active={type==='ALL'} onClick={()=>setType('ALL')} label="Todas"/>{types.map(value=><Filter key={value} active={type===value} onClick={()=>setType(value)} label={typeLabel(value)}/>)}</div></section>
  {loading?<div className="flex justify-center p-12"><Loader2 className="h-7 w-7 animate-spin text-[var(--bitalis-primary)]"/></div>:visible.length?<section className="mt-3 grid gap-3 lg:grid-cols-2">{visible.map(item=><article key={item.id} className="rounded-[24px] border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><span className="inline-flex rounded-full bg-amber-50 px-2.5 py-1 text-[9px] font-black text-amber-800">{typeLabel(item.type)}</span><h2 className="mt-2 truncate text-lg font-black text-[var(--bitalis-primary)]">{item.sale?.client?`${item.sale.client.firstName} ${item.sale.client.lastName}`:item.product?.name||'Solicitud'}</h2><p className="mt-1 text-[10px] text-slate-500">{item.sale?.saleNumber||item.product?.sku||''}</p></div><span className="flex shrink-0 items-center gap-1 text-[9px] font-bold text-slate-400"><Clock3 className="h-3.5 w-3.5"/>{new Date(item.createdAt).toLocaleDateString('es-MX',{day:'2-digit',month:'short'})}</span></div>{visibleReason(item.reason)&&<p className="mt-3 rounded-2xl bg-slate-50 p-3 text-xs leading-5 text-slate-600">{visibleReason(item.reason)}</p>}{item.proposedPrice!=null&&<div className="mt-3 grid grid-cols-2 rounded-2xl border border-slate-100"><Data label="Propuesto" value={money(item.proposedPrice)}/><Data label="Mínimo" value={item.minimumPrice!=null?money(item.minimumPrice):'—'}/></div>}<div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>openDecision(item,'REJECTED')} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl border border-red-200 bg-red-50 text-xs font-black text-red-700"><XCircle className="h-4 w-4"/>RECHAZAR</button><button onClick={()=>openDecision(item,'APPROVED')} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-[var(--bitalis-action)] text-xs font-black text-white"><CheckCircle2 className="h-4 w-4"/>APROBAR</button></div></article>)}</section>:<div className="mt-3 rounded-[24px] border border-dashed border-slate-300 bg-white p-10 text-center"><SlidersHorizontal className="mx-auto h-7 w-7 text-slate-300"/><p className="mt-2 font-black text-[var(--bitalis-primary)]">Sin pendientes en este filtro</p><p className="mt-1 text-xs text-slate-500">Cambia la búsqueda o el tipo de autorización.</p></div>}
  {decision&&<div className="fixed inset-0 z-[180] flex items-end bg-slate-950/55 backdrop-blur-sm sm:items-center sm:justify-center sm:p-4" onClick={close}><section role="dialog" aria-modal="true" className="bitalis-bottom-sheet w-full p-4 sm:max-w-md sm:rounded-[28px] sm:p-5" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-[10px] font-black uppercase tracking-widest text-[var(--bitalis-action)]">Decisión supervisada</p><h2 className="mt-1 text-xl font-black text-[var(--bitalis-primary)]">{decision.value==='APPROVED'?'Aprobar solicitud':'Rechazar solicitud'}</h2></div><button disabled={!!busy} onClick={close} className="h-11 w-11 rounded-xl bg-slate-100"><X className="mx-auto h-5 w-5"/></button></div><p className="mt-3 text-sm font-bold text-slate-600">{decision.item.sale?.client?`${decision.item.sale.client.firstName} ${decision.item.sale.client.lastName}`:decision.item.product?.name||'Solicitud'}</p><label className="mt-4 block"><span className="text-xs font-black text-slate-500">{decision.value==='REJECTED'?'Motivo obligatorio':'Nota opcional'}</span><textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={500} rows={4} placeholder={decision.value==='REJECTED'?'Explica claramente por qué se rechaza…':'Añade una observación para auditoría…'} className="mt-2 w-full resize-none rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm outline-none focus:ring-2 focus:ring-[var(--bitalis-action)]"/></label><button disabled={!!busy||(decision.value==='REJECTED'&&reason.trim().length<5)} onClick={()=>void save()} className={`mt-4 flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl text-sm font-black text-white disabled:opacity-40 ${decision.value==='APPROVED'?'bg-[var(--bitalis-action)]':'bg-red-600'}`}>{busy?<Loader2 className="h-5 w-5 animate-spin"/>:decision.value==='APPROVED'?<CheckCircle2 className="h-5 w-5"/>:<XCircle className="h-5 w-5"/>}{busy?'GUARDANDO…':'CONFIRMAR DECISIÓN'}</button></section></div>}
 </main></AppShell>;
}
const money=(value:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(value);
function Filter({active,onClick,label}:{active:boolean;onClick:()=>void;label:string}){return <button onClick={onClick} className={`min-h-10 shrink-0 rounded-full px-3 text-[10px] font-black ${active?'bg-[var(--bitalis-primary)] text-white':'border border-slate-200 bg-white text-slate-600'}`}>{label}</button>}
function Data({label,value}:{label:string;value:string}){return <div className="p-3 first:border-r first:border-slate-100"><p className="text-[9px] font-black uppercase text-slate-400">{label}</p><p className="mt-1 text-sm font-black text-[var(--bitalis-primary)]">{value}</p></div>}
