'use client';

import {FormEvent,useState} from 'react';
import {CheckCircle2,KeyRound,Loader2,ShieldCheck} from 'lucide-react';
import {useRouter} from 'next/navigation';
import AppShell from '@/components/phase15/AppShell';

export default function PasswordPage(){
 const router=useRouter();const[currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');if(newPassword!==confirmPassword){setError('Las contraseñas nuevas no coinciden.');return;}if(newPassword.length<8){setError('La nueva contraseña debe tener al menos 8 caracteres.');return;}setSaving(true);try{const token=localStorage.getItem('bitalis_access_token');const res=await fetch('/api/auth/change-password',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({currentPassword,newPassword})});const j=await res.json().catch(()=>({}));if(!res.ok||!j.success)throw new Error(j.message||'No pudimos cambiar la contraseña.');setDone(true);localStorage.removeItem('bitalis_access_token');localStorage.removeItem('bitalis_refresh_token');setTimeout(()=>router.replace('/'),1200);}catch(e:any){setError(e.message||'No pudimos cambiar la contraseña.');}finally{setSaving(false);}};
 return <AppShell title="Cambiar contraseña"><main className="mx-auto max-w-xl px-3 py-4 sm:px-4 sm:py-6"><section className="rounded-[26px] bg-[#12224A] p-5 text-white"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.14em] text-[#C79A3B]"><ShieldCheck className="h-4 w-4"/>Seguridad</div><h1 className="mt-2 text-2xl font-black">Cambiar contraseña</h1><p className="mt-2 text-sm text-slate-300">Cambia la contraseña temporal por una que solo tú conozcas. Al guardarla volverás al inicio de sesión.</p></section>{error&&<div role="alert" className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}{done?<div className="mt-4 rounded-3xl border border-emerald-200 bg-emerald-50 p-6 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-emerald-600"/><h2 className="mt-3 text-lg font-black text-[#12224A]">Contraseña actualizada</h2><p className="mt-1 text-sm text-slate-600">Volviendo al inicio de sesión…</p></div>:<form onSubmit={submit} className="mt-4 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><Field label="Contraseña actual" value={currentPassword} onChange={setCurrentPassword} current/><div className="mt-3"><Field label="Nueva contraseña" value={newPassword} onChange={setNewPassword}/></div><div className="mt-3"><Field label="Confirmar nueva contraseña" value={confirmPassword} onChange={setConfirmPassword}/></div><p className="mt-3 text-[11px] leading-5 text-slate-500">Mínimo 8 caracteres, una mayúscula, una minúscula y un número.</p><button disabled={saving||!currentPassword||!newPassword||!confirmPassword} className="mt-4 flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-[#FF6A00] text-sm font-black text-white disabled:opacity-40">{saving?<Loader2 className="h-5 w-5 animate-spin"/>:<KeyRound className="h-5 w-5"/>}CAMBIAR CONTRASEÑA</button></form>}</main></AppShell>;
}
function Field({label,value,onChange,current=false}:{label:string;value:string;onChange:(v:string)=>void;current?:boolean}){return <label className="block text-xs font-bold text-slate-600">{label}<input type="password" autoComplete={current?'current-password':'new-password'} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 min-h-14 w-full rounded-2xl border border-slate-200 px-4 text-base outline-none focus:ring-2 focus:ring-[#FF6A00]"/></label>}
